### ISSUE TITLE
ESP8266 not selectable in ios app

### ISSUE THREAD

**Issue by tzapu** [blynkkk/blynk-library#1]
Hi,

got the sketch working on an ESP8266 nodemcu board by selecting arduino yun in the ios app.
is there a better choice until the app is updated? 

trying to read pin analog0 results in a reboot of the esp.
cheers

**Comment by RobinMglsk** [comment]
I think it was a bug thats fixed in the new version thats still pending review on the itunes connect.
I addressed this issue on the android version and it was fixed the day after.

**Comment by tzapu** [comment]
thanks
