### ISSUE TITLE
We need doc. with list of all Blynk commands

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#10]
For instance :

Blynk.virtualWrite();
Blynk.isConnected();

etc...

**Comment by vshymanskyy** [comment]
You can easily generate the API documentation using Doxygen (doxygen.config is provided).
We will add more documentation later, I think it will be provided via a separate repository + site or wiki.

**Comment by vshymanskyy** [comment]
Basics doc was updated:
https://github.com/blynkkk/blynk-library/blob/master/docs/Basics.md
