### ISSUE TITLE
Add sketch showing how Blynk HTTP API could be used

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#100]
PUT/GET for pins

**Comment by vshymanskyy** [comment]
HTTP API is not intended to be used from HW side.
It would require many samples for different connection types.
I can provide only Ethernet or ESP8266 example.
Can you send the sketch you came up with?

**Comment by doom369** [comment]
I understand this, however at the moment I have conversation with guys that try to use Blynk based on HTTPS API. They have STM32F. If we want develop Blynk as platform we need to make integration with Blynk as quick as possible. 

I think even Ethernet example would be nice (HTTP and HTTPS).

You can understand main problem from this thread http://community.blynk.cc/t/solved-what-is-wrong-in-my-http-request-method-put/4588/16

**Comment by vshymanskyy** [comment]
STM32F - we're not covering...
"Ethernet example would be nice (HTTP and HTTPS)" - Ethernet Shield doesn't handle HTTPS...

**Comment by doom369** [comment]
@vshymanskyy hm? ok. Just HTTP would be also nice. Something like :

```
  String putData = "[\"1\"]";
  client.println("PUT /token/pin/V1 HTTP/1.1");
  client.println("Host:  blynk-cloud.com");
  client.println("Content-Type: application/json");
  client.print("Content-Length: ");
  client.println(putData.length());
  client.println();
  client.println(putData);
```
