### ISSUE TITLE
ESP + terminal == duplicated strings

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#102]
http://community.blynk.cc/t/terminal-widget-duplicate-strings/5050/12

**Comment by vshymanskyy** [comment]
This is not related to Blynk behaviour.
It is how SimpleTimer works. It triggers multiple times if the timer was missed due to micro-controller busy...
If you want different behaviour, you can use millis(), similar to https://www.arduino.cc/en/Tutorial/BlinkWithoutDelay
