### ISSUE TITLE
Add sketch for "labeled value" widget 

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#103]
Same as value display but with string formatting on UI.

- Reading sketch
- Pushing sketch

**Comment by vshymanskyy** [comment]
We have regular examples:
* PushData
* PushDataOnRequest
Are they sufficient?

**Comment by doom369** [comment]
Well, in general - yes. However I think separation is better. Also we can give direct links from docs to specific examples and show exactly difference between widgets.
