### ISSUE TITLE
Support Particle Electron

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#104]

**Comment by vshymanskyy** [comment]
Currently blocked by https://github.com/spark/firmware/issues/896#issuecomment-201481032

**Comment by doom369** [comment]
@vshymanskyy issue is fixed. Any update from our side?

**Comment by vshymanskyy** [comment]
It's not released yet. But working.

**Comment by vshymanskyy** [comment]
0.5.0 is released so it should work now (tested on rc2)
https://github.com/spark/firmware/releases/tag/v0.5.0
