### ISSUE TITLE
RTC makes real server request very rarely?

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#105]
We added TimeZone for RTC widget and after changing it on UI - RTC remains the same on hardware (for ~5 mins) I see that RTC sketch doesn't perform real requests to server.

Can this be fixed? Is that some kind of optimization or bug?

**Comment by vshymanskyy** [comment]
1. Yes it is a very important optimization
2. You can send the updated value, when it has changed - it should work.
3. setSyncInterval(interval); can be used to modify refresh time (according to Time library docs.)

**Comment by doom369** [comment]
Ok. It's fine for now.
