### ISSUE TITLE
Add sketch for MENU widget

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#107]

**Comment by vshymanskyy** [comment]
what's the API? Please don't set milestone, you don't know the scope...

**Comment by doom369** [comment]
> what's the API?
User selects value from combobox. Widget sends index of selected value starting from 1.

```
BLYNK_WRITE(V1) {
   switch (param.asInt())
       case 1 : //menu 1
       case 2 : //menu 2
       case 3 : //menu 3
}
```

@blynkkk correct?

**Comment by vshymanskyy** [comment]
Is it menu or combo box?

**Comment by doom369** [comment]
We call it menu. But logic it performs == combobox
