### ISSUE TITLE
Push notification widget issue

### ISSUE THREAD

**Issue by taro10h** [blynkkk/blynk-library#109]
blynk-library/examples/Widgets/PushNotification/PushNotification.ino
Blynk limit push notification to 1 message/minute. The current example includes a button click notification and a runtime notification. Because the runtime notification pushes every minute, it takes all message quota in the blynk server. The server may block other messages. Also, the button press snippet doesn't include a debounce part; it would send multiple messages to the server at the transient time. Then, the server will block the device because of those spamming messages. This issue will cause  "The device is offline" message which irritates many users.

Todo:
1/ Increase push message limitation?
2/ Disable runtime notification in this sketch
3/ Debounce the button
4/ Or try another way to illustrate push notification
Thanks!

**Comment by vshymanskyy** [comment]
Thanks, I will look into this.

**Comment by doom369** [comment]
@vshymanskyy we can split example on 2.
