### ISSUE TITLE
gauge won't read float

### ISSUE THREAD

**Issue by VoliKoN** [blynkkk/blynk-library#11]
sensors.requestTemperatures(); // Send the command to get temperatures
    float temp = sensors.getTempCByIndex(0);
    Serial.println(temp);
    Blynk.virtualWrite(5, temp);

above shows nothing.

    sensors.requestTemperatures(); // Send the command to get temperatures
    int temp = sensors.getTempCByIndex(0);
    Serial.println(temp);
    Blynk.virtualWrite(5, temp);

above shows only 28 (instead of 28.31)

**Comment by blynkkk** [comment]
Thank you for reporting. This is application bug. Looking into it.

**Comment by VoliKoN** [comment]
Negative value also shows nothing.

**Comment by doom369** [comment]
Fixed on apps. Will be available in next update.
