### ISSUE TITLE
Problem developing with multiple files

### ISSUE THREAD

**Issue by jacklol13** [blynkkk/blynk-library#112]
It seems the Blynk global variable is declared and defined in the same header file (Specific for each board). This means that Blynk Widgets API cannot be used outside of the main cpp (.ino) file because that throws a "multiple definitions" linker error.

A good example of this problem is when using the virtual terminal widget which requires all prints to be called from a global variable. That variable cannot be shared across files which means printing from different modules is impossible.

This might be fine for simple Arduino IDE "one file" projects, but as soon as larger projects with multiple files are needed, it is impossible to do properly.

**Comment by vshymanskyy** [comment]
It is necessary to put all blynk-related code into one ino and put the header there.
This is not limitation of Blynk itself, but rather the Arduino IDE - and it was made for simplicity.

**Comment by jacklol13** [comment]
And yet PlatformIO and other custom build systems support more than one C file.
This problem can easily be resolved by using "extern Blynk" in every board's H file and adding a C file to contain the actual global variable definition.
