### ISSUE TITLE
Add support for WildFireV4

### ISSUE THREAD

**Issue by ackushiw** [blynkkk/blynk-library#117]
The latest wildfire now uses the ESP 8266 as its wifi module.

**Comment by vshymanskyy** [comment]
@ackushiw Did you try if normal ESP8266 -standalone examples work with WF4?

**Comment by ackushiw** [comment]
@vshymanskyy I get this
`[65265] Blynk v0.3.4
[65766] Connecting to (ssid)
[66783] Failed to disable Echo
`

**Comment by ackushiw** [comment]
Here are the pins for v4
[https://docs.google.com/spreadsheets/d/1BqM1gniiG8M5_cpoPuO8JrL4PujZgr8S6vu16_zUoq4/edit#gid=0](url)

**Comment by ackushiw** [comment]
got it working with the hard serial. I had to set pin 23 (ESP8266-Enable) to HIGH

this is my setup 
```
int WIFIswitch =  23;
void setup()
{
  // Set console baud rate
  pinMode(WIFIswitch, OUTPUT);
  Serial.begin(9600);
  delay(10);
  // Set ESP8266 baud rate
  EspSerial.begin(115200);
  while(digitalRead(WIFIswitch) != HIGH)
  {
    Serial.println("Initializing...");
    digitalWrite(WIFIswitch, HIGH);
    delay(10);
  }
  Serial.println("Starting Blynk");
  Blynk.begin(auth, wifi, "kukijun", "alexander");

  
}
```

@vshymanskyy thanks for pointing me in the right direction!

**Comment by vshymanskyy** [comment]
@ackushiw glad you have got it working. could you send me the full working sketch, so I can include it as an example?
Thank you!

**Comment by vshymanskyy** [comment]
@ackushiw hi, could you look into this?
