### ISSUE TITLE
Is the Blynk library for ESP8266 SSL(HTTPS) by default?

### ISSUE THREAD

**Issue by cottsak** [blynkkk/blynk-library#126]

**Comment by vshymanskyy** [comment]
There are two separate exemples, SSL and non-SSL

**Comment by cottsak** [comment]
Can you provide links please?

**Comment by doom369** [comment]
[ESP8266 SSL](https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_WiFi/ESP8266_Standalone_SSL/ESP8266_Standalone_SSL.ino#L33)

[More examples](https://github.com/blynkkk/blynk-library/tree/master/examples/Boards_WiFi)

**Comment by cottsak** [comment]
@doom369 But what does https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_WiFi/ESP8266_Standalone_SSL/ESP8266_Standalone_SSL.ino#L33 mean exactly? Where is the line in that lib that makes the SSL/TLS request? Which lib is it using underneath to make that request? Is the cert fingerprint pinned for the Blynk server or is there a root CA list somewhere?

**Comment by doom369** [comment]
@cottsak please have a look in sketch comment.

**Comment by cottsak** [comment]
@doom369 Ok, so I've looked into https://github.com/blynkkk/blynk-library/blob/master/BlynkSimpleEsp8266_SSL.h and it seems that it's using the default ESP Arduino helpers which do now support SSL. Can a Blynk user choose to use `BlynkSimpleEsp8266` or `BlynkSimpleEsp8266_SSL` when they import into their sketch? 

I'm essentially trying to discover how easy it is for a novice to build some security-related home automation, and not realise the HTTP traffic to the Blynk server is not encrypted.

**Comment by vshymanskyy** [comment]
If you want to audit your system for security - please use "Blynk for Business".
