### ISSUE TITLE
 BLE Pushes not working reliably

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#127]
http://community.blynk.cc/t/ble-pushes-not-working-reliably/6416

**Comment by vshymanskyy** [comment]
We don't officially support this hardware

**Comment by Gaff** [comment]
I'm pretty sure it's an app issue not an arduino issue. Can you confirm that the sketch I posted works with any supported board?

@vshymanskyy: Seriously tell me what I need to do to get you to check this issue out? I'll happily send you one of the feather BLE boards if that's what it takes!   :smile:

**Comment by vshymanskyy** [comment]
Sorry, I cannot accept yiur board, cause I can't guaratee to get it working.

**Comment by Gaff** [comment]
I still think it's an app problem - Can you confirm my example works on *any* board?
