### ISSUE TITLE
Make LCD remember entire LCD display on App re-open (not just the Last "sent" values)

### ISSUE THREAD

**Issue by Phoenix260** [blynkkk/blynk-library#130]
if doing something like:

#define LCD_VIRTUAL             V13 // attach LCD to Virtual 13 complex mode
WidgetLCD LCD(LCD_VIRTUAL); // LCD widget. Global intialization.

LCD.print(0, 0, "Hello");
LCD.print(0, 1, "World");

only "World" will be displayed on the bottom line if the app was closed while sending this data, but opened after some time has passed since sending both commands ... Both should be displayed.

**Comment by vshymanskyy** [comment]
It is a known server issue, it's not related to he library.
Please post it here: https://github.com/blynkkk/blynk-server

**Comment by Phoenix260** [comment]
done, thanks!
