### ISSUE TITLE
Some board have the duty cycle between 0-1023 (by default is 0-255)

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#134]
BlynkBoard have range 0-1023
Like result if set up in Slider value 255 in output we have 0.8 V (max is 3.3 V)

**Comment by vshymanskyy** [comment]
Thanks, it will be fixed in next App releases.

**Comment by Refenz** [comment]
@vshymanskyy 
Any news?
P.S. i see in json BlynkBoard 0-255

**Comment by vshymanskyy** [comment]
All ESP8266 jsons are updated now, Thanks.

**Comment by vshymanskyy** [comment]
The original issue was related to different board type.
