### ISSUE TITLE
Add example sketch for "setProperty" feature

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#136]

**Comment by doom369** [comment]
@vshymanskyy apps and server ready.

**Comment by vshymanskyy** [comment]
Please provide list of properties

**Comment by doom369** [comment]
For now 

`label` and `color` should be enough.

**Comment by vshymanskyy** [comment]
what are example values?

**Comment by doom369** [comment]
@vshymanskyy here you go for Blynk Theme : 

white "#FFFFFF " -1
green "#23C48E " 600084223
dark blue "#5F7CD8 ” 1602017535
light blue "#04C0F8 " 79755519
orange "#ED9D00 " -308477697
red "#D3435C " -750560001

**Comment by doom369** [comment]
In general any color could be used, but we need to provide some predefined.

**Comment by doom369** [comment]
I think you can use few DEFINE for that fields. Like

`Blynk.setProperty(V1, COLOR, RED);`

**Comment by vshymanskyy** [comment]
I would prefer not to.
