### ISSUE TITLE
Arduino. Pin #13 turns off after stop-start project.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#139]
Reproduce for Arduino(use Nano)
1)Add button for pin #13 in "switch" mode
2)Start project
3)Press Button(Led is lights)
4)Stop project
5)Start project
Result: Button state is pressed. Pin#13 is LOW.
It is feature of Arduino?

**Comment by vshymanskyy** [comment]
What is the method of connection?

**Comment by Refenz** [comment]
@vshymanskyy 
via COM-port

**Comment by vshymanskyy** [comment]
Closed because lack of interest and available workarounds (virtual pins can be used to implement the desired behaviour).
