### ISSUE TITLE
BLYNK_WRITE not working on Arduino Due

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#141]

**Comment by fredmatic1** [comment]
here is my code for the Due..... I have an ESP01 on Serial2. That works great, but just does not want to accept any of the commands from my phone, however, data writes to the phone work just fine. I have an Arduino Pro Mini, (32u4), working just fine too.

[Due.txt](https://github.com/blynkkk/blynk-library/files/384798/Due.txt)

**Comment by vshymanskyy** [comment]
Just checked with Arduino Due, BLYNK_WRITE works perfectly
Arduino Pro Mini also works.
