### ISSUE TITLE
RedBearLab_BLE_Mini.ino example compiler issues

### ISSUE THREAD

**Issue by koraysels** [blynkkk/blynk-library#147]
[blynk-library/examples/Boards_BLE/RedBearLab_BLE_Mini/RedBearLab_BLE_Mini.ino](https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_BLE/RedBearLab_BLE_Mini/RedBearLab_BLE_Mini.ino#L35)

Hi I get a compiler error in the arduino IDE on line 35

I have no idea what that define statement does .. 

```
Blynk_BLE_tesy.ino: In function 'void setup()':
Blynk_BLE_tesy:35: error: 'Serial1' was not declared in this scope
Blynk_BLE_tesy.ino:42:3: note: in expansion of macro 'SerialBLE'
'Serial1' was not declared in this scope

```

EDIT: I am using a standard Arduino Uno board

**Comment by vshymanskyy** [comment]
I think it's better to use Leonardo or similar in this case..
You only have 1 Hw Serial on UNO, so it will be inconvenient

**Comment by vshymanskyy** [comment]
@koraysels was this issue resolved?

**Comment by koraysels** [comment]
yeah i think so :) thanks!

**Comment by koraysels** [comment]
Do you think I could use [SoftSerial](https://www.arduino.cc/en/Reference/SoftwareSerial) ?
