### ISSUE TITLE
Fatal Error during 'wiring pi'

### ISSUE THREAD

**Issue by zbutcher** [blynkkk/blynk-library#148]
Had this happen (see below) while trying to install Blynk per this video https://www.youtube.com/watch?v=ZJcYiSFiMY8 Not sure if it has to do with 404 error from https://github.com/blynkkk/blynk-library/blob/master/docs/Platforms.md#linux-raspberry-pi (recommended by same creator in his older video) or that http://wiringpi.com/ no longer exists. Total n00b so any help with how to solve this would be really appreciated. - Thx

Cloning into 'wiringPi'...
remote: git: error while loading shared libraries: libcrypto.so.1.0.0: failed to map segment from shared object: Cannot allocate memory
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: index-pack failed
./build.sh: line 9: cd: wiringPi: No such file or directory
Already up-to-date.
./build.sh: line 11: ./build: No such file or directory
./build.sh: line 12: gpio: command not found

**Comment by zbutcher** [comment]
After doing some more research I was able to finally get BLYNK to work via this community thread (by user bvdbrule) http://community.blynk.cc/t/could-anyone-help-me-with-the-raspberry-pi-b-and-blynk/1103/3 along with the assistance of this video https://youtu.be/ZJcYiSFiMY8 (coincidentally from same creator as the one I had initial trouble with). Not sure what's (technically) different about doin' it this way but regardless, excited that it's now working and looking forward to now having some fun. Thanks again for creating BLYNK so noobs like myself can explore what otherwise was too difficult. :)

**Comment by vshymanskyy** [comment]
Thank you! ;)
Glad that it worked!
