### ISSUE TITLE
Arduino not compile SetProperty sketch

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#158]
Updated IDE and library, show next:
D:\Program\Arduino\libraries\Blynk\examples\More\SetProperty\SetProperty.ino: In function 'void BlynkWidgetWrite1(BlynkReq&, const BlynkParam&)':
SetProperty:67: error: 'class BlynkEthernet' has no member named 'setProperty'
     Blynk.setProperty(V0, "color", gaugeColor);
           ^
Несколько библиотек найдено для "BlynkSimpleEthernet.h"
 Используется: C:\Users\Roma\Documents\Arduino\libraries\Blynk
Не используется: D:\Program\Arduino\libraries\Blynk
Не используется: D:\Program\Arduino\libraries\Blynk
Не используется: D:\Program\Arduino\libraries\Blynk
Не используется: D:\Program\Arduino\libraries\Blynk
exit status 1
'class BlynkEthernet' has no member named 'setProperty'

**Comment by vshymanskyy** [comment]
You need to update the whole blynk library from master

**Comment by Refenz** [comment]
Yes, i did.
Problem is present.

**Comment by vshymanskyy** [comment]
https://travis-ci.org/blynkkk/blynk-library/jobs/156389650
CI indicates this sketch build is ok. I think you just need to check that you're using latest source  code.
Closing for now.
