### ISSUE TITLE
TimeInput sketch

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#160]
`param[0].asInt()` - startAt (always present). Seconds of a day with user timezone applied. Could be negative in case of SUNSET/SUNRISE.
`param[1].asInt()` - stopAt (optional). Seconds of a day with user timezone applied. Could be negative in case of SUNSET/SUNRISE.
`param[2].asInt()` - timezone (always present). Seconds of zimezone "+03:00" is equal to 10800.
`param[3].asString()` - comma separated indexes of day of week (optional). Ex : "1,2,3" is Monday, Tuesday, Wednesday.

**Comment by vshymanskyy** [comment]
Partially implemented

**Comment by doom369** [comment]
@vshymanskyy startAt is seconds of a day. Range is 0 < x < 86400.

**Comment by vshymanskyy** [comment]
@doom369 oh, ok ))

**Comment by vshymanskyy** [comment]
@doom369 : comma separated indexes of day of week, is optional:
do we consider all days selected, if this is missing?

**Comment by vshymanskyy** [comment]
If any changes needed - let's discuss in slack

**Comment by doom369** [comment]
@vshymanskyy in future please mark commits with #TICKET_NUMBER so I anyone can track it from tickets.
