### ISSUE TITLE
TimeInput example should be simplified

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#163]
I think 90% of Blynk users don't know what `BlynkTime&` is. Can we get rid of it?

**Comment by doom369** [comment]
@vshymanskyy maybe something like 

`timeInput.getStartHour()`?

**Comment by vshymanskyy** [comment]
is API ok?

**Comment by doom369** [comment]
@vshymanskyy fine for now.

Please consider also adding `TimeInputParam.hasStartTime()` `hasStopTime()` methods in future to avoid adding `switch` in code.
