### ISSUE TITLE
LCD often causes flood

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#175]
http://community.blynk.cc/t/zergba-virtualsync-lcd-widget/8028/3

**Comment by vshymanskyy** [comment]
This is normal behaviour, as per flood definition.

**Comment by doom369** [comment]
only 9 writes cause flood? Look like lib bug.

**Comment by vshymanskyy** [comment]
Ok, need to check. should be 20 at least. (or it was called actually twice)

**Comment by vshymanskyy** [comment]
To be fixed with #182
