### ISSUE TITLE
Sync feature causes problems on hardware side 

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#179]
> I think syncAll struggles if there are more than a handful of pins to sync and can result in command skipped messages.
> 
> I sometimes use a one time timer to sync a few seconds after the initial connection has been made, which normally helps.

http://community.blynk.cc/t/read-timeinput-widget/8072/9

**Comment by doom369** [comment]
@vshymanskyy one more issue - http://community.blynk.cc/t/hardware-init-connecting-to-blynk-server-takes-long-time/8155/5. Several Sync commands for different pins also cause problems. Please consider adding `Blynk.virtualSync(V1, V2, V3, V4, V5, etc);` method instead of many syncs.

**Comment by vshymanskyy** [comment]
So, maybe server should wait a bit between sending the commands...

**Comment by doom369** [comment]
So let's introduce proposed command, to avoid flood. With proposed command there will be just 1 packet.

**Comment by vshymanskyy** [comment]
Implemented on library side
