### ISSUE TITLE
Using ESP8266 as an Arduino Shield

### ISSUE THREAD

**Issue by terrag42** [blynkkk/blynk-library#18]
Hello, 
I've had success using Blynk with my ESP8266 in standalone mode, now I'd like to use it as an Arduino shield. I am trying to flash the correct AT firmware so I can use the [ITEADLIB_Arduino_WeeESP8266 library](https://github.com/itead/ITEADLIB_Arduino_WeeESP8266). I saw in the examples that Blynk uses this library, and it requires version 0.22 AT firmware. I downloaded this firmware from the [Espressif website](http://bbs.espressif.com/viewtopic.php?f=46&t=286), but the instructions on which .bin files to flash were not clear to me. I ended up using the [NodeMCU flasher program](https://github.com/nodemcu/nodemcu-flasher) to flash three .bin files at different offsets:
boot_v1.2.bin at 0x00000
user1.512.new.bin at 0x01000
blank.bin at 0x7E000
When I communicated with the ESP using ESPlorer, I typed AT+GMR and got some numbers back, but when I tried it with the ITEADLIB_Arduino_WeeESP8266 library and an Arduino Mega, I was not able to start UART communication. I posted an issue on the ITEADLIB_Arduino_WeeESP8266 github page a few days ago but haven't gotten a response. Since I am using hardware serial with version 0.22 firmware, I did not modify the .h file in the ESP8266 library. Any ideas?

**Comment by vshymanskyy** [comment]
I think you missed a point that you need a MODified itead library... please check comments in the example sketch and tell us if it helps...

**Comment by terrag42** [comment]
Hello vshymanskyy, thanks for the response. 
>Since I am using hardware serial with version 0.22 firmware, I did not modify the .h file in the ESP8266 library.

It was my understanding that the modification to the .h file in the itead library if only necessary if you're using software serial or a version of the AT firmware other than 0.22 or both.

**Comment by vshymanskyy** [comment]
No, actually you need the *modified* library AND the link is in the sketch...

**Comment by vshymanskyy** [comment]
Did it help?

**Comment by terrag42** [comment]
I took a step back and spent about an hour last night trying to get my ESP-201 to talk to a 3.3v version of an Arduino Pro Mini running the "bare minimum" sketch. I figured that I should be able to type "AT" in the serial monitor in the Arduino IDE and receive "OK" from the ESP-201. 
To prepare my ESP, I grounded GPIO 0 and I used the NodeMCU flasher program to load version 0.22 of Espressif's AT firmware with the offsets mentioned in my first post. Then I plugged my serial communication tool (voltage switched to 3.3v) into the Arduino and connected the ESP RX<->RX and TX<->TX because the Arduino is not actually communicating with the ESP in this setup, it's acting as a pass-through. I was able to receive some nonsense characters when applying power to the ESP at baud rates 9600 and 115200, but no response to "AT". 
After trying the same procedure with the 0.30 AT firmware (latest one from Espressif) and having no success, I gave up. I used the Arduino IDE to load the ESP (in standalone mode) with my Blynk + DHT22 sketch so I could have some sense of satisfaction (it works great). 
If you have any thoughts on what I'm doing wrong or how I can see "AT", "OK" on the Arduino serial monitor running the bare minimum sketch, I'd love to hear them.

**Comment by scropion86** [comment]
you must use ESP FW from SDK v1.0 that has AT code V22
any other version - older or newer - will not work as the Current SDK v1.4 has many APIdepreciated
and some of them used to make ESP work as Shield.

also try the latest Blynk 3.1 has many improvements for ESP8266 as shield.

i have it working now in two device in my home-with the old library- i will update my code to work with the latest library to be more stable as i'am getting disconnections randomly during the day.
