### ISSUE TITLE
Add Samsung Artik board example and JSON

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#180]

**Comment by vshymanskyy** [comment]
Needs proper integration of https://www.npmjs.com/package/artik-sdk
and https://github.com/artik-iot/artik-sdk/blob/master/doc/GPIO_README.md.

**Comment by vshymanskyy** [comment]
Current effort estimation is 2-3md

**Comment by vshymanskyy** [comment]
now tracked in roadmap
