### ISSUE TITLE
Provide a solution (concept) for virtualWrite for top 4 hardware models not to cause flood and not using external timer libs  

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#182]

**Comment by jaggil** [comment]
Hello, I have a project with ESP that uses "Blink.setProperty" and I would like to know if you have an estimate date to correct it
Greetings and thanks in advance

**Comment by vshymanskyy** [comment]
I added 1.0.0 milestone, but there's no estimate right now - it's not planned any time soon.
Just use timers for now..

**Comment by jaggil** [comment]
OK thanks
Is the minimum delay time known to ensure that the error does not occur?
