### ISSUE TITLE
Add BlynkBoard to Platformio

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#183]

**Comment by vshymanskyy** [comment]
@ivankravets , let's discuss this

**Comment by ivankravets** [comment]
Hey :) 

I've already added http://platformio.org/boards?count=15&filter%5Bname%5D=Blynk&page=1&sorting%5Bvendor%5D=asc

**Comment by vshymanskyy** [comment]
@ivankravets 
Ok, thank you.
Only need to fix Flash size - it's 4MBytes (32Mbit flash)

**Comment by ivankravets** [comment]
Done! :)

https://github.com/platformio/platform-espressif8266/commit/38628fcebd79d55f77f289d8a36486aefcc56de0
