### ISSUE TITLE
Edison SimpleTimer Error

### ISSUE THREAD

**Issue by michaelllh** [blynkkk/blynk-library#184]
Why it will appear the error when I using SimpleTimer in the code ?
It printf "**B0100000063f694"   ,what the problem might be ?

**Comment by vshymanskyy** [comment]
Yes, we know this problem. Unfortunately there's almost no way getting rid of it without changing Simple Timer API ...

**Comment by michaelllh** [comment]
I have solve this problem.I change the source code of SimpleTimer. I move the constructor code to the method of set SimpleTimer ,Then it works!

**Comment by vshymanskyy** [comment]
We fixed the issue, it will be available in new library release.
