### ISSUE TITLE
Add QRs for basic example skethces.

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#191]
So uses don't have to put widgets by themselfы. Will simplify start a lot.

**Comment by vshymanskyy** [comment]
1. We will start with GettingStarted.
2. Hardware-related QR's don't make sense.

Even for GettingStarted, for some examples, we don't know which type of board is used, (and direct pins are used)

**Comment by vshymanskyy** [comment]
#171 - related

**Comment by vshymanskyy** [comment]
To be added in "Example Browser": #249
