### ISSUE TITLE
Provide sketch and JSON for Light Blue Bean

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#195]

**Comment by vshymanskyy** [comment]
Light Blue Bean and Bean+ confirmed both working, but very unstable.

**Comment by doom369** [comment]
@vshymanskyy so move from debug to release folder?

**Comment by vshymanskyy** [comment]
No, stability is very bad, need to meet again and investigate

**Comment by vshymanskyy** [comment]
Example is provided here
https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_BLE/LightBlue_Bean/LightBlue_Bean.ino

**Comment by vshymanskyy** [comment]
now tracked in roadmap
