### ISSUE TITLE
ESP8266 - Sketch

### ISSUE THREAD

**Issue by sticilface** [blynkkk/blynk-library#2]
Can ```Blynk.begin(auth, "ssid", "pass");``` be called without specifying the wifi credentials.  If we are managing it elsewhere?

**Comment by tzapu** [comment]
if this is possible, it would be good to also have a non standalone example sketch, just to easily see how to add blynk as an addon to our existing esp projects

**Comment by sticilface** [comment]
you can easily add it to existing projects.  

```
#include <BlynkSimpleEsp8266.h>

char auth[] = "xyz";


void setup() {

Blynk.begin(auth, "ssid", "pass");
}

void loop () {
Blynk.run();
}

// This takes the value of virtual pin 0 in blynk program...  if it is 1 turns on, else off...
BLYNK_WRITE(0)
{
  int a = param.asInt();
  if (a == 1) opState = RAINBOW; else opState = OFF;
}

//// This publishes the int power back to the blynk program...

BLYNK_READ(1)
{
  int power = getPixelPower();
  Blynk.virtualWrite(0, power);
}

**Comment by tzapu** [comment]
hi, i meant the same as you "Can Blynk.begin(auth, "ssid", "pass"); be called without specifying the wifi credentials. If we are managing it elsewhere? ".

i already have the wifi connection taken care of in another lib..

**Comment by tzapu** [comment]
another issue closely related to blynk managing the wifi connection is that if it fails to connect there s nothing i can do anymore, like reset the esp or try another access point, etc, it s just stuck there

**Comment by vshymanskyy** [comment]
I'm now working to enable connect/disconnect from Blynk server.. cheers :)

**Comment by vshymanskyy** [comment]
Guys, in the master branch I have implemented 3 features:
  1. Now you can call Blynk.disconnect() and Blynk.connect() to control connection to the server.
  2. Instead of calling Blynk.begin(...) you can call Blynk.config(auth) or Blynk.config(auth, server, port)
      this won't try to setup WiFi, Ethernet, etc. only token and server.
      there is also Blynk.connectWiFi(ssid, pass) - you can call it before Blynk.config(..) for ease of use.
  3. begin(..) and connectWiFi(..) will try to connect to Open network if pass is empty ("")

Please evaluate :)

**Comment by tzapu** [comment]
this works lovely, thank you very much

**Comment by chinswain** [comment]
Any plants to make these changes to BlynkSimpleShieldEsp8266 vshymanskyy?

**Comment by vshymanskyy** [comment]
@chinswain what's the problem?

**Comment by pieman64** [comment]
@vshymanskyy please see this thread that explains the question from @chinswain 
http://community.blynk.cc/t/esp8266-as-a-shield-wifi-recovery/11666
