### ISSUE TITLE
myPlant: remove notifications code from sketch

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#208]
we don't have it in the app, let's keep it clear.

**Comment by vshymanskyy** [comment]
Is email enabled in app?

**Comment by vshymanskyy** [comment]
Notification is removed

**Comment by doom369** [comment]
no emails for now

**Comment by vshymanskyy** [comment]
@blynkkk please comment, as we discussed this

**Comment by doom369** [comment]
@vshymanskyy no need. as ticket only for pushes. If emails not necessary Pavel will create one more ticket.

**Comment by doom369** [comment]
@vshymanskyy please close ticket if you removed notifications code.

**Comment by vshymanskyy** [comment]
Push notifications are removed, emails still there
