### ISSUE TITLE
demo app docs: add information / description why Auth Token is not required and how it works without it

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#209]
Describe the process on the steps where it's relevant.

It's the top asked question

**Comment by vshymanskyy** [comment]
There is a note like this already:
"Note that for BlynkProvisioning.begin(), you don’t need to specify Auth Token or WiFi credentials. That’s right! This information is provided dynamically during device configuration process."

Does it need to be more detailed, or put in another place?

**Comment by vshymanskyy** [comment]
@blynkkk ping

**Comment by doom369** [comment]
@vshymanskyy pls move to related readme.
