### ISSUE TITLE
myPlant : incorrect values

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#211]
Please make 3 IF statements to make the app more human

Soil:

- DRY
- WET
- MOIST

Light:
- LOW
- MED
- GOOD

https://github.com/blynkkk/blynk-android/issues/923

**Comment by vshymanskyy** [comment]
@doom369 , @blynkkk : Soil moisture, i would suggest to make it a gauge. The whole app looks meaningless otherwise (IMHO). I reported this 2 times already.
Let's decide it at last.

**Comment by doom369** [comment]
@vshymanskyy purpose of this demo just to show possibilities of Blynk. Text messages are very user-friendly and simple to understand in this "non-real world" demo. We already have gauges.

**Comment by doom369** [comment]
By the way. Change color of label would be cool too :).

**Comment by vshymanskyy** [comment]
@blynkkk - let's finalize the requirements

**Comment by doom369** [comment]
@vshymanskyy Ticket describes requirements... Please see description.
