### ISSUE TITLE
myPlant : reset instructions not clear

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#213]
From doc : 

> SparkFun Blynk Board: Press and hold the on board button “0” for 10 seconds.
> 
> After few seconds it will start fading white color, and then turn solid white. Then you can release the button to reset device configuration. After the board configuration is reset, you can configure it again from the myPlant App.

@vshymanskyy 

> Then you can release the button to reset device configuration.

how to reset device configuration?

**Comment by vshymanskyy** [comment]
You release the button to reset, actually

**Comment by doom369** [comment]
So probably next text is better

> Then you can release the button and device will be reset and act as AP again.
