### ISSUE TITLE
SetProperty doesn't work with BLE

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#217]
http://community.blynk.cc/t/error-processing-client-command-with-setproperty/8758

**Comment by vshymanskyy** [comment]
Hardware:
Nexus 6 with Android 7.0 installed
Sparkfun RedBoard (Uno clone)
Adafruit BlueFruit LE Shield
Big Easy Driver (stepper motor driver -- not used in this sketch, but is connected)
Blynk library v0.3.10

**Comment by vshymanskyy** [comment]
There is big chance this is actually Android bug.

**Comment by doom369** [comment]
Ok. I'll create there too.

**Comment by doom369** [comment]
android bug
