### ISSUE TITLE
Geo DNS issue fix

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#218]
It's time to fix geo dns issue. So as you proposed : 

1. Hardware sends `login token` command;
2. Server returns either OK in case this is correct server or same Login command with ip/host as message body;
3. In case server returned Login command you need to make login again to server from response;

Please don't forget to add additional logging.

**Comment by vshymanskyy** [comment]
why same Login command?
i think it should be a different command (REDIRECT)

**Comment by vshymanskyy** [comment]
this won't work on all hardware out-of the box

**Comment by doom369** [comment]
> this won't work on all hardware out-of the box

Why?

> i think it should be a different command (REDIRECT)

Ok.

**Comment by vshymanskyy** [comment]
1. I just checked - this will require big changes in several parts of the library.
2. It won't work with USB, for example - as gateway script is not aware of protocol API
3. Almost all hardware will have to be re-tested, so we expect some (maybe big) regressions.

**Comment by doom369** [comment]
Any other proposals?

**Comment by vshymanskyy** [comment]
Getting this command in older libraries should be just skipped - but i need to validate this.
Is there any auth token on QA server which is currently set up for redirection?

**Comment by doom369** [comment]
> Is there any auth token on QA server which is currently set up for redirection?

No. Will add today

**Comment by doom369** [comment]
> Getting this command in older libraries should be just skipped - but i need to validate this.

Good point.

**Comment by vshymanskyy** [comment]
1. We do changes, if they are needed.
2. No ideas about how to fix USB easily. there is an option of writing full gateway from scratch (but huge efforts)
3. We will test 3-4 most used platforms and then fix regression as reported.

**Comment by vshymanskyy** [comment]
Also about SSL - some libraries require hard-coded fingerprint or certificate. I hope they are the same on different servers?

**Comment by vshymanskyy** [comment]
BTW, do we have Authorized SSL cerificates for HW ports already? If not, maybe it is a good time to include

**Comment by doom369** [comment]
> I hope they are the same on different servers?

Yes.

> BTW, do we have Authorized SSL cerificates for HW ports already? If not, maybe it is a good time to include

Let's do it step by step. Not all in once.

**Comment by vshymanskyy** [comment]
There is one more problem: will it always be an IP address?
Problem is, some hardware is using different routines for connecting via IP or domain name.
In this case, if it differs from what was used by user, both routines would be built into project.

**Comment by doom369** [comment]
> There is one more problem: will it always be an IP address?

In nearest future - yes. However it may be changed in future. Just IPs for now are ok.

**Comment by doom369** [comment]
@vshymanskyy have you finished? I'll do deploy in few hours on QA.

**Comment by vshymanskyy** [comment]
Of course, not. As I said, there are lot's of changes, and I need to test
them. What is the number of new message?

**Comment by doom369** [comment]
`CONNECT_REDIRECT = 41;`

**Comment by doom369** [comment]
@vshymanskyy deployed. Let me know when I can test too. We need this feature ASAP.

**Comment by vshymanskyy** [comment]
I get Invalid auth token for 123

**Comment by doom369** [comment]
@vshymanskyy fixed. please check again.

**Comment by vshymanskyy** [comment]
@doom369, works.
please also send port to connect to, as: addr\0port

**Comment by vshymanskyy** [comment]
@doom369 ready to test

**Comment by doom369** [comment]
> please also send port to connect 

Do we need this? This feature only for Blynk Cloud and we do not plan to change ports.

**Comment by vshymanskyy** [comment]
1. Yes we need port - we're changing the whole endpoint.

**Comment by vshymanskyy** [comment]
2. Old Hardware versions expect OK to continue working. Server should send it?

**Comment by vshymanskyy** [comment]
Some Libraries may return ILLEGAL_COMMAND when get redirect - hope no problem for server.

**Comment by doom369** [comment]
> Old Hardware versions expect OK to continue working. Server should send it?

We have very small number of hardware that sends this info. I would say 10%.

**Comment by vshymanskyy** [comment]
This most probably is because of old libraries. We should not rely on info.
What I say - if you send redirect, you should also reply OK for login

**Comment by doom369** [comment]
I don't like this idea as it brings regressions.

Why can't you make just separate command before login command? So we have no problems with outdated libs?

**Comment by vshymanskyy** [comment]
Yes it is needed.
we are changing whole endpoint
