### ISSUE TITLE
Improve setProperty for color and add color for Widget classes

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#227]
Suggestions : http://community.blynk.cc/t/suggestion-for-making-the-color-property-easier-to-use/9331

Looks very nice.

**Comment by vshymanskyy** [comment]
@doom369 this has to be implemented on the server side.
Library already accepts numbers, strings, etc.

**Comment by doom369** [comment]
@vshymanskyy hm, you are right... I thought about overloaded methods.

**Comment by doom369** [comment]
@vshymanskyy by the way do we have `led1.color` ?

**Comment by vshymanskyy** [comment]
not currently - it needs some refactoring

**Comment by PascalWALLEM** [comment]
Hi,
FYI,
I've tried use widgetLed.setColor and the displayed color of led in Blynk (IOs) changed... but IOs app. crashed... It is reproductible...
Perhaps I did something wrong...

**Comment by doom369** [comment]
Hello. This is known issue for iOS. We will fix it soon.

**Comment by PascalWALLEM** [comment]
Hello,
Thanks for your quick response.
I will wait for application upgrade to use this new feature...
Thanks

**Comment by rgm3** [comment]
Hello -- I see that you added a setColor method to the base widget class, thank you.  Have you also added support for `Args...` such as a uint32_t and r, g, b values?

```
led1.setColor(0xFF0000);
led1.setColor(255, 0, 0);
```

These would really make many kinds of programs easier for both advanced users (who work with the packed values) and beginners (who think in RGB), as well as avoiding the need to figure out number-to-string conversion for creating the "#ff0000" string.
