### ISSUE TITLE
Certificate location for USB connection

### ISSUE THREAD

**Issue by WhizzCat** [blynkkk/blynk-library#228]
Blynk library version: [0.4.0]
IDE: [doesn't matter]
IDE version: [...]
Board type: [Wemos D1]
Additional modules: [...]

When you want to create a USB-serial connection using the Blynk-Serial example, the blynk-ser.sh script on Linux/MacOS cannot find the server and client certificates if there are spaces in the path. When removing the spaces it works fine (e.g. make a hard link in the blynk-ser.sh script to the certificate).

More info when starting script:

```
Resetting device /dev/cu.wchusbserialfd130...
./blynk-ser.sh: line 212: [: /Users/bastiaanvisee/Google: binary operator expected
Warning: /Users/bastiaanvisee/Google Drive/Arduino/libraries/Blynk/scripts/certs/server.crt not found. Skipping server verification (connection may be insecure)!
./blynk-ser.sh: line 219: [: /Users/bastiaanvisee/Google: binary operator expected
```

**Comment by vshymanskyy** [comment]
Thank you for this report, we will try to fix that!
