### ISSUE TITLE
RTC sketch doesn't work.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#230]
Blynk library version: [Last commit 304b86c ]
IDE: [Arduino]
IDE version: [1.6.12]
Board type: [Arduino Nano]
Additional modules: [No]

### Scenario, steps to reproduce
[Use default RTC sketch+modify to use COM port(Serial-USB)]

### Expected Result
[Update date and time in Value Display widgets]

### Actual Result
[Value Display don't show anything(empty)]

**Comment by vshymanskyy** [comment]
Should work now... can you check this?

**Comment by Refenz** [comment]
@vshymanskyy 
Still doesn't work

**Comment by vshymanskyy** [comment]
Can you post your debug serial output here?
Connect another USB-Serial adapter, and use SwSerial for BLYNK_PRINT.
Does your sketch work except the RTC?

**Comment by Refenz** [comment]
@vshymanskyy 
In Debug Serial time and date present. (log have ugly format, so not post here)
Have strange message:                                                                                       `dw.3.1..^..dw.2.1.._..aw.16.217Current time: 0:0:35 1 1 1970.......vw.1.0:0:35.....vw.2.1 1 1970`
Use RTC sketch. Don't add rtc widget:
1) Button work fine. 
2)Value Display update value from pin(like HIGH or random analog signal).
After add rtc widget:
1)Button work.
2)Value display stops update any value. (Remove rtc widget doesn't help)

**Comment by vshymanskyy** [comment]
I think the problem is following: you use Serial for Blynk communication, but RTC sketch also prints to Serial... Just remove the lines:
```
  Serial.print("Current time: ");
  Serial.print(currentTime);
  Serial.print(" ");
  Serial.print(currentDate);
  Serial.println();
```

**Comment by Refenz** [comment]
@vshymanskyy 
Yes, it's helped
