### ISSUE TITLE
Additional property for json files

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#233]
For multi devices feature we need one more property that will define connection type for specific board.

For example, when user uses ESP8266 we don't need to show "connection type" field as we know it is WI-FI. So we need something like `connectionType` property for every board.

Examples : 

`connectionType : "ANY"` //for arduino uno

`connectionType : "WI_FI"` //for ESP8266

```
    ETHERNET,
    WI_FI,
    USB,
    BLUETOOTH,
    BLE,
    GSM

```

**Comment by doom369** [comment]
> connectionType : "ANY" //for arduino uno

Or could be just null/missing.

**Comment by vshymanskyy** [comment]
Connection type should be always shown. The fact that ESP has WiFi does not restict to wifi usage

**Comment by doom369** [comment]
After discussion with @blynkkk - yes, ESP may be used in any way. However in majority of cases it would be Wi-Fi. So from point of view of UX it is better to provide predefined connection types for well-known boards based on statistics.

**Comment by vshymanskyy** [comment]
Replaced by #249
