### ISSUE TITLE
Add clear command for Map

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#238]

**Comment by vshymanskyy** [comment]
should it be ```Blynk.virtualWrite(vPin, index, "clear");``` or
```Blynk.virtualWrite(vPin, "clear");``` ?

**Comment by doom369** [comment]
`Blynk.virtualWrite(vPin, "clear");`

**Comment by doom369** [comment]
@vshymanskyy `clr` not `Clear`
