### ISSUE TITLE
Adafruit_Feather_32u4_BLE.ino does not work

### ISSUE THREAD

**Issue by arms22** [blynkkk/blynk-library#242]
Blynk library version: 0.4.1
IDE: Arduino IDE
IDE version: 1.6.13
Board type: Adafruit Feather M0 Bluefruit LE
Additional modules: Adafruit BluefruitLE nRF51 v1.9.4

### Scenario, steps to reproduce
Write Adafruit_Feather_32u4_BLE.ino on board and connect from Blynk app

### Expected Result
Be able to connect to Blynk app

### Actual Result
Can not connect to Blynk app

Since the loop continues until it can connect to the server with the begin function, processing after the begin function is not executed.

    Blynk.begin(auth,ble);
    ble.begin(BLUEFRUIT_VERBOSE_MODE);
    ble.factoryReset(); // Optional
    ble.setMode(BLUEFRUIT_MODE_DATA);

I modified it as follows and it worked.

    ble.begin(BLUEFRUIT_VERBOSE_MODE);
    ble.factoryReset(); // Optional
    ble.setMode(BLUEFRUIT_MODE_DATA);
    Blynk.begin(auth,ble);

**Comment by vshymanskyy** [comment]
Thank you. I updated the example.
