### ISSUE TITLE
Add latest Blynk library to codebender

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#25]

**Comment by blynkkk** [comment]
@vshymanskyy any update here?

**Comment by blynkkk** [comment]
Please create a request, mentioning what exactly should be added here:
http://feedback.codebender.cc/

**Comment by vshymanskyy** [comment]
I don't think it's a good idea to release a codebender version right now.
We need to release new version of library first, and then give it a weak or two to get feedback.

**Comment by blynkkk** [comment]
they manually test all the libraries, so it's ok :)

**Comment by vshymanskyy** [comment]
We moved to new library format (1.5.x) so adding to codebender is quite impossible at this point.
We can release the latest 1.0.x version to codebender - but this looks very low priority ATM.
closing
