### ISSUE TITLE
Include scripts in PlatformIO

### ISSUE THREAD

**Issue by krasilich** [blynkkk/blynk-library#252]
Blynk library version: 0.4.3
IDE: Platform.IO
IDE version: 1.7.1
Board type: *

I want to use blynk-ser.sh but Blynk scripts folder is excluded in PlatformIO library manifest.
Is there any reason you are not including scripts to PlatformIO lib?

**Comment by vshymanskyy** [comment]
@ivankravets ?

**Comment by vshymanskyy** [comment]
so is this ok? i will add to original library then

**Comment by ivankravets** [comment]
@vshymanskyy Please sorry, I forgot to pull request. See https://github.com/blynkkk/blynk-library/pull/253
