### ISSUE TITLE
Example for non blocking flow

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#254]
Users often requesting example of non-blocking flow. Something like : 

```
if (NO_INTERNET) {
  //do regular job
} else {
  Blynk.run();
}
```

http://community.blynk.cc/t/how-to-run-blynk-run-only-when-wifi-connection-is-established/6492
http://community.blynk.cc/t/code-isnt-working-without-connected-blynk/5624/16
http://community.blynk.cc/t/blynk-library-for-arduino-v0-4-1-is-released/9882/47

**Comment by vshymanskyy** [comment]
¿¿¿

**Comment by doom369** [comment]
@vshymanskyy see attached links.
