### ISSUE TITLE
give me video link to add libarary to arduino ide . im using arduino 1.6.5r and blynk is 0.4.3

### ISSUE THREAD

**Issue by ManikandanET** [blynkkk/blynk-library#260]
Blynk library version: [...]
IDE: [Arduino/Energia/MBED Compiler/Platform.IO/Eclipse ...]
IDE version: [...]
Board type: [...]
Additional modules: [...]

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by vshymanskyy** [comment]
Please find the answer on our community forum
