### ISSUE TITLE
Reading widgets force ESP to drop connection

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#261]
We have a very old issue with ESP and reading widgets when bunch of reading widgets forces ESP to drop connection. 

Right now we are moving "reading" logic to server so in nearest future user doesn't require app to be opened and running. I think for that time it would be nice to have this issue to be fixed.

**Comment by vshymanskyy** [comment]
Tested with 10 widgets, 1 second interval and working as expected.
We do not support this feature for more than 10 widgets on same HW device.

**Comment by doom369** [comment]
@vshymanskyy please show sketch you was testing with.

**Comment by vshymanskyy** [comment]
just regular VR test:
```
#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

char auth[] = "YourAuthToken";

char ssid[] = "YourNetworkName";
char pass[] = "YourPassword";

#define VR(pin) BLYNK_READ(pin){Blynk.virtualWrite(pin, millis() / 1000);}

VR(V1)
VR(V2)
VR(V3)
VR(V4)
VR(V5)
VR(V6)
VR(V7)
VR(V8)
VR(V9)
VR(V10)

void setup()
{
  Serial.begin(9600);
  Blynk.begin(auth, ssid, pass);
}

void loop()
{
  Blynk.run();
}

```

**Comment by eepetrash** [comment]
I was experiencing such connection drops on NodeMCU V3 ESP8266. 
Project had a slider (with `Send Values On Release Only` == OFF), continuously changing its value triggered changing the Gauge value and its color:
```cpp
BLYNK_WRITE(SLIDER)
{
  double pinValue = param.asDouble();

  Serial.print("Slider value is: ");
  Serial.println(pinValue);

  Blynk.virtualWrite(GAUGE, pinValue);

  if (pinValue < 1023.0 * (1.0 / 4.0)) {
    Blynk.setProperty(GAUGE, "color", BLYNK_BLUE);
  }
  else if (pinValue < 1023.0 * (2.0 / 4.0)) {
    Blynk.setProperty(GAUGE, "color", BLYNK_GREEN);
  }
  else if (pinValue < 1023.0 * (3.0 / 4.0)) {
    Blynk.setProperty(GAUGE, "color", BLYNK_YELLOW);
  }
  else {
    Blynk.setProperty(GAUGE, "color", BLYNK_RED);
  }

  analogWrite(LED_PIN, pinValue);
}
```

If we change Slider's `Send Values On Release Only` == ON connections keeps fine.

**Comment by vshymanskyy** [comment]
Then it is a different bug.

**Comment by doom369** [comment]
@vshymanskyy ok. rename this one :).
