### ISSUE TITLE
ESP8266_Shield doesn't compile for Arduino 101

### ISSUE THREAD

**Issue by d1runberg** [blynkkk/blynk-library#263]
Hello. I would like to use my SparkFun ESP8266 Wifi Shield with my Arduino 101. The shield works with the 101 as per sparkfuns docs. Is there a reason that the blynk library doesn't compile for it. The 101 works with software serial, so theoretically you should be able to use the 101 with this shield and blynk....correct?

Blynk library version: 0.4.3
IDE: Arduino
IDE version: 1.6.10
Board type: Arduino 101
Additional modules: SparkFun ESP8266 Shield

### Scenario, steps to reproduce
Arduino 101 with a SparkFun ESP8266 Shield set to SW Serial on pins 8 and 9. Try to compile ESP8266_Shield example to start using with Blynk
 
### Expected Result
control pin 13 with a button in blynk

### Actual Result

ERROR: 

Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -hardware "/Users/Derek/Library/Arduino15/packages" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/Derek/Library/Arduino15/packages" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/Derek/Documents/Arduino/libraries" -fqbn=Intel:arc32:arduino_101 -vid-pid=0X8087_0X0AB6 -ide-version=10610 -build-path "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/build23f7d518531de06255349e123ba9976c.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/arduino_modified_sketch_73320/ESP8266_Shield.ino"
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -hardware "/Users/Derek/Library/Arduino15/packages" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/Derek/Library/Arduino15/packages" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/Derek/Documents/Arduino/libraries" -fqbn=Intel:arc32:arduino_101 -vid-pid=0X8087_0X0AB6 -ide-version=10610 -build-path "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/build23f7d518531de06255349e123ba9976c.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/arduino_modified_sketch_73320/ESP8266_Shield.ino"
Using board 'arduino_101' from platform in folder: /Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6
Using core 'arduino' from platform in folder: /Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6
Detecting libraries used...
"/Users/Derek/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-g++" -c -mcpu=quarkse_em -mlittle-endian -g -Os -Wall -fno-reorder-functions -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -fno-defer-pop -Wno-unused-but-set-variable -Wno-main -ffreestanding -fno-stack-protector -mno-sdata -ffunction-sections -fdata-sections -fsigned-char  -fno-rtti -fno-exceptions -D__ARDUINO_ARC__ -std=c++11 -w -x c++ -E -CC -DF_CPU=32000000L -DARDUINO=10610 -DARDUINO_ARC32_TOOLS -DARDUINO_ARCH_ARC32 -D__CPU_ARC__ -DCLOCK_SPEED=32 -DCONFIG_SOC_GPIO_32 -DCONFIG_SOC_GPIO_AON -DINFRA_MULTI_CPU_SUPPORT -DCFW_MULTI_CPU_SUPPORT -DHAS_SHARED_MEM "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/common" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/drivers" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/bootcode" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/framework/include"  "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/cores/arduino" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/variants/arduino_101" "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/build23f7d518531de06255349e123ba9976c.tmp/sketch/ESP8266_Shield.ino.cpp" -o "/dev/null"
"/Users/Derek/Library/Arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1/bin/arc-elf32-g++" -c -mcpu=quarkse_em -mlittle-endian -g -Os -Wall -fno-reorder-functions -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -fno-defer-pop -Wno-unused-but-set-variable -Wno-main -ffreestanding -fno-stack-protector -mno-sdata -ffunction-sections -fdata-sections -fsigned-char  -fno-rtti -fno-exceptions -D__ARDUINO_ARC__ -std=c++11 -w -x c++ -E -CC -DF_CPU=32000000L -DARDUINO=10610 -DARDUINO_ARC32_TOOLS -DARDUINO_ARCH_ARC32 -D__CPU_ARC__ -DCLOCK_SPEED=32 -DCONFIG_SOC_GPIO_32 -DCONFIG_SOC_GPIO_AON -DINFRA_MULTI_CPU_SUPPORT -DCFW_MULTI_CPU_SUPPORT -DHAS_SHARED_MEM "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/common" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/drivers" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/bootcode" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/system/libarc32_arduino101/framework/include"  "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/cores/arduino" "-I/Users/Derek/Library/Arduino15/packages/Intel/hardware/arc32/1.0.6/variants/arduino_101" "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/build23f7d518531de06255349e123ba9976c.tmp/sketch/ESP8266_Shield.ino.cpp" -o "/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/build23f7d518531de06255349e123ba9976c.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
/var/folders/gv/l476855s53z4hyy9y3wtbfv00000gn/T/arduino_modified_sketch_73320/ESP8266_Shield.ino:30:25: fatal error: ESP8266_Lib.h: No such file or directory
 #include <ESP8266_Lib.h>
                         ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino 101.

**Comment by vshymanskyy** [comment]
Please install all of the libraries, as described in the release notes https://github.com/blynkkk/blynk-library/releases/latest
