### ISSUE TITLE
Blynk.disconnect() and then Blynk.connect() fails to reconnect (with possible solution)

### ISSUE THREAD

**Issue by lorneb** [blynkkk/blynk-library#264]
### Scenario, steps to reproduce
ESP8266 NodeMCU v1.
Blynk connection is up and running working well
I need to shut down the connection to blynk for a little pause so I use Blynk.disconnect();
Then to reconnect I use Blynk.connect(3333)
I then test the status with Blynk.connected() it is false,  even if i put the connect in a while loop it never reconnects.

### Expected Result
I would expect it to reconnect and behave as normal after that

### Actual Result
it never reconnects.

Blynk\src\Blynk\BlynkProtocol.h Line ~50
``` C++
conn.disconnect();
//I believe should be, i have changed to this and it is working as expected for me
conn.connect();

**Comment by vshymanskyy** [comment]
Thx.
I will check this.. ```conn.disconnect();``` is a correct action here.

**Comment by apokrovskyy** [comment]
Can you please send relative part of code or entire sketch if possible?

**Comment by beachmiles** [comment]
Blynk.connected()  is also returning false for me a lot more often on my node MCU. Whether or not I take the check out in the code I still see lots of disconnections in the app (1 disconnection every 10 seconds or so). Seems to be happening on the newer libraries cause an older library ~ 5 months ago has way more Blynk.write calls and never seems to disconnect. 

Ita nice to have the timeout in case WiFi is really down but you want the code to not get locked up on the blynk.connect

**Comment by apokrovskyy** [comment]
Try to use example sketch for your device. Try to search for your problem on [blynk forum](http://community.blynk.cc/). Add relative code to your problem so it can be solved properly.

**Comment by vshymanskyy** [comment]
The bug is not confirmed. Please take a look at possibly relevant example: https://github.com/blynkkk/blynk-library/blob/master/examples/More/HandleDisconnect/HandleDisconnect.ino
