### ISSUE TITLE
problem linking two virtual pins together

### ISSUE THREAD

**Issue by weixuan109** [blynkkk/blynk-library#268]
Hi, 

I am currently trying to do a temperature logger with Blynk and what i am trying to do is to allow temperature to be displayed onto the table. I have a menu widget that allows me to choose the interval of the logging and i also have a button which i would like to switch the logging on and off.

However, I could not figure out how to make use of the button and the menu together to operate the logging on to the table. Because so far what i have done is that whenever I choose the interval from the menu, my timer automatically starts logging on to the table. But instead i want it to start logging only when i press the on button. I don't know whether i am on the right approach but it would be great if someone step out to help.

Does anyone have any idea how to solve the problem? Thank you.
```
#define BLYNK_PRINT Serial    // Comment this out to disable prints and save space
#include <Bridge.h>
#include <SPI.h>
#include <BlynkSimpleYun.h>
#include <SimpleTimer.h>
#include "DHT.h"
#define DHTPIN A0
#define DHTTYPE DHT11   // DHT 11 
char auth[] = "";
const int led = 13;
SimpleTimer timer;
int rowIndex = 0; 
DHT dht(DHTPIN, DHTTYPE);
void sendEvent()
{
     float temp = dht.readTemperature();
  // adding 1 row to table every second
  Blynk.virtualWrite(V1, "add", rowIndex, "Temperature", temp); //virtual pin 1 allocated to table

  //highlighting latest added row in table
  Blynk.virtualWrite(V1, "pick", rowIndex);

  rowIndex++;
  Serial.print("temperature is: ");
  Serial.println(temp);
}
BLYNK_WRITE(V2) // virtual pin 2 allocated to menu.
{
    switch(param.asInt())
    {
      case 2:
      {
      timer.setInterval(1000L, sendEvent);
      }
      break;
      case 3:
      {
      timer.setInterval(5000L, sendEvent);
      }
      break;
      case 4:
      {
       timer.setInterval(5000L, sendEvent);
      }
      break;
      default:;
    }
      
}
BLYNK_WRITE(V3) // virtual pin 3 allocated to button
{
if (param.asInt())
{
  BLYNK_WRITE(V2); // suppose to start logging upon press of button.
}
else
{
  //suppose to turn off the logging
}
}
void setup()
{
  pinMode(led, OUTPUT);
  Serial.begin(9600);
  Blynk.begin(auth);
  Blynk.setProperty(led, "ON", HIGH);
  Blynk.setProperty(led, "OFF", LOW);
  Blynk.virtualWrite(V1, "clr");
  pinMode(V3, INPUT);
  
  dht.begin();
}

void loop()
{
  timer.run();
  Blynk.run();  
}
```

**Comment by weixuan109** [comment]
i updated the code but its still not working. This time when i press the button nothing came out.

#define BLYNK_PRINT Serial  // Comment this out to disable prints and save space
#include <Bridge.h>
#include <SPI.h>
#include <BlynkSimpleYun.h>
#include <SimpleTimer.h>
#include "DHT.h"
#define DHTPIN A0
#define DHTTYPE DHT11   // DHT 11 
char auth[] = "0a9505abab10463bb6146362b09c84c3";
const int led = 13;
SimpleTimer timer;
int rowIndex = 0; 
int buttonOnOff;
DHT dht(DHTPIN, DHTTYPE);

void sendEvent()
{
     float temp = dht.readTemperature();
  // adding 1 row to table every second
  Blynk.virtualWrite(V1, "add", rowIndex, "Temperature", temp);

  //highlighting latest added row in table
  Blynk.virtualWrite(V1, "pick", rowIndex);

  rowIndex++;
  Serial.print("temperature is: ");
  Serial.println(temp);
}
BLYNK_WRITE(V3)
{
  buttonOnOff = param.asInt();
}
BLYNK_WRITE(V2)
{
  
    switch(param.asInt())
    {
      case 2:
        if(buttonOnOff == 1)
        {
      timer.setInterval(1000L, sendEvent);
      }
      break;
      case 3:
      if(buttonOnOff == 1)
      {
      timer.setInterval(5000L, sendEvent);
      }
      break;
      case 4:
      {
        if(buttonOnOff == 1)
       timer.setInterval(10000L, sendEvent);
      }
      break;
      default:;
    }
      
}

void setup()
{
  pinMode(led, OUTPUT);
  Serial.begin(9600);
  Blynk.begin(auth);
  Blynk.setProperty(led, "ON", HIGH);
  Blynk.setProperty(led, "OFF", LOW);
  Blynk.virtualWrite(V1, "clr");
  pinMode(V3, INPUT);
  
  dht.begin();
}

void loop()
{
  timer.run();
  Blynk.run();  
}

**Comment by vshymanskyy** [comment]
Please post such questions to our community forum http://community.blynk.cc/
