### ISSUE TITLE
ESP8266-01+Arduino UNO+blynkk 

### ISSUE THREAD

**Issue by dhavalb96** [blynkkk/blynk-library#269]
hey guys,
please help me i am stuck with the esp8266 interfacing with arduino uno. Below is the screenshot 
![untitled12](https://cloud.githubusercontent.com/assets/25839988/23057996/cd5d77da-f518-11e6-9b3e-ae5590a568bc.png)

Blue Led is constantly flickering and the RED led is stable.
my code is given below:

#define BLYNK_PRINT Serial    // Comment this out to disable prints and save space
#include <ESP8266_Lib.h>
#include <BlynkSimpleShieldEsp8266.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "1c5e8914c01f41549e9c01e1a9dc8aa5";

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "Dhaval";
char pass[] = "123456789";

// Hardware Serial on Mega, Leonardo, Micro...
//#define EspSerial Serial1

// or Software Serial on Uno, Nano...
#include <SoftwareSerial.h>
SoftwareSerial EspSerial(5, 6); // RX, TX

// Your ESP8266 baud rate:
#define ESP8266_BAUD 115200

ESP8266 wifi(&EspSerial);

void setup()
{
  // Set console baud rate
  Serial.begin(9600);
  delay(10);
  // Set ESP8266 baud rate
    EspSerial.begin(ESP8266_BAUD);
 
  Blynk.begin(auth,wifi,ssid,pass);
}

void loop()
{
  Blynk.run();
}

please please help me.....thank you in advance

**Comment by ArduProg** [comment]
Are you powering it from 3.3V pin on Arduino? If so, that won't work, because it isn't capable of supplying enough current. Also check that u r pulling CH_PD pin HIGH and the arduino's RX is connected to TX on esp8266 and arduino's TX to esp'sRX

**Comment by dhavalb96** [comment]
@ArduProg Should i supply 3.3V using LM1117 voltage regulator?????? and CH_PD is high and RX to TX Arduino , TX to RX Arduino is done correctly, What about the  GPIO0, GPIO2 and RST??

**Comment by ArduProg** [comment]
yes you should. only CH_PD needs to be high. you can also try to flash empty sketch to arduino, connect RX and TX and use duino as Serial to USB. Set baud to 115200 line ending to both CR & NL and try to send AT. response should be OK. If not, try to swap RX&TX in first place and try other bauds (i.e. 9600 57600...) in 2nd place.

**Comment by dhavalb96** [comment]
@ArduProg Failed to disable echo!! :(:(

**Comment by ArduProg** [comment]
Have you tried swapping the RX and TX (RX to RX, TX to TX? pins 0 and 1 on arduino uno) u can use it as some kind of FTDI chip.

**Comment by dhavalb96** [comment]
@ArduProg  tried buddy still that "Failed to disable echo" error is coming. I tried to upload program on arduino 0,1 pins but its not getting uploaded!! sometimes the error comes "Not in Sync" and sometimes "Programmer not responding", "Can't set mask", "Cannot open port"

**Comment by ArduProg** [comment]
no, no, you need to flash blank code to it (File-New). firstly you should disconnect esps Serial from arduino. Then upload blank code, then connect esps serial to arduinos RX/TX pins and open serial monitor.

**Comment by oz1411** [comment]
hi I'm having the same issue with the ESP8266 12E 
I'm not even sure how to wire it let alone worry about code. 

I have followed the instructions of 3 other forums and nothing seems to work. 

I have an uno and want to use the ESP8266 simply to get wifi so I can trigger io pins on Arduino but I cant get it to communicate. I would massively appreciate if anyone can help me solder this and get it to do something when I type AT

**Comment by vshymanskyy** [comment]
Guys, there are a lot of discussions on this topic on http://community.blynk.cc/ please search the forum.
Also, check wiki article here: https://github.com/blynkkk/blynk-library/wiki/ESP8266-with-AT-firmware
