### ISSUE TITLE
Provide better starting guides and docs for PI and CHIP

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#270]
See discussion here 
http://community.blynk.cc/t/getting-blynk-client-to-work-on-c-h-i-p-hardware/11816/3
and here 
http://community.blynk.cc/t/using-c-on-a-raspberry-pi-with-blynk/11864

**Comment by vshymanskyy** [comment]
http://help.blynk.cc/hardware-and-libraries/node-js/how-to-install-nodejs-library-on-linux

**Comment by doom369** [comment]
@vshymanskyy did you update doc.blynk.cc?
