### ISSUE TITLE
Bluetooth HC05 does not connect

### ISSUE THREAD

**Issue by Vankxr** [blynkkk/blynk-library#274]
Blynk library version: 0.4.4
IDE: Arduino
IDE version: 1.8.1
Board type: Mega 2560
Additional modules:

### Scenario, steps to reproduce
Example for HC05 does not connect. Simply compile and upload it, it does not connect, maybe I am missing something, I am using Serial1 as the bluetooth serial, and Serial as the print serial. in the print serial I only get Connecting... messages repeatedly even after connecting on the app. The app, however, is able to send data to the arduino and the arduino is able to receive, but as it is blocked by the constant connection attempts (failed), it does not execute my code inside loop().

### Expected Result
Expected to get Connecting... > Connected

### Actual Result
Getting Connecting... with no success

**Comment by vshymanskyy** [comment]
please post such questions to the community forum.

**Comment by vshymanskyy** [comment]
also, take a look at this: https://github.com/blynkkk/blynk-library/wiki/Bluetooth
