### ISSUE TITLE
Please keep the same release description as I updated it

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#280]
https://github.com/blynkkk/blynk-library/releases/tag/v0.4.4

People are constantly asking for instructions on how to install libraries. They should come first and always be step-by-step

**Comment by vshymanskyy** [comment]
Probably one reason for this is a completely wrong instruction on the site:
```
In case you forgot how to install Arduino libraries – check here. Follow "Importing a .zip Library" guide.
```
it should refer to https://www.arduino.cc/en/guide/libraries#toc5 and **Manual installation** section
