### ISSUE TITLE
Simple Timer example uses integer

### ISSUE THREAD

**Issue by erolcanulutas** [blynkkk/blynk-library#281]
Simple Timer example uses integer so it doesn't show above 32768. 09:06 is 32760 so that is the last one it shows correctly. If you change it, it would be good for who is not very similar with coding.

Thank you.

BLYNK_WRITE(V1) {
  long startTimeInSecs = param[0].asLong();
  Serial.println(startTimeInSecs);
  Serial.println();
}

**Comment by vshymanskyy** [comment]
Fixed. thanks!
