### ISSUE TITLE
Create First Example for New Blynk Users

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#282]
The major idea of the first example is Establishing Connection

First Example (we can call it Hello Blynk) should not rely on other hardware (LEDs, resistors, and so on)

User will add Terminal Widget and set it to pin V0
Press Play

In the terminal there will be:

```
     ___  __          __
    / _ )/ /_ _____  / /__
   / _  / / // / _ \/  '_/
  /____/_/\_, /_//_/_/\_\
         /___/    v0.4.4

bla bla bla Connected

Blynk is saying Hello to you!
Your hardware is online for:
1
2
3
4 
5
...
```

This will be included in all documentation I'm currently working on.

It can be easily reused for Label, Graph, Gauge and other widgets. We are also teaching BlynkTimer

**Comment by Fettkeewl** [comment]
Shhh, SimpleTimer is now depricated, use BlynkTimer 😜😜😜
