### ISSUE TITLE
Blynk.tweet() seem doesn't work.

### ISSUE THREAD

**Issue by benjenq** [blynkkk/blynk-library#284]
Blynk library version: 0.4.6
IDE: Arduino IDE
IDE version: 1.8.1
Board type: ESP8266 / ESP-01
Additional modules: None.

### Scenario, steps to reproduce
I've add a Twitter widget in project of Blynk app, and linked to my Twitter account in iPhone settings successfully.

Code:
```C++
String postcontent = "esp8266 say hello world! #iot #blynk";
Blynk.tweet(postcontent);
Blynk.notify("You posted a twitter:" + postcontent);
```

### Expected Result
Post a message "esp8266 say hello world! #iot #blynk" to Twitter within my Twitter account, and got a notification on iPhone "You posted a twitter: esp8266 say hello world! #iot #blynk"

### Actual Result
Notification works on my iPhone, but twitter message no show on my Twitter account. 
I've test my Twitter account and post message via twitter iOS app / website and it works.

Any idea?

**Comment by doom369** [comment]
@benjenq please try to add some random number to your tweet message. Does that help?

**Comment by benjenq** [comment]
@doom369 

Still the same result. 

```C++
String postcontent = "esp8266 say hello world! #iot #blynk" + String(millis(),DEC);
Blynk.tweet(postcontent);
Blynk.notify("You posted a twitter:" + postcontent);
```
Notification show "You posted a twitter:esp8266 say hello world! #iot #blynkXXXXX", but twitter not.

**Comment by doom369** [comment]
Please send me your login email to dmitriy@blynk.cc

**Comment by benjenq** [comment]
@doom369
Has sent to you <ben***@ms24****>.  please check the mail box, thanks!

**Comment by doom369** [comment]
I see authentication failures for your acc. Seems like you are not connected. Could you please post screenshot of twitter edit settings?

**Comment by benjenq** [comment]
@doom369
iPhone screenshot:
http://imgur.com/S5oykb2

The twitter.com/settings/applications
http://imgur.com/ESINrOu

**Comment by benjenq** [comment]
iPhone Setting Screenshot
http://imgur.com/8mr9EJK

**Comment by doom369** [comment]
Is that latest Blynk App?

**Comment by benjenq** [comment]
Just download Blynk iOS App yesterday and play one day.
Ver 2.8.6, Feb 17,2017.
I think it's the latest version.

**Comment by doom369** [comment]
Ok. Thanks. We will investigate.

**Comment by doom369** [comment]
@benjenq issue is fixed. It is iOS app issue. Will be released in 2 weeks. Thanks for reporting and sorry fro inconveniences.
