### ISSUE TITLE
Check Teensy board

### ISSUE THREAD

**Issue by eepetrash** [blynkkk/blynk-library#287]
Board: Teensy 3.2
Please check why pins D15 through D19 are not available for dr/dw.

Also, are there plans to support Teensy 3.5 / 3.6?

**Comment by doom369** [comment]
@vshymanskyy Why is that low priority? Please fix it.

**Comment by vshymanskyy** [comment]
Why is it not a low priority? ))

**Comment by vshymanskyy** [comment]
Fixed.
