### ISSUE TITLE
Add SimpleTimer to Linux/Particle

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#288]
Need to investigate if it can be done

**Comment by vshymanskyy** [comment]
Need to test on Linux, Particle and fix in all examples

**Comment by vshymanskyy** [comment]
Linux verified.

**Comment by pieman64** [comment]
@vshymanskyy so it will work on a Pi now, right?

**Comment by vshymanskyy** [comment]
Yes, it should work, at least for intervals > 10 ms.
Usually, you'd set much bigger intervals anyway...

**Comment by pieman64** [comment]
> 10ms is fine, thanks.

**Comment by vshymanskyy** [comment]
Particle verified
