### ISSUE TITLE
BLYNK_PRINT Serial doesn’t print any more

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#290]
http://community.blynk.cc/t/my-blynk-print-serial-doesnt-print-any-more/12588

**Comment by vshymanskyy** [comment]
Not reproduced

**Comment by doom369** [comment]
@vshymanskyy did you check with local server? Seems likes it is reproducible only with local server.

**Comment by vshymanskyy** [comment]
Not reproducible with local server, the original poster also resolved his problems
