### ISSUE TITLE
notifications with bluetooth on iOS!!

### ISSUE THREAD

**Issue by jebay1** [blynkkk/blynk-library#291]
any idea when it will be working?  do you have a beta?
thanks

Blynk library version: [...]
IDE: [Arduino/Energia/MBED Compiler/Platform.IO/Eclipse ...]
IDE version: [...]
Board type: [...]
Additional modules: [...]

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by doom369** [comment]
It is already in todo list. No estimations so.
