### ISSUE TITLE
Add example of LM35 sensor

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#295]
Here is ready example http://community.blynk.cc/t/blynk-simple-temperature-sensor-lm35/1807

**Comment by vshymanskyy** [comment]
Such example won't work on Raspberry Pi, etc.

**Comment by doom369** [comment]
But we have similar for DHT

**Comment by vshymanskyy** [comment]
So it isn't working as well ;)))

**Comment by doom369** [comment]
However, this examples are very cool thing. You just do copy/paste them and have working setup. That's really simplify things.

**Comment by vshymanskyy** [comment]
Yeagh, OK if we положим болт or RPi for now ;)

**Comment by doom369** [comment]
That's fine.
