### ISSUE TITLE
email attachment

### ISSUE THREAD

**Issue by MichelRichir** [blynkkk/blynk-library#298]
It would be nice to be able to send file(s) stored on an SD card as an email attachment.
(I use files on the SD for data logging...)

**Comment by vshymanskyy** [comment]
Email attachments are not supported, sorry

**Comment by doom369** [comment]
This is feature request.

**Comment by vshymanskyy** [comment]
It's mainly server side, so reopen on server if you want to implement it ;)

**Comment by vshymanskyy** [comment]
Also, we do not support sending Files bigger than SEND_MAX_BYTES. Like several KB or so - this is impractical. Closing for now.
