### ISSUE TITLE
toggle/write button state from library

### ISSUE THREAD

**Issue by tzapu** [blynkkk/blynk-library#30]
like it says, it would be very useful to be able to upload button states in the app from the library end

https://github.com/tzapu/node-red-contrib-blynk/issues/4

**Comment by Toshibass** [comment]
+1 ..  I can toggle the state of a LED from the library but I desperately need to be able to toggle a button

**Comment by vshymanskyy** [comment]
Please post this as an idea to our forum.. this is not related to the library itself.
thanks for understanding...
