### ISSUE TITLE
Widget send value block mode

### ISSUE THREAD

**Issue by Fettkeewl** [blynkkk/blynk-library#301]
I hope I put this in right place. 

In order to prevent flooding server into device disconnects. I think there should be a mode to set for all widgets that require the app to get feedback from hardware/server that the value sent is received and processed. BEFORE allowing the widget to be changed.

**Comment by Fettkeewl** [comment]
This thread is a case in point 
http://community.blynk.cc/t/disconnected-after-quick-rapidly-repetitive-press-of-button/12947/9

**Comment by vshymanskyy** [comment]
Sorry this is not considered currently for implementation... I put wontfix tag so we might return to this later.
