### ISSUE TITLE
If use Blynk.syncAll(), then Value Display show 1023 all the time after recconect.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#306]
Blynk library version: 0.4.6
IDE: Arduino
IDE version: 1.6.12
Board type: Arduino Nano
Additional modules: 

### Scenario, steps to reproduce
Use sketch with "Blynk.syncAll()"
1)Open Blynk app(your project should use Value Display on the Analog pin)
2)Start project
3)Connect board to the internet
4)Value Display update value every second between 200-800
5)Disconnect board
6)Connect board
7)Value Display show 1023 all the time
P.S. Perhaps this is how the library works

### Expected Result
Value Display still update value

### Actual Result
Value Display still show 1023 all the time. If connect Analog pin to the ground, then Value Display show "0".

**Comment by vshymanskyy** [comment]
Are you sure you understand completely what Blynk.syncAll() should do?

**Comment by Gun-neR** [comment]
Renfenz.  You are describing a floating pin on the Analog side... this is normal and the reason for a three way sensor connection:  One pin on sensor to GND; One to Vcc; And one to the Analog pin, supplying a voltage between GND and Vcc (0-1023 on analog pin reading).  Once the Blynk Library is loaded, it will make internal changes like pinmode() to various pins as determined by Widgets using direct pin assignment in the App...  But that has nothing to do with Virtual pins and their supported commands like Blynk.syncAll.

**Comment by vshymanskyy** [comment]
Everything works as expected.
