### ISSUE TITLE
Add ESP-Touch Smart Config Protocol on SmartPhone App

### ISSUE THREAD

**Issue by omersiar** [blynkkk/blynk-library#309]
When using an ESP Standalone module we can use ESP8266_Standalone_Smartconfig.ino example, but it's not clear how to use it. Give user enough information on the example header.

And on SmartPhone Blynk App if user choose one of ESP board let them use ESP-Touch protocol in order to benefit from ease of use instead of downloading another application from the app store. Implementation won't be hard since open source code is available under MIT or similar license.

Resources:

https://espressif.com/en/products/software/esp-touch/overview
https://github.com/EspressifApp/EsptouchForAndroid
https://github.com/EspressifApp/EsptouchForIOS

**Comment by vshymanskyy** [comment]
Blynk provides full-fledged, unified WiFi provisioning process, which is available for commercial use only. See demo here: https://play.google.com/store/apps/details?id=cc.blynk.appexport.demo&hl=en
