### ISSUE TITLE
"ESP8266_DirectConnect.ino" not working

### ISSUE THREAD

**Issue by markusgritsch** [blynkkk/blynk-library#31]
Hi,

first of all I want to say thank you for Blynk. You are doing an excellent job with it!

I would like to get the "ESP8266_DirectConnect.ino" example running. If I understand it correctly, it would allow directly connect the iPhone app with the ESP8266.

Compiling and uploading the firmware works fine, and I can connect to the "Blynk-AP" with my iPhone. However, when I manually point the Blynk app (version 1.4) to the custom server 192.168.4.1 port 8442, the serial debug output reports the following error:

[1194] Blynk v0.3.1
[1194] Configuring WiFi access point: Blynk-AP
AP IP address: 192.168.4.1
[1194] Listening on port: 8442
Client connected from 192.168.4.2:51312
Error happened or disconnected.Client disconnected.

Should the code still work, or does it need to be updated, to work with the current iPhone app?

Kind regards,
Markus

**Comment by doom369** [comment]
@markusgritsch The iPhone app. should be changed in order to support direct connect. And this also involves few UI changes. So at the moment you are not able to do that. But some day in future you will.
