### ISSUE TITLE
WiFi Provisioning: drop WiFI AP after getting config command

### ISSUE THREAD

**Issue by eepetrash** [blynkkk/blynk-library#310]
We're facing provisioning issues of SparkFun Blynk Board from iOS devices. From the logs it is seen as the board just can't connect:
```
SSID: freud
Pass: annafreud2013
Auth: 04b3b38ab7bb4ffab779d3275e620d6c
Host: qa.blynk.cc
Port: 8442
Connecting to qa.blynk.cc
Connecting to: freud
..............
Timed out connecting to WiFi.
```
I've noticed, that in such case, the iPhone is still connected to board's WiFI AP (e.g. "BlynkMe-BBYR"). This seems to be an issue.

This is not the case with Android, because Android drops connection to board after sending `config` http request. Unfortunately, there is no way to do the same on iOS.

As experiment, we've tried to provision board from Android without explicitly dropping connection to it after `config` http request. The result was the same as on iOS: board couldn't connect to instructed WiFi network.

**Comment by vshymanskyy** [comment]
[Template_ESP8266_fixed.zip](https://github.com/blynkkk/blynk-library/files/1007996/Template_ESP8266_fixed.zip)
Please verify if this example works win problemtic scenario.

**Comment by vshymanskyy** [comment]
@eepetrash

**Comment by vshymanskyy** [comment]
Reported to work OK - please reopen if issue happens again.
