### ISSUE TITLE
simple question I can't find the answer

### ISSUE THREAD

**Issue by LoloLaurentiu** [blynkkk/blynk-library#311]
<Run Blynk test script (put your auth token): blynk-client 715f8cafe95f4a91bae319d0376caa8c >

this means blynk-client is the test version ?
how can I start it in full version?

thanks

**Comment by doom369** [comment]
Hello. See "Creating a new Node.js project with Blynk" section here : http://help.blynk.cc/hardware-and-libraries/node-js/how-to-install-nodejs-library-on-linux

**Comment by vshymanskyy** [comment]
These kinds of questions should always go to our community forum: https://community.blynk.cc/
