### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#316]
This link is not longer valid. Not sure where it should point to now
https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_USB_Serial/User_Defined_Connection/User_Defined_Connection.ino

![5469e598ad15c572f0d2dedef5c328202ab09df0](https://cloud.githubusercontent.com/assets/1536494/25776221/5b2caa50-32c1-11e7-88b3-0a86a4bfb6a5.PNG)

https://community.blynk.cc/t/wifi-connection-system-not-run/14056/6

**Comment by vshymanskyy** [comment]
fxed
