### ISSUE TITLE
From the customer. The connection is droped after restarting.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#318]
Blynk library version: [...]
IDE: [Arduino/Energia/MBED Compiler/Platform.IO/Eclipse ...]
IDE version: [...]
Board type: [ESP8266]
Additional modules: [...]

### Scenario, steps to reproduce
Customer wrote:

 ```
Whilst I can flash the code and connect to the app - every time it restarts it makes me go through the connection process again. On looking at the code it drops out in ConfigStore.h where the
 EEPROM.get(EEPROM_CONFIG_START, configStore);
  if (configStore.magic != configDefault.magic) {
    DEBUG_PRINT("Using default config.");
    configStore = configDefault;
    return;

doesn't match up with the 'magic'. Any ideas?

```
Dynamic provisioning.

**Comment by vshymanskyy** [comment]
Please do NOT create issues for customer requests here (especially unverified). This makes no sense.
You should arrange direct email conversation on such topics.
