### ISSUE TITLE
Create API to send "Events" from hardware

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#321]
Events are defined on the web and tied to Product:

Command ideas:
 - `Blynk.logEvent(predefined_event_name)` - will render predefined event on the timeline with default description
-  `Blynk.logEvent(predefined_event_name, "description")` will render predefined event on the timeline with given description
- `Blynk.createEvent("Event Name", "description", type)` will create new event on the timeline. Types can be : info, warning, alert

@doom369 will share details
contact @blynkkk for UI

**Comment by doom369** [comment]
Let's skip "createEvent" for now. Code for command would be 60.
