### ISSUE TITLE
ESP8266: RTC fails when SSL enabled

### ISSUE THREAD

**Issue by getmechamot** [blynkkk/blynk-library#325]
Blynk library version: 0.4.7
IDE: Arduino
IDE version: 1.8.2 and earlier versions
Board type: ESP8266
Additional modules: TimeLib, WidgetRTC,BlynkSimpleEsp8266 then BlynkSimpleEsp8266_SSL

### Scenario, steps to reproduce
I'm trying to get RTC from my local Blynk server or from blynk.cc server while using SSL. It works fine without SSL then fails to get time when I enable SSL. This is true for both my local server and the blynk.cc server. 

I would like to be able to use SSL for all hardware-server communication but would also like RTC from the server as opposed to another NTP server.

To replicate:

1. Make Sketch with TimeLib, WidgetRTC,BlynkSimpleEsp8266 and report it (serial, app display, etc.) - RTC time is correct.

2. Edit Sketch, add SSL Blynk module, then RTC time is 0 (ensure you do not retrieve synced value from server!).

Note: I tried to determine if this was a hardware limitation issue but my other option is a brand-new ESP32 board and the Blynk library for ESP32 doesn't appear to support SSL yet.

### Expected Result
hour() value is correct, minute() value is correct, etc.

I should be able to get RTC value and it should sync with SSL enabled, or an insecure port should be used for RTC communication so that hardware can use SSL for transactions with the server and still get RTC sync from that server. 

Worst case scenario: make it easy to use the pool.ntp.org feed to supply the optimal NTP server. 

### Actual Result
hour() value is 0, minute() value is 0, etc. - the sync fails

**Comment by vshymanskyy** [comment]
We would be happy if someone from the community helps to investigate this issue.

**Comment by vshymanskyy** [comment]
On my tests, the board always recovers after second attempt to connect.

**Comment by getmechamot** [comment]
I am attaching my sketch and serial output because it never retrieves time when SSL is enabled. If I'm missing something, I'm happy to be corrected, but the sketch works fine and when I enable SSL by appending _SSL to BlynkSimpleEsp8266, I go from getting time that is correct to time that, no matter how long I wait, is incorrect. 

If the only difference is me enabling SSL, then I don't understand what I could be doing wrong. As per your workaround, I added that line into BlynkProtocol.h and got the same result. Here is my most recent serial output without SSL, then, with SSL, showing multiple connects and the time never is adjusted. After 60 seconds, the time reads 0:01 and after 60 more seconds, it reads 0:02, so it clearly never gets RTC data from the Blynk server, even after 120 seconds where it has connected multiple times. 

**Serial dump with SSL non-enabled (no _SSH for BlynkSimpleEsp8266):**
[3268] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.7 on NodeMCU

[5001] Connecting to blynk-cloud.com:8442
[5080] Ready (ping: 1ms).
First connect
Wifi connected and starting up
time is: 0:00

********************************************
[5203] Time sync: OK
[10081] Connecting to blynk-cloud.com:8442
[10202] Ready (ping: 13ms).
was connected but not firstConnect
The time is: 14:00
[15203] Connecting to blynk-cloud.com:8442
[15277] Ready (ping: 0ms).
was connected but not firstConnect
The time is: 14:00
[20277] Connecting to blynk-cloud.com:8442
[20348] Ready (ping: 1ms).
was connected but not firstConnect
The time is: 14:00
[25349] Connecting to blynk-cloud.com:8442
[25438] Ready (ping: 4ms).
was connected but not firstConnect
The time is: 14:00


**Serial dump with SSL enabled:**
[3268] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.7 on NodeMCU

[5001] Connecting to blynk-cloud.com:8441
[5333] Certificate OK
[5361] Ready (ping: 1ms).
First connect
[5469] Connecting to blynk-cloud.com:8441
[5796] Certificate OK
Wifi connected and starting up
time is: 0:00

********************************************
[10362] Connecting to blynk-cloud.com:8441
[10692] Certificate OK
[10718] Ready (ping: 1ms).
was connected but not firstConnect
The time is: 0:00
[15719] Connecting to blynk-cloud.com:8441
[16038] Certificate OK
[16063] Ready (ping: 1ms).
was connected but not firstConnect
The time is: 0:00
[21064] Connecting to blynk-cloud.com:8441
[21368] Certificate OK
[21407] Ready (ping: 0ms).
was connected but not firstConnect
The time is: 0:00
[26408] Connecting to blynk-cloud.com:8441
[26717] Certificate OK
[26743] Ready (ping: 1ms).
was connected but not firstConnect
The time is: 0:00
[31744] Connecting to blynk-cloud.com:8441
[32055] Certificate OK
[32081] Ready (ping: 1ms).
was connected but not firstConnect
The time is: 0:00
[37082] Connecting to blynk-cloud.com:8441
[37377] Certificate OK
[37419] Ready (ping: 1ms).
was connected but not firstConnect
The time is: 0:00

**Sketch (note, for RTC to work, remove _SSL)**
`

#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266_SSL.h>
#include <TimeLib.h>
#include <WidgetRTC.h>

char auth[] = "myAUTH";
bool isFirstConnect = true;  // flag to not re-sync on every connection

char ssid[] = "mySSID";
char pass[] = "myPWD";

// for counters
int seconds = 0;
int minutes = 0;
int hours = 0;
static unsigned long mscount = millis();

BlynkTimer timer;
WidgetRTC rtc;

// Blynk virtual pin assignments
#define TERMINAL                 0  // V0
#define ALERT                    3  // V3

WidgetTerminal terminal(TERMINAL);

// runs every time Blynk connection is established 
BLYNK_CONNECTED() {
  if (isFirstConnect) {          
    Serial.println("First connect");
    rtc.begin();
    Blynk.syncAll();
    isFirstConnect = false;        
  }
  else {
  Serial.println("was connected but not firstConnect");
  Serial.println("The time is: " + ebShowTime());        
  }
}

// show properly formatted time
String ebShowTime () {
  if (minute() < 10) return (String(hour()) + String("\:0") +  String(minute()));
  else return (String(hour()) + String("\:") +  String(minute()) );
}

void ebTimer() {
  Blynk.connect();
  if (millis() - mscount >= 1000) {
    mscount += 1000;
    seconds ++;
    Blynk.virtualWrite(ALERT,ebShowTime());
  }

  // minutes loop
  if (seconds == 60) {
    seconds = 0;
    minutes ++;
    Serial.println("The time is: " + ebShowTime());        
  }
  if (minutes == 60) {
    minutes = 0;
    hours ++;
    Serial.println("system time: " + String(hours) + ":" + String(minutes));
    Serial.print("human time: ");
    Serial.println(ebShowTime());    
  }
}

void setup() {
  Serial.begin(115200);
  Blynk.begin(auth, ssid, pass);
  if (!Blynk.connected())   {
    Serial.println("WiFi not connected");
    delay(2000);
    return;
  }
  Serial.println("Wifi connected and starting up");
  delay(50);
  Serial.println("time is: " + ebShowTime());    
  Serial.println("");
  Serial.println("********************************************");
  timer.setInterval(1000L, ebTimer);  
  mscount = millis();
}

void loop()
{  
  Blynk.run();
  timer.run(); 
`

**Comment by vshymanskyy** [comment]
I suggest you to re-test after we release 0.4.8 or current master branch

**Comment by getmechamot** [comment]
Shall do – thank you very much. Luckily, there’s lots of other things to work on! 

 

It’s really an incredible thing you’ve built here! :)
