### ISSUE TITLE
BlynkBoard. Can't connect to the WiFi after power off/on.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#328]
Blynk library version: 0.4.3 and 0.4.7
IDE: Arduino
IDE version: 1.8.0 and 1.6.12
Board type: BlynlBoard
Additional modules: -

### Scenario, steps to reproduce
1)Connect Board
2)Flash "myPlant_ESP8266" sketch
3)Use dynamic provisioning to connect board to the home wifi
4)Board is online(in Blynk app)
5)Disconnect board(power OFF)
6)Connect board to USB(power ON)
7)Wait for reconnecting

### Expected Result
Board connect to the same WiFi network.

### Actual Result
After +- 30sec board LED blynk RED color.
Monitor show:
```
[31618] CONNECTING_NET => ERROR
[41622] Restarting after error.

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
[672] 
[672] Hardware v1.0.0
[673] Firmware v1.0.1
[673] WAIT_CONFIG => CONNECTING_NET
[673] Connecting to WiFi: Dom2
[31633] CONNECTING_NET => ERROR
[41638] Restarting after error.

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
[672] 
[672] Hardware v1.0.0
[672] Firmware v1.0.1
[673] WAIT_CONFIG => CONNECTING_NET
[673] Connecting to WiFi: Dom2

```

**Comment by vshymanskyy** [comment]
Please re-test with the latest version of library and examples

**Comment by vshymanskyy** [comment]
I could not reproduce it with the latest version

**Comment by vshymanskyy** [comment]
Closed for now. Please report if issue continues
