### ISSUE TITLE
including <BlynkWidgets.h> fails for linux example

### ISSUE THREAD

**Issue by rabarar** [blynkkk/blynk-library#33]
Attempting to include BlynkWidgets.h into the example main.cpp fails to compile - can't find Print.h header file.

Is this not the correct way to access the widgets in the Raspberry Pi main.cpp?

**Comment by vshymanskyy** [comment]
We're now suggesting to use our Node.js library on linux platforms... What do you think?

**Comment by rabarar** [comment]
Personally, I think a c/c++ compiled binary is a better way to go. 

You aren't limited to access any sensor data that way. It was a five minute process to leverage existing sensor code whereas repackaging that for node would be more involved.

**Comment by rabarar** [comment]
So much for the c/c++ API ...

**Comment by vshymanskyy** [comment]
em.. what do you mean? )

**Comment by rabarar** [comment]
Without header files that allow you to build a binary with c/c++, you can't use those language bindings to fully access all of the Blynk widgets.

Personally I'd clean up the build process so the Linux c/c++ works rather than abandon it.
