### ISSUE TITLE
Add troubleshooting for "ESP is not responding" (previously: "Failed to disable echo")

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#333]
Very often request in support. Could you please add some clear troubleshooting guide for it?

**Comment by vshymanskyy** [comment]
Error changed to "ESP is not responding"

**Comment by doom369** [comment]
@vshymanskyy we still need some todo or docs that will guide user on how to resolve this and where to look.

**Comment by vshymanskyy** [comment]
Fixed. please update generator webpage
