### ISSUE TITLE
RTS widget. Synchronize the time after the connection to the server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#337]
Also allow users to set the synchronization time interval.

**Comment by doom369** [comment]
@vshymanskyy would be very useful, or maybe some default sketch that does that as we getting many requests "RTC not working".

**Comment by vshymanskyy** [comment]
What's the problem? Just read docs for time library...

**Comment by doom369** [comment]
The problem is nobody reads docs.

**Comment by vshymanskyy** [comment]
@Refenz please re-test RTC example
