### ISSUE TITLE
App preview for ESP8266

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#338]
https://community.blynk.cc/t/app-preview-on-android-with-esp8266/15238

Maybe we need to add 

`#define USE_ESP8266_BOARD `?

It is not clear for end users what to choose for ESP8266.

**Comment by vshymanskyy** [comment]
No, it makes no sense. ESP8266 is too generic, we do not provide predefined setup - they should use Custom.

**Comment by doom369** [comment]
@vshymanskyy could you please update doc in that case and comments in the sketch?
