### ISSUE TITLE
Integrate into Arduino IDE Library Manager

### ISSUE THREAD

**Issue by homerruma** [blynkkk/blynk-library#34]
I do not find Library in Arduino ide 1.6.5 in the library manager.
How can I find blynk-library?

**Comment by vshymanskyy** [comment]
You have to install it manually, just download zip and unpack it (it contains several libraries).
We will add Blynk to Library Manager later (after they add dependency management...)

**Comment by homerruma** [comment]
OK thank's.

**Comment by vshymanskyy** [comment]
Should appear in Library manager soon (note that it will install without dependencies!).
