### ISSUE TITLE
ButtonWidget for syncing physical and virtual

### ISSUE THREAD

**Issue by Fettkeewl** [blynkkk/blynk-library#341]
I think it's time now for a ButtonWidget class for blynk library that handles synchronization between a virtual and physical pin. 

Initialization and instantiation:
ButtonWidget button1(virtualPin, physicalPin) 

Sync is handled in background by Blynk.run()

Extra suggested functions:
.pinMode(Mode) // just for altering depending on circuit 
.vibrate(boolean) // vibrates phone when physical button is pressed

**Comment by vshymanskyy** [comment]
Why should ButtonWidget be limited only to syncing with a physical digital pin?

**Comment by Fettkeewl** [comment]
Not sure how you mean? I wasnt asking it as a limiter, more of an extender.

use case, I need to turn on a lamp and I want a physical button to update digital switch button in the app, 

atm the "syncing" between the two needs manual implementation everytime.
I wanted it to boil down to 2 basic needs

WidgetButton object, tied to a virtualPin and a physicalPin
and a 
BLYNK_WRITE function. 

The WidgetButton object should call BLYNK_WRITE internally no matter the pushed source phys/digital
and if physical is pressed, the digital is updated aswell. This ofc only works with momentary push buttons .

Is my explanation understandable? Im at work so cant write to much :P

**Comment by vshymanskyy** [comment]
Yeagh. I don't think I will have time to work on this - but contributions are welcome ;)

**Comment by vshymanskyy** [comment]
Closed due to lack of interest
