### ISSUE TITLE
Particle. Can't compile base-sketch for Electron.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#342]
Blynk library version: [0.4.8]
IDE: Particle-CLI
Board type: Particle Electron

### Scenario, steps to reproduce
Try to compile an example from the library.

### Expected Result
Working binary file.

### Actual Result
Compilation error.
Full log: [Log.txt](https://github.com/blynkkk/blynk-library/files/1102513/Log.txt)
P.S. The same actions with 0.4.7 are successful.

**Comment by vshymanskyy** [comment]
Could you try updating your particle-cli ?

**Comment by vshymanskyy** [comment]
@Refenz is the issue resolved?
