### ISSUE TITLE
Add Chronometer widget - timer pressed button

### ISSUE THREAD

**Issue by andregm3** [blynkkk/blynk-library#348]
add a chronometer to for example keep a button pressed for 5 seconds and then release it.

**Comment by andregm3** [comment]
like this app: https://play.google.com/store/apps/details?id=com.appshed.appcar

where you can create a list of tasks for a wheel robot to do.

like go foward 5 seconds

rotate left 2 seconds

![dadasd](https://user-images.githubusercontent.com/4154732/28179186-904087ac-67d7-11e7-9c83-08a398470a75.png)


https://www.youtube.com/watch?v=Afxh7NwEbpw&feature=youtu.be

**Comment by vshymanskyy** [comment]
You can implement this easily with virtual pins.

**Comment by doom369** [comment]
Maybe we will add such widget someday.
