### ISSUE TITLE
In iOS app terminal widget show nothing.

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-library#350]
I add a terminal widget.
In android app, terminal is work good.
But in iOS app, it show nothing.

```cpp
...
WidgetTerminal console(101);
...
void show() {
  if (Blynk.connected()) {
    console.println("abc");
    console.flush();
  }
}
...
```

**Comment by doom369** [comment]
Do you use latest app version?

**Comment by bestpika** [comment]
@doom369 yes, my installed version is 2.9.7 (2017.07.13).
And I use blynk server (0.25.4).

**Comment by doom369** [comment]
@bestpika ok. thanks. we will check. I created ticket in another repo as this is not library issue.
