### ISSUE TITLE
Add Arduino UNO WiFi support (WiFiLink)

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#353]
https://community.blynk.cc/t/solved-arduino-org-uno-wifi-board-with-firmware-1-0-0-and-wifilink-h-librairies/15947/40?u=vhymanskyy

**Comment by tech-rostand** [comment]
Hey ! 
At the moment the library examples, works very well. I tested the led and button widget in the case of get and push data with Vpin.
