### ISSUE TITLE
Blynk / Electron Data Usage EXTREMELY HIGH

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#358]
https://community.blynk.cc/t/blynk-electron-data-usage-extremely-high/16577

**Comment by vshymanskyy** [comment]
Here are results of my test:
```
#define BLYNK_HEARTBEAT 120
#define PARTICLE_KEEPALIVE 60

And (once per minute):
 Blynk.virtualWrite(V2, millis() / 60000L);
```
After 12 hours, our local Cellular provider reports 0.41 Mb of data usage.
I use 3-rd party sim, which I pay around $1.2 per month, and it includes 10Mb per day + Voice Call and SMS plans.
I consider this kind of charges completely adequate.
