### ISSUE TITLE
iOS App Crash.

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-library#360]
I use Blynk app (2.10.1 2017/08/19) with Blynk server (0.26.3).
But I don't known why my app crash often.

I have a lot of project (over 10) and every project have a lot of widget (over 30).
Maybe the problem is from this?
But I didn't delete any project and widget.

**Comment by eepetrash** [comment]
@bestpika
Do crashes appear randomly or is there any pattern you could catch? 
Did crashes appear before 2.10.* update?

Many projects (especially in running mode) with heavy widgets (e.g. map, charts, etc.) might be an issue if your iPhone can't handle the workload (so called out-of-memory type of crashes).

**Comment by bestpika** [comment]
Crash when I change project.
Previous version no crash.

**Comment by vshymanskyy** [comment]
Sorry, this is not library issue, so closing it. you can continue your conversation.
