### ISSUE TITLE
Implement BLYNK_EVERY_N_SECS, BLYNK_EVERY_N_MILLIS

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#361]

**Comment by vshymanskyy** [comment]
Usage:
```cpp
void loop() {
  ...
  BLYNK_EVERY_N_MILLIS(500) {
    Serial.println("Woa!!!");
  }
  ...
}
```
Supported variants:
* `BLYNK_EVERY_N_MILLIS(ms)`
* `BLYNK_EVERY_N_SECONDS(sec)`
* `BLYNK_EVERY_N_MINUTES(min)`
* `BLYNK_EVERY_N_HOURS(hour)`

**Comment by doom369** [comment]
@vshymanskyy is that good idea to put it in the loop?

**Comment by doom369** [comment]
@vshymanskyy examples?

**Comment by vshymanskyy** [comment]
we have no other option

**Comment by vshymanskyy** [comment]
Examples will not be updated untill feedback and testing by community

On 2 Sep 2017 11:59 a.m., "Volodymyr Shymanskyi" <vshymanskyi@gmail.com>
wrote:

we have no other option
