### ISSUE TITLE
Failed to flash the board through the OTA using a local server.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#362]
https://github.com/blynkkk/blynk-server/issues/719
Last version of the server and library.
1)Run local server:
`java -jar server.jar -dataFolder /path`
2)Connect SF Blynk Board
3)Use dynamic provisioning to connect board
4)Change sketch and create binary file
5)Use:
`curl -v -F file=@Template_ESP82662.ino.nodemcu.bin --insecure -u admin@blynk.cc:admin https://localhost:9443/admin/ota/start`
AR:
After reboot, the board tries to use the new firmware. After the error, it reboots and the process repeats.
A binary file is available for downloading via the browser.
```
[5467] RUNNING => OTA_UPGRADE
[5968] Firmware update URL: http://192.168.113.2:8080/static/ota/FUp_6165330441115044621_upload.bin
[12049] Firmware update failed (error -1): HTTP error: connection refused
[12050] OTA_UPGRADE => ERROR
[22057] Restarting after error.

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
[863] 
[863] Hardware v1.0.0
```
P.S. the same flow works on a QA server

**Comment by doom369** [comment]
@vshymanskyy does library support `:8080` port part of request uri?

**Comment by vshymanskyy** [comment]
it **should** support specifying port - but to verify it, we need to test a case with local server, with default port.

**Comment by vshymanskyy** [comment]
@Refenz what is IP address of the device itself?

**Comment by vshymanskyy** [comment]
@Refenz is issue resolved?

**Comment by Refenz** [comment]
@vshymanskyy 
Yes. All is fine.
Thanks!
