### ISSUE TITLE
Add Orange PI to supported boards

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#363]
Very often we get asked about orange pi. Let's just add it to boards list to avoid this quetions.

**Comment by scropion86** [comment]
**here to list compatible boards of orange Pi**
Most of the user use it Running ether [Armbian ](https://www.armbian.com/)or Ubuntu Core

- Orange Pi Zero 
- Orange Pi One 
- Orange Pi Lite 
- Orange Pi PC 
- Orange Pi pc 2 
- Orange Pi Pc Plus 
- Orange Pi Plus 2E 
- Orange Pi Plus 
- Orange Pi Plus2 
- Orange Pi Zero Plus2 
- Orange Pi 2G-10T 
- OPI Win,' Win Plus 
- Orange Pi Prime 
- Orange Pi 196 
- Orange Pi Zero Plus 
- Orange Pi RI 

**Also below is [FriendlyArm ](http://www.friendlyarm.com/index.php?route=product/category&path=69)a very popular Boards which will be requested**
Most of the user use it Running ether [Armbian ](https://www.armbian.com/), Debian  or Ubuntu

- NanoPi Duo
- NanoPi NEO Plus2
- NanoPi K2
- NanoPi NEO2
- NanoPi M1 Plus
- NanoPi A64
- NanoPi S2
- NanoPi NEO Air
- NanoPi NEO
- NanoPi M2A
- NanoPC-T3
- NanoPC-T2

**Comment by vshymanskyy** [comment]
@doom369 
It will continue to happen with other boards (like nRF51 and 52 - we get lots of requests for those too).
I recommend to make a small change in UI for iOS and Android:
Add an item "My board is not in the list..." as the last item of device list, explain the situation an select Generic Board automatically.

**Comment by doom369** [comment]
@vshymanskyy discussed with Pavel. Solution - let's add all these boards to the list. It is much more simpler + has "Wow" effect for customers :). Please add above boards to list.
