### ISSUE TITLE
BlynkSimpleWifilynk.h is missing.

### ISSUE THREAD

**Issue by tech-rostand** [blynkkk/blynk-library#370]
Hello,
you announce the supportof the Aruino Uno Wifi card, but you give no example in the sketch Builder and you forgot to file BlynkSimpleWifiLynk.h in the update while it is present in the depot.
Can you explain that to me?
Regards Emmanuel_leroy

**

Blynk library version: [...]
IDE: [Arduino/Energia/MBED Compiler/Platform.IO/Eclipse ...]
IDE version: [...]
Board type: [...]
Additional modules: [...]

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by vshymanskyy** [comment]
First of all where did you get your "BlynkSimpleWifilynk.h" from?
There's an official example for UNO WiFi in Examples, shipped with the library.
We do not always update example builder - which is a different component (not part of the library).

**Comment by tech-rostand** [comment]
Hello, i found the BlynkSimpleWifilynk.h in https://github.com/blynkkk/blynk-library/tree/master/src/BlynkSimpleWiFiLink.h

And there is no Example for the Uno Wifi ( of arduino.org with the wifilink librairies).
In the example of the 0.4.10, i just see for Uno Wifi shield and Uno Wifi whield 101.
And i do the Blynk script update in Arduino 1.8.3 to upgrade.
And i checked twice the Blynk_Release_v0.4.10.zip. BlynkSimpleWifilink.h is missing in the \libraries\blynk\scr folder

Best regards M. Leroy

**Comment by vshymanskyy** [comment]
Hey, you're right. Sorry.
Arduino.org UNO WiFi wasn't announced AFAIK for release yet!
It was just published on github (in master branch).
It is scheduled for next release.

**Comment by vshymanskyy** [comment]
You can try downloading master branch and using it with you HW

**Comment by vshymanskyy** [comment]
As per release announcement, I don't see UNO WiFi support: https://community.blynk.cc/t/new-blynk-library-v0-4-10-is-released/18545

**Comment by tech-rostand** [comment]
It’s because the board is in your Full list of supported hardware is here <https://github.com/blynkkk/blynkkk.github.io/blob/master/SupportedHardware.md> 35 of your annoucement. 😉

 

I already use the wifilink lIbrarie 😉

I’m Emmanuel Leroy from https://community.blynk.cc/t/solved-arduino-org-uno-wifi-board-with-firmware-1-0-0-and-wifilink-h-librairies/15947/40

 

The librarie is stable and works fine.

My student works today with the lcd, button and Gauge widget and a DhT11 sensor of Seedstudio.

 

#define BLYNK_PRINT Serial

 

 

#include <SPI.h>

#include <WiFiLink.h>

#include <BlynkSimpleWifiLink.h>

#include <DHT.h>

 

// You should get Auth Token in the Blynk App.

// Go to the Project Settings (nut icon).

char auth[] = "xxxxxxx";

 

// Your WiFi credentials.

// Set password to "" for open networks.

char ssid[] = "xxxxxxx";     //  your network SSID (name)

char pass[] = "xxxxx";  // your network password

int status = WL_IDLE_STATUS;     // the Wifi radio's status

 

 

 

#define DHTPIN 2          // What digital pin we're connected to

 

// Uncomment whatever type you're using!

#define DHTTYPE DHT11     // DHT 11

//#define DHTTYPE DHT22   // DHT 22, AM2302, AM2321

//#define DHTTYPE DHT21   // DHT 21, AM2301

 

DHT dht(DHTPIN, DHTTYPE);

BlynkTimer timer;

 

// This function sends Arduino's up time every second to Virtual Pin (5).

// In the app, Widget's reading frequency should be set to PUSH. This means

// that you define how often to send data to Blynk App.

 

void sendSensor()

{

  float h = dht.readHumidity();

  float t = dht.readTemperature(); // or dht.readTemperature(true) for Fahrenheit

 

  if (isnan(h) || isnan(t)) {

    Serial.println("Failed to read from DHT sensor!");

    return;

  }

  // You can send any value at any time.

  // Please don't send more that 10 values per second.

  Blynk.virtualWrite(V5, h);

  Blynk.virtualWrite(V6, t);

  Blynk.virtualWrite(V7, t);

  Serial.println(h);

  Serial.println(t);

}

 

void setup()

{

  // Debug console

  Serial.begin(9600);

 

  Blynk.begin(auth, ssid, pass, "blynk-cloud.com", 8442);

  // You can also specify server:

  //Blynk.begin(auth, "blynk-cloud.com", 8442);

  //Blynk.begin(auth, IPAddress(192,168,1,100), 8442);

 

  dht.begin();

 

  // Setup a function to be called every 3 second

  timer.setInterval(3000L, sendSensor);

}

 

void loop()

{

  Blynk.run();

  

  timer.run();

}

 

Best regards M. leroy

 

De : Volodymyr Shymanskyy [mailto:notifications@github.com] 
Envoyé : lundi 6 novembre 2017 20:03
À : blynkkk/blynk-library <blynk-library@noreply.github.com>
Cc : Mr_Leroy <tech.rostand@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [blynkkk/blynk-library] BlynkSimpleWifilynk.h is missing. (#370)

 

As per release announcement, I don't see UNO WiFi support: https://community.blynk.cc/t/new-blynk-library-v0-4-10-is-released/18545

**Comment by vshymanskyy** [comment]
Correct. But it wasn't explicitly announced ;)
Just wait a few days more ))) P. Patience!
