### ISSUE TITLE
Terminal.println doesn't work in the same way as Blynk.virtualWrite with UTF-8 strings

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#372]
More details here: 

https://community.blynk.cc/t/terminal-can-not-output-chinese-properly/19301

**Comment by vshymanskyy** [comment]
@Refenz could you please check this on the master branch?

**Comment by vshymanskyy** [comment]
The bug was regarding .virtualWrite acting dufferently from terminal.write.
Looks ok now.

**Comment by vshymanskyy** [comment]
@Refenz you need to be sure that your IDE uses utf8 encoding?

**Comment by vshymanskyy** [comment]
@doom369 this can only be fixed on server side. I'll create a ticket
