### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by mpo881** [blynkkk/blynk-library#375]
Blynk library version: any
IDE: Particle
IDE version: [...]
Board type: Electron
Additional modules: [...]

### Scenario, steps to reproduce
I am modifying the heartbeat from 10 to whatever works with my project. Data overhead to run Blynk is very high at 10s heartbeat. 

### Expected Result
I would like to be able to modify #define BLYNK_HEARTBEAT in my code without having to copy and paste every tab of the library into my project just to change a few numbers on one line of BlynkConfig.h Would it be possible to make the line in the config file a variable so that you can easily edit the line in your code? Thank you

### Actual Result
You must copy and paste each tab. Very time consuming, cumbersome and prone to mistakes!

**Comment by vshymanskyy** [comment]
Thanks, I'll re-check it

**Comment by vshymanskyy** [comment]
Specifying BLYNK_HEARTBEAT 30 before any of Blynk includes - absolutely works!
Can be verified by BLYNK_DEBUG
