### ISSUE TITLE
Time Input. Displays the wrong information on the serial port when no day is selected.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#376]
Blynk library version: [0.4.8]
IDE: [Arduino]
IDE version: [1.8.4]
Board type: [ESP8266]
Additional modules: [...]

### Scenario, steps to reproduce
1)Use:https://github.com/blynkkk/blynk-library/blob/master/examples/Widgets/TimeInput/AdvancedTimeInput/AdvancedTimeInput.ino
2)Start project
3)Open Time Input
4)Choose some time and doesn't choose day
5)Press "Ok"

### Expected Result
```
Start: 0:0:1
Stop: 0:0:2
Time zone: Europe/Kiev
Time zone offset: 7200
```
Or
```
Start: 0:0:1
Stop: 0:0:2
Time zone: Europe/Kiev
Time zone offset: 7200
No day is selected.
```

### Actual Result
```
Start: 0:0:1
Stop: 0:0:2
Time zone: Europe/Kiev
Time zone offset: 7200
Day 1 is selected
Day 2 is selected
Day 3 is selected
Day 4 is selected
Day 5 is selected
Day 6 is selected
Day 7 is selected
```

**Comment by vshymanskyy** [comment]
@Refenz it looks like expected behaviour. Consult with dima
