### ISSUE TITLE
Error in lib on compile/verify (Arduino 101 BLE)

### ISSUE THREAD

**Issue by golyalpha** [blynkkk/blynk-library#380]
Blynk library version: latest release (as of writing)
IDE: Arduino
IDE version: 1.8.4
Board type: Arduino 101
Additional modules: None

### Scenario, steps to reproduce
Get a BLE GPS example from the example generator
Copy-paste
Try to compile

### Expected Result
Successful compilation

### Actual Result

In file included from C:\Users\..\Blynk\src/BlynkSimpleCurieBLE.h:24:0,

                 from C:\Users\...\Blynk_BLE_Test.ino:4:

C:\Users\...\Blynk\src/utility/BlynkFifo2.h: In member function 'T BlynkFifo<T, N>::peek()':

C:\Users\...\Blynk\src/utility/BlynkFifo2.h:115:16: error: 'r' was not declared in this scope

         while (r == _w);

                ^

C:\Users\...\Blynk\src/utility/BlynkFifo2.h:116:19: error: 'r' was not declared in this scope

         return _b[r];

                   ^

exit status 1
Error compiling for board Arduino/Genuino 101.

**Comment by vshymanskyy** [comment]
Please try the latest master pranch
