### ISSUE TITLE
Support for Ameba Devices (RT8711/8195) in the blynk app

### ISSUE THREAD

**Issue by narioinc** [blynkkk/blynk-library#385]
Hi Team

Thanks for the community effort into making the blynk project a wonderful place to test out and analyse data from iot devices.

I have a small issue where i am trying to get a Ameba device (RT8195AM board and a customer RTL8711AM board) to connect with Blynk. However the app currently doesnt show an option to add a RTL chipset based board.

Can i select Generic Board in the board selection menu and then program the RTL board with the Blynk library. I recently saw that the Blynk library supports Ameba baords so curious to try and give it a spin

Regards
Naresh K

**Comment by narioinc** [comment]
Team

Also to test the basic functionality with a RTL8195 board, is there a sample available ?

**Comment by narioinc** [comment]
The board in my setup is a RAK473 Based Creator pro board based on the RTL8711AM chipset made by Rak Wireless.

**Comment by narioinc** [comment]
Hi Team

Was able to get the RTL8711AM and RT8195AM board connected to blynk API like so:

RTL8195A[Driver]: start auth to xx:xxx:xx:xx:xx



RTL8195A[Driver]: auth success, start assoc



RTL8195A[Driver]: association success(res=7)



RTL8195A[Driver]: set pairwise key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4)



RTL8195A[Driver]: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:1



RTL8195A[Driver]: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:1



Interface 0 IP address : 192.168.1.xx[5007] Connected to WiFi
[5014] IP: 192.168.1.xx
[5021] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.5.0 on RTL8195A

[5059] Connecting to blynk-cloud.com:8442


Connect to Server successful!

[5237] Ready (ping: 50ms).


Looks good :) cant wait to try out other interesting stuff :) on the blynk platform.
I had to modify the BlynkWifixxx.h to introduce a new one for the RTL8195AM I am not sure if i can send a pull request but it was relatively easy to make the changes and run it.

Thanks Team.

**Comment by vshymanskyy** [comment]
Glad it's working for you. Basically we do not plan to support this option in the app. Just use Generic Board. Sure you can send a pull request ;)

**Comment by narioinc** [comment]
Sure will do,
I have some edit done to the code to keep inline with the code standard that i saw in the Blynk library. Will post the PR soon. 

Thanks
