### ISSUE TITLE
BlynkSimpleEsp8266_SSL can't be complied for NodeMCU board

### ISSUE THREAD

**Issue by shur1k** [blynkkk/blynk-library#387]
Trying to use SSL version of Esp8266 library causes the problem:
BlynkSimpleEsp8266_SSL.h:132:9: error: 'class WiFiClientSecure' has no member named 'setCACert_P'
Switching back to non-secure library BlynkSimpleEsp8266.h solves the problem and everything works fine. 
Is there any way to force SSL library work for NodeMCU board?
Thank you.

**Comment by vshymanskyy** [comment]
Please update your ESP8266 core.

**Comment by shur1k** [comment]
Thanks! Works fine now.
