### ISSUE TITLE
Add doc for handling "DHCP Failed"

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#39]

**Comment by vshymanskyy** [comment]
What do you mean exacltly

**Comment by doom369** [comment]
We need steps in docs (troubleshooting) with description what user should do exactly with above problem in order to start Blynking.

**Comment by vshymanskyy** [comment]
there is no such step-by-step. Or maybe I.missed something...

**Comment by doom369** [comment]
Of course, but we need to provide some help and advices. Or you are welcome to answer it every time somebody asks it =).

**Comment by vshymanskyy** [comment]
DHCP is device-specific.
We can't cover it in generic way.
DHCP error is happening to people rather rarely. Searching DHCP through forum helps.

**Comment by doom369** [comment]
Well, we can explain in same way we did on forum. C'mon man, you know it should be done. It will save our time in future.

**Comment by vshymanskyy** [comment]
Maybe next week )

**Comment by arvindpdmn** [comment]
I am getting DHCP error but so far no solution on forum as well. Meanwhile I am continuing to debug what I can. Any help, much appreciated. In my case, DHCP server is working, client gets DHCP address and yet Blynk.begin() says DHCP error!

My post on forum:
http://community.blynk.cc/t/nodemcu-giving-dhcp-error-but-gets-ip-address/3750
