### ISSUE TITLE
ESP32. Dynamic Provisioning. At compilation the file ESP32Ticker.h is necessary.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#390]
Blynk library version: [0.5.0]
IDE: [Arduino]
IDE version: [1.8.4]
Board type: [ESP8266]

### Scenario, steps to reproduce
1. Add support for ESP32 (download https://github.com/espressif/arduino-esp32)
2. Open Tempalte_ESP32
3. Click on the compile button

### Expected Result
The sketch compilation takes place without errors.

### Actual Result
```
In file included from sketch\BlynkProvisioning.h:16:0,

                 from C:\Users\Home\Documents\Arduino\libraries\blynk-library\examples\Export_Demo\Template_ESP32\Template_ESP32.ino:18:

sketch\Indicator.h:209:84: fatal error: ESP32Ticker.h: No such file or directory

compilation terminated.

Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Home\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi
 Not used: C:\Program Files\Arduino\libraries\WiFi
exit status 1
Error compiling for board ESP32 Dev Module.
```

P.S. after adding these files(https://github.com/bertmelis/Ticker-esp32), the compilation is successful.
I'm assuming an error or need to add the specified files to the library/installation steps.

**Comment by vshymanskyy** [comment]
What is the problem?
