### ISSUE TITLE
Change the LED's used color from BLUE to "Blynk" when using Dynamic Provisioning.

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#397]
https://github.com/blynkkk/blynk-library/blob/8e0679867f963bd8c5eb4fd3f470fea91231b349/examples/Export_Demo/Template_ESP8266/Indicator.h#L54
In accordance with the new design:
![green](https://user-images.githubusercontent.com/16590099/36180801-917b578a-112a-11e8-8ce1-ddba0430aacd.PNG)

**Comment by vshymanskyy** [comment]
Please re-check it with Pavel.

**Comment by Refenz** [comment]
@vshymanskyy 
I clarified this task. The work of the hardware is done correctly.
The text description in the application will be changed.
