### ISSUE TITLE
ESP8266: ADC_MODE(ADC_VCC) incompatibility

### ISSUE THREAD

**Issue by vshymanskyy** [blynkkk/blynk-library#399]
```cpp
ADC_MODE(ADC_VCC);

#include <ESP8266WiFi.h>          // wifi
#include <BlynkSimpleEsp8266.h>   // blynk library

char auth[] = "YourAuthToken";
char ssid[] = "YourNetworkName";
char pass[] = "YourPassword";

void setup()
{
  Blynk.begin(auth, ssid, pass);
}

void loop()
{
  Blynk.run();
}

BLYNK_WRITE(V10) {}
```

=>

```
sketch_feb17a:20: error: variable or field 'BlynkWidgetWrite10' declared void
 BLYNK_WRITE(V10) {}
                                                            ^
sketch_feb17a:20: error: 'BlynkReq' was not declared in this scope
 BLYNK_WRITE(V10) {}
                         ^
sketch_feb17a:20: error: expected primary-expression before 'const'
 BLYNK_WRITE(V10) {}
```

**Comment by ClintonKeith** [comment]
This problem applies to other platforms as well with any kind of macro

Example:
#define RANDOM_MACRO(mode) int empty_function(void) { return (int) (mode); }

If you instantiate the macro above the include
#include <BlynkSimpleEsp8266.h>   // blynk library
you get the compile error, but if it's below the include it doesn't.

This applies (in my case) to 
#include <BlynkSimpleEthernet2.h>

**Comment by vshymanskyy** [comment]
Workaround available: https://community.blynk.cc/t/variable-or-field-blynkwidgetwrite100-declared-void/22046/24?u=vhymanskyy

**Comment by pieman64** [comment]
@vshymanskyy  I think we need more than a workaround. We need to know what the problem is.

**Comment by vshymanskyy** [comment]
@pieman64 welcome to investigate! ;)

**Comment by pieman64** [comment]
I have, I checked out the two completely different sketches that fail to compile.

**Comment by vshymanskyy** [comment]
I was investigating it, and it looks like the compiler/toolchain issue. The workaround works, so I'm closing this.
