### ISSUE TITLE
Make Blynk appear in Particle list as verified library

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#402]
![image](https://user-images.githubusercontent.com/11541426/37098265-80570266-21eb-11e8-8e25-b215ed4801d6.png)

**Comment by vshymanskyy** [comment]
Fisrt of all, why HIGH PRIORITY for this?
Secondly - we already started this process long time ago and still not there. Looks like Particle just doesn't want to highlight us.

**Comment by blynkkk** [comment]
Don't close. It's an open issue
https://docs.particle.io/guide/tools-and-features/libraries/#verified-libraries
