### ISSUE TITLE
BlynkSimpleEthernet.h: No such file or directory

### ISSUE THREAD

**Issue by xtfishburnx** [blynkkk/blynk-library#404]
Blynk library version: 0.5.1
IDE: Arduino
IDE version: 1.0.5
Board type: Arduino UNO
Additional modules: None

### Scenario, steps to reproduce
I am attempting to compile and upload the Arduino_Ethernet example.

### Expected Result
I expect the code to compile and upload without a problem.

### Actual Result
I get an error saying that the BlynkSimpleEthernet.h file does not exist. The error reads as "Arduino_Ethernet.ino:39:33: fatal error: BlynkSimpleEthernet.h: No such file or directory
compilation terminated."

**Comment by vshymanskyy** [comment]
Not reproducible.
