### ISSUE TITLE
Help needed for Blynk.email and time of day

### ISSUE THREAD

**Issue by robademar** [blynkkk/blynk-library#405]
I would like to send an email including the time of day. 
Unfortunately any attempt to include a string of character or an integer gives compilation error.
I could not find anywhere explanation about the Blynk.email format.
Can somebody give me an advise?

**Comment by Refenz** [comment]
@robademar 
Please try to create a topic or try to find the answer on the forum: [https://community.blynk.cc](https://community.blynk.cc)

**Comment by robademar** [comment]
sorry
