### ISSUE TITLE
Arduino.org Uno WiFi example doesn't need SPI.h

### ISSUE THREAD

**Issue by jandrassy** [blynkkk/blynk-library#406]
the example for Uno WiFi has unnecessary SPI include. with WiFiLink 1.0.x the necessary includes of Wire for Uno WiFi or SPI for Primo are inside WiFiLink library. and WiFi Link version 1.1.x takes Stream implementation for serial communication with the firmware in esp8266. With Uno WiFi [the Uno WiFi Serial1 library](https://github.com/jandrassy/UnoWiFiDevEdSerial1/blob/master/examples/UnoWiFiBlynk/UnoWiFiBlynk.ino) is used.

one more small thing. in BlynkSimpleWiFiLink.h the copyright date jan 2017  can't be right. WiFi Link was available from Mar 2017. jan 2018 was meant?

and thank you for Blynk. it is great. simple to use and powerful

**Comment by vshymanskyy** [comment]
Thanks for your comments. Does anything that you describe cause any troubles for you?

**Comment by jandrassy** [comment]
not for me, but the SPI include could be confusing for some newbie
