### ISSUE TITLE
examples->Boards_Bluetooth->BBC_MicroBit:    "Packet too big:" 

### ISSUE THREAD

**Issue by DF-LeeX** [blynkkk/blynk-library#418]
Blynk version: 2.25.0
Library version: v0.5.3

Detailed information:
Waiting for connections...
[38] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.5.3 on nRF5

  Give Blynk a Github star! => https://github.com/blynkkk/blynk-library

[265] Connecting...
[6058] Packet too big: 25392
[6089] Packet too big: 26160
[6120] Packet too big: 13873
[8151] Connecting...
[14151] Connecting...**

**Comment by vshymanskyy** [comment]
Do you use BBC_MicroBit or any other board?

**Comment by vshymanskyy** [comment]
Closed due to lack of interest

**Comment by zafersn** [comment]
hi. I am having the same problem.

```
[5917] BLE connect
[8110] >> 144:-78,66:-6,25:1,09[0A]
[8110] >144:-
[8110] Packet too big: 14893
[8111] >78,66
[8111] Packet too big: 13878
[8111] >:-6,2
E 8(11116]38 P5)ac kBTet: t oGAoT bTSi_gS: en11dR31sp4 
c
o81n1n6_]id >: 
4
8  11wa8i] tPinacgk efot rt oopo_ bcoigd:e  =11 03102



E (16397) BT: Sending response failed

[11123] Bad hdr len: -1

```

**Comment by vshymanskyy** [comment]
You should use community forum for such questions. Lots of interesting answers already there

**Comment by zafersn** [comment]
@vshymanskyy none of these and other similar questions on the forum have a solution. incomplete
