### ISSUE TITLE
Received the Following Error in ESP8266_HardSer

### ISSUE THREAD

**Issue by Suresh3012** [blynkkk/blynk-library#42]
ESP8266_Shield_HardSer.ino:31:29: fatal error: ESP8266_HardSer.h: No such file or directory
compilation terminated.
Error compiling.

I initially doughted there might be issues with installing the library but even after reinstalling i had the same issue.

NOTE: All others examples are working fine expect ESP8266_HardSer and ESP8266_SoftSer Examples

**Comment by vshymanskyy** [comment]
You should copy all libraries from the latest release ZIP package (it includes libraries you're mentioning). We will make it easier once Arduino IDE supports library dependencies.
