### ISSUE TITLE
SuperChart delta values 

### ISSUE THREAD

**Issue by dontsovcmc** [blynkkk/blynk-library#421]
I write increasing values to VirtualPin. I add SuperChart to see history. I need to compare values between measures: see columns upper zero and lower. Like this: http://criticaltosuccess.com/wp-content/uploads/2014/05/IMG-Difference-Chart-Actual-v-Target-01.png
I see straight SuperChart settings 'delta', but I can't understand how it works.

Is it possible?

If it is not possible, maybe I should calculate deltas on the device and send to another pins?
The better way to do this is read previous values from virtual pin, calculate delta, send new data. I don't see API for reading values..

**Comment by vshymanskyy** [comment]
Again, please use Blynk community forum for such questions. You may just copy-paste it
