### ISSUE TITLE
virtualWrite value issue

### ISSUE THREAD

**Issue by bestpika** [blynkkk/blynk-library#424]
Blynk library version: `0.5.3`
IDE: `Arduino`
IDE version: `1.8.0`
Board type: `WeMos D1 mini` (core version is 2.3.0)
Additional modules:

### Scenario, steps to reproduce
1. virtualWrite a `double` type's value

### Expected Result
A value.

### Actual Result
`%.7f`

**Comment by vshymanskyy** [comment]
Your core version is 2.3.0 is outdated. The bug is in it. Please use the latest version
