### ISSUE TITLE
Display TEXT on blynk

### ISSUE THREAD

**Issue by key5000** [blynkkk/blynk-library#429]
Hello,

This is my first post here as I'm new to Blynk/Github and also new to programming so please understand the newbie questions:

I have little program that will output number 7, 11 or 15 (depend on source).  
Currently the Serial print can only display 7, 11, or 15.  
How to translate or have Serial print to display Text like:
     Number 7 is for Test1
     Number 7 is for Test2
     Number 7 is for Test3

Here  is the code:

**_void AddressRegistry_3201() {
  result = node.readInputRegisters(0x3201, 2);
  if (result == node.ku8MBSuccess)
  {
    ChargingStatus = node.getResponseBuffer(0x00) / 1.0f;
    if (debug == 1) {
      Serial.print("Charging Status %: ");
      Serial.println(ChargingStatus);     
  } else {
    rs485DataReceived = false;
  }
}
}_**

**Comment by vshymanskyy** [comment]
Please use our community forum
