### ISSUE TITLE
how to change the server address using ESP8266_Standalone_SmartConfig

### ISSUE THREAD

**Issue by hznupeter** [blynkkk/blynk-library#430]
Blynk library version: 0.5.3
IDE: Arduino
IDE version: 1.8.5
Board type: esp8266
Additional modules: none

### Scenario, steps to reproduce

I have tried the [ESP8266_Standalone_SmartConfig](https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_WiFi/ESP8266_Standalone_SmartConfig/ESP8266_Standalone_SmartConfig.ino) and succeed to connect to blynk-cloud.com.

I want to connect to local server,so  i change the `#define BLYNK_DEFAULT_DOMAIN` in [BlynkConfig.h](https://github.com/blynkkk/blynk-library/blob/master/src/Blynk/BlynkConfig.h)，it will connect to the local server.

But if I redefine the BLYNK_DEFAULT_DOMAIN in the *.ino file ,it won't connect to the new server,it still connect to the blynk-cloud.com

**Comment by vshymanskyy** [comment]
Up to my knowledge, there's no way to pass extra data with SmartConfig on ESP8266.
