### ISSUE TITLE
Improve provisioning indication

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#435]
Make a more robust and abstract way to use provisioning statuses. 
More and more devices are coming out with screens. Screen can be used instead of LED monitor. 
For example: M5Stack, Amulet

Right now it's very difficult to build indication routines.

**Comment by vshymanskyy** [comment]
It is already provided in an abstract, extensible way (yes you need to write code). There's no way to implement for every possible situation. Amulet screen is not controllable directly from the device, etc.
