### ISSUE TITLE
ESP32 Using as IDF Component

### ISSUE THREAD

**Issue by Goldenstarc** [blynkkk/blynk-library#444]
I get this errors in make (latest library) for esp32
code is a simple template (  Blynk.begin(auth, ssid, pass) and   Blynk.run() with BlynkSimpleEsp32.h included)

`/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0x68): undefined reference to `BlynkWidgetRead'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0x6c): undefined reference to `BlynkWidgetWrite'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0x9c): undefined reference to `BlynkDelay(unsigned int)'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xa0): undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xa4): undefined reference to `BlynkOnConnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xa8): undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xcc): undefined reference to `GetReadHandler'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xd0): undefined reference to `BlynkWidgetReadDefault'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xd4): undefined reference to `GetWriteHandler'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xd8): undefined reference to `BlynkWidgetWriteDefault'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xdc): undefined reference to `BlynkWidgetWriteInternalPinRTC'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xe0): undefined reference to `BlynkWidgetWriteInternalPinOTA'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xe4): undefined reference to `BlynkWidgetWriteInternalPinACON'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o):(.literal._ZN13BlynkProtocolI21BlynkArduinoClientGenI6ClientEE3runEb[BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)]+0xe8): undefined reference to `BlynkWidgetWriteInternalPinADIS'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BLYNK_LOG_TIME()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkDebug.h:193: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:135: undefined reference to `BlynkDelay(unsigned int)'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::processInput()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:241: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:257: undefined reference to `BlynkDelay(unsigned int)'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:258: undefined reference to `BlynkOnConnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::internalReconnect()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:97: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::processInput()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:294: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:315: undefined reference to `BlynkDelay(unsigned int)'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:316: undefined reference to `BlynkOnConnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:340: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkApi<BlynkProtocol<BlynkArduinoClientGen<Client> > >::processCmd(void const*, unsigned int)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkApiArduino.h:174: undefined reference to `GetReadHandler'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkApiArduino.h:178: undefined reference to `BlynkWidgetReadDefault'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkApiArduino.h:186: undefined reference to `GetWriteHandler'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkApiArduino.h:190: undefined reference to `BlynkWidgetWriteDefault'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::processInput()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:364: undefined reference to `BlynkWidgetWriteInternalPinRTC'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:365: undefined reference to `BlynkWidgetWriteInternalPinOTA'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:366: undefined reference to `BlynkWidgetWriteInternalPinACON'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:367: undefined reference to `BlynkWidgetWriteInternalPinADIS'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::internalReconnect()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:97: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::run(bool)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:158: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:166: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::internalReconnect()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:97: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:97: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkWifi::connectWiFi(char const*, char const*)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkSimpleEsp32.h:41: undefined reference to `BlynkDelay(unsigned int)'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkSimpleEsp32.h:49: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::printBanner()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:82: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkWifi::config(char const*, char const*, unsigned short)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/BlynkSimpleEsp32.h:57: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkProtocol<BlynkArduinoClientGen<Client> >::sendCmd(unsigned char, unsigned short, void const*, unsigned int, void const*, unsigned int)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:434: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Blynk/BlynkProtocol.h:441: undefined reference to `BlynkMillis()'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkArduinoClientGen<Client>::write(void const*, unsigned int)':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Adapters/BlynkArduinoClient.h:109: undefined reference to `BlynkDelay(unsigned int)'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/main/libmain.a(main.o): In function `BlynkArduinoClientGen<Client>::disconnect()':
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Adapters/BlynkArduinoClient.h:68: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Adapters/BlynkArduinoClient.h:68: undefined reference to `BlynkOnDisconnected'
/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/components/blynk-library/src/Adapters/BlynkArduinoClient.h:68: undefined reference to `BlynkMillis()'
collect2: error: ld returned 1 exit status
make: *** [/Users/hamid/Documents/Projects/Hardware/ESP-IDF/arduino-temp/build/app-template.elf] Error 1`

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc for such questions
