### ISSUE TITLE
Arduino IDE can not compile a sketch with pinging instructions

### ISSUE THREAD

**Issue by OslafEman** [blynkkk/blynk-library#447]
I am trying to complete a project in Arduino IDE using an ESP32 (mini kit MH ET Live).
Once a day, the code updates an RTC through NPT. The problem is that if there is no internet connection, the code stops.
To use a conditional that omits this instruction, I would need to verify that there is not an active connection to the Internet. I've thought about sending a ping and waiting for its return, but I have not found a library that works well for ESP32. I tried the libraries and the examples of ESP32_ping and ESP32Ping without success. The pbecchi library now gives an error that says it can not compile for the module that I use.
I would like to know how else I can verify that the ESP32 has an Internet connection.
I am a newbie in this field with three months since I started learning how to program. Hope someone can help me.

**Comment by vshymanskyy** [comment]
Please use http://community.blynk.cc for such questions. Thanks!
