### ISSUE TITLE
Compile time error MKR1010

### ISSUE THREAD

**Issue by frozap** [blynkkk/blynk-library#448]
Blynk library version: 0.5.4
IDE: Arduino
IDE version: 1.8.8
Board type: MKR1010
Additional modules: [...]

### Scenario, steps to reproduce
Blynk Example does not compile because WiFi101 instead of WiFiNINA is used
Added "BlynkSimpleMKR1010.h" to my copy of Blynk library

### Expected Result
Compiles

### Actual Result
Does not compile

**Comment by vshymanskyy** [comment]
@frozap You should use the provided example for your device: https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_WiFi/Arduino_MKR1010/Arduino_MKR1010.ino
