### ISSUE TITLE
Consider adding an ArduBadge badge to README.md

### ISSUE THREAD

**Issue by gilmaimon** [blynkkk/blynk-library#449]
Hi.

A nice addition to the readme page can be a badge from [ArduBadge](https://www.ardu-badge.com/), It will look like this:
[![arduino-library-badge](https://www.ardu-badge.com/badge/Blynk.svg)](https://www.ardu-badge.com/Blynk)
Markdown:
`[![arduino-library-badge](https://www.ardu-badge.com/badge/Blynk.svg)](https://www.ardu-badge.com/Blynk)`

The badge shows:
- That Blynk is available from the Arduino IDE (Library Manager)
- The newest available version (0.5.4 when writing this issue)
- Clicking on the badge redirects users to a custom page with explanation on installing Blynk (from the ide and from a ZIP file). It is great for new users.

Also, badges are awesome.
Thank You! :)

**Comment by vshymanskyy** [comment]
Thanks, I think the existing badges are enough
