### ISSUE TITLE
ESP32 BLE not working with Blynk latest release (0.6.0) library arduino.

### ISSUE THREAD

**Issue by nalindas9** [blynkkk/blynk-library#450]
Blynk library version: [0.6.0]
Blynk android app: [2.27.1]
IDE: [Arduino]
IDE version: [1.8.8]
Board type: [Sparkfun ESP32 Thing]
Additional modules: [...]

### Scenario, steps to reproduce
[Connecting BLE with ESP32 on Blynk]

### Expected Result
[Should Connect]

### Actual Result
[Connects and disconnects.]
![image](https://user-images.githubusercontent.com/44141068/52530120-56d02700-2d26-11e9-9625-5c7749508c92.png)

PS: ESP32 Bluetooth is working fine.

**Comment by vshymanskyy** [comment]
Thanks. Will be fixed soon

**Comment by vshymanskyy** [comment]
Please check on latest version (master branch)

**Comment by vshymanskyy** [comment]
Fixed
