### ISSUE TITLE
A list of connected devices!

### ISSUE THREAD

**Issue by dmamontov** [blynkkk/blynk-library#455]
Good day! Can we get a list of all devices from DeviceSelector in any way? I really needed this opportunity! Since in the implementation of many devices and various DeviceSelector's.

I also wanted to be able to use some kind of Master key to gain access to these devices through a bridge from others.

Would do it myself. But far from Java. The api method is easy to implement, but through web sockets it would be more correct!

Thank!

**Comment by vshymanskyy** [comment]
Sorry, this is probably related to https://github.com/blynkkk/blynk-server

**Comment by dmamontov** [comment]
Thanks!
