### ISSUE TITLE
Blynk library download problem

### ISSUE THREAD

**Issue by mamdobreklapki** [blynkkk/blynk-library#457]
Hello,

Newbie here :)
The library downloads from GitHub very slowly ale stuck in the 1/3.. all the time. 

Cheers!

**Comment by mamdobreklapki** [comment]
https://github.com/blynkkk/blynk-library/releases/tag/v0.6.1

**Comment by vshymanskyy** [comment]
Did you resolve the issue?

**Comment by mamdobreklapki** [comment]
Yes. But actually I don't remember how ;)

pt., 31 maj 2019 o 23:21 Volodymyr Shymanskyy <notifications@github.com>
napisał(a):
