### ISSUE TITLE
[ESP32] SimpleWifi Reconnect

### ISSUE THREAD

**Issue by cujomalainey** [blynkkk/blynk-library#460]
Blynk library version: 0.6.1
IDE: Neovim
IDE version: N/A
Board type: Adafruit Feather HUZZAH32
Additional modules: External LEDs

### Scenario, steps to reproduce
Start a device, let it connect to wifi, disconnect wifi (e.g. disconnect router or turn off hotspot) then plug back in an resume wifi

### Expected Result
Device would resume wifi when it becomes available

### Actual Result
Device is stuck forever re-attempting to connect to the server
```
[21543] Connecting to blynk-cloud.com:80
[E][WiFiClient.cpp:220] connect(): lwip_connect_r: 118
[26544] Connecting to blynk-cloud.com:80
[E][WiFiClient.cpp:220] connect(): lwip_connect_r: 118
```
### Side notes
From what I can tell. It appears the ESP32 needs an explicit disconnect when a WiFi connection fails. I was digging around but I can't tell if it is getting that call from within the framework.

**Comment by cujomalainey** [comment]
For those also experiencing this issue, I found a work around
```
bool connected = false;
void setup() {}
 
void loop()
{
  if(!Blynk.connected() && connected) {
    Blynk.disconnect();
    delay(500);
    connected = false;
    Blynk.begin(auth, ssid, pass);
  } else {
    connected = true;
  }
  Blynk.run();
}

**Comment by pradgood** [comment]
Hi
I tried it but no success
Find a way to repower the board.

**Comment by cujomalainey** [comment]
@pradgood there is a fix upstream in the ESP32 library for this wifi issue, should roll out in the next while https://github.com/espressif/arduino-esp32/issues/2769#issuecomment-491580150

**Comment by vshymanskyy** [comment]
I think this was mainly related to instability of ESP32 Arduino core. Feel free to reopen the issue if it still happens

**Comment by nodoubtman** [comment]
An easy workaround i found on youtube :)

 Blynk.begin(BLYNK_AUTH, ssid, password, "blynk-cloud.com", 8080);

that's all :)
Have a good day.
Marc.
