### ISSUE TITLE
SSL support on ESP8266 broken when using ESP8266 Arduino core 2.5.0

### ISSUE THREAD

**Issue by tssva** [blynkkk/blynk-library#462]
The latest ESP8266 Arduino core, 2.5.0, has switched to BearSSL as the default SSL implementation and deprecated the axTLS based implementation. The WiFiClientSecure API differs between the BearSSL and axTLS implementations which means BlynkSimpleEsp8266_SSL.h no longer compiles properly out of the box.

**Comment by truglodite** [comment]
Interesting that BlynkSimpleEsp8266_SSL.h fails to compile in PIO, but it succeeds for me in Arduino IDE. The first error that shows:

C:\Users\Kevin\.platformio\lib\Blynk_ID415\src/BlynkSimpleEsp8266_SSL.h:76:34: error: there are no arguments to 'time' that depend on a template parameter, so a declaration of 'time' mus
t be available [-fpermissive]

I researched this error a little and I've tried renaming time.h to _time.h etc... nothing I try will remove that error.

**Comment by tssva** [comment]
The issue with the change in SSL library is only present in the ESP8266 Arduino core >= 2.50. Possibly you have a prior version install with the Arduino IDE?

The time.h error occurs systems with case insensitive file systems such as Windows and macOS because the TimeLib library contains a header named Time.h. On case sensitive systems this conflicts with the platform time.h headers file. Using PIO by default the library header files are searched before the platform header files. 

This can be fixed in several ways.

1. The Time.h header file in the TimeLib library directory can be renamed to something else. Every time the library is installed by PIO you will need to rename it.

2. On macOS create a disk image formatted with a case sensitive file system. Mount it and use it as the directory for your project.

3. If running Windows 10 version 1803 (April 2018 update) or higher issue the following the command `fsutil.exe file SetCaseSensitiveInfo C:\folder\path enable` with the path to your project replacing C:\folder\path and Windows 10 will treat your project folder and subfolders as case sensitive.

**Comment by truglodite** [comment]
Thank you tssva, I solved the problem after uninstalling conflicting a global library (Time.h). It is a bit frustrating dealing with the Windows case insensitivity, but it is what it is (not a problem with Blynk).

**Comment by truglodite** [comment]
After further testing of BlynkSimpleEsp8266_SSL.h using securebearssl class to handle an ota observer with core 2.5.2, it seems to compile ok, however I am getting what appears to be 'crashed memory' logs from the device every time I try to connect with my browser. I can post my code and serial debug logs if it helps. 

At this point I am pretty certain this is related to the OP.

**Comment by vshymanskyy** [comment]
Should be fixed in the latest (upcoming) v0.6.6
