### ISSUE TITLE
Can't connect Android app to DFRobot Bluno Beetle BLE

### ISSUE THREAD

**Issue by treii28** [blynkkk/blynk-library#464]
Blynk library version: 0.61
IDE: platformio + clion + android Blynk app
IDE version: platformio 3.6.7
Board type: DFRobot Bluno Beetle BLE (ATMEGA328P + CC2540)

Trying to connect BLE to use in Arduino app. Added widget for connect BLE, it scans and see's "Bluno", clicking "OK" says 'Connecting' then fails with "Can't connect. Retry or choose another device"
I have retried multiple times, I have tried doing it from multiple Android devices.

### Expected Result
Connection

### Actual Result
"Can't connect. Retry or choose another device"

**Comment by treii28** [comment]
Addendum, I notice if I connect to the USB serial, I see the app ID being sent. Is it possibly configuring the wrong device for connection? As mentioned, I am using the sketch from the examples for the DFRobot Bluno with the only modification being the addition of #include <Arduino.h> at the top as required by platformio

**Comment by vshymanskyy** [comment]
https://community.blynk.cc is the best place to discuss such issues!
