### ISSUE TITLE
onion omega example

### ISSUE THREAD

**Issue by boneskull** [blynkkk/blynk-library#47]
I see onion omega was added to the boards list, but I'm confused how to use it.  Is this with the arduino dock or no...?

**Comment by vshymanskyy** [comment]
This is bug in the App. It is not supported yet, until Onion releases their Node.JS support.
Sorry, and keep tuned.

**Comment by doom369** [comment]
@boneskull Added by mistake. Sorry. We will removed from next release.

**Comment by boneskull** [comment]
Wouldn't it be possible to use Blynk with the Onion on the [Arduino Dock](https://store.onion.io/products/arduino-dock)?  Maybe with the Yun libs..?

**Comment by boneskull** [comment]
(using the Arduino toolchain/IDE)

**Comment by vshymanskyy** [comment]
Let us check ;)
Anyway I don't have the Dock, so I can't verify..

**Comment by vshymanskyy** [comment]
Guys, Onion support is on it's way.
I don't think Arduino Dock will be supported for now (need something like a Yun Bridge)..

**Comment by vshymanskyy** [comment]
Blynk Node.js library runs on Omega without problems already.
But Omega doesn't provide 'onoff' library yet, so we don't provide direct pin operations (digital pins).

**Comment by vshymanskyy** [comment]
Blynk library should be installable once Onion releases their firmware with npm support.
