### ISSUE TITLE
ESP32 manage wifi myself (CODE UPDATE) Like: blynk.begin(auth)

### ISSUE THREAD

**Issue by ajaybnl** [blynkkk/blynk-library#470]
**Add the code to BlynkSimpleESP32.h :** 

void begin(const char* auth)
    {
        //connectWiFi(ssid, pass);
        config(auth, BLYNK_DEFAULT_DOMAIN, BLYNK_DEFAULT_PORT);
        while(this->connect() != true) {}
    }

This will let you control the wifi youtself. (**Without Generating Error in Debug**)

**Comment by vshymanskyy** [comment]
You should use `config()` method directly from your sketch, instead of modifying the `begin()`
