### ISSUE TITLE
Question: PC Computer and blink library

### ISSUE THREAD

**Issue by DJuego** [blynkkk/blynk-library#471]
Hi!.  I'm looking for a library that allows me to use bluetooth with C++ in Windows 10 x64 environments, linux distributions, and perhaps in MacOSX environment (crossplattform desktop software) . This library seems to focus on embedded hardware. But it also seems very powerful. Could it be suitable for my purposes?

Thank you!

DJuego

**Comment by vshymanskyy** [comment]
It is recommended to use Python or Node.JS blynk library for use on Windows 10, Linux, Mac (it's just easier to use).
However, neither of these libraries supports Bluetooth on Windows 10 out of the box.
