### ISSUE TITLE
The application is disabled when the server is restarted.

### ISSUE THREAD

**Issue by madixi** [blynkkk/blynk-library#473]
Blynk library version: 0.6.1
IDE: Arduino and gcc in linux Raspberry pi
IDE version: Arduino 1.8.10, gcc Raspbian 8.3.0-6+rpi1
Board type: Arduini Pro Mini, Adruino Nano, Raspberry Pi Zero v1.3
Additional modules: enc28j60 for Arduino, 0fe6:9700 ICS Advent DM9601 Fast Ethernet Adapter for Raspberry Pi Zero

### Scenario, steps to reproduce
For Adruino I have done simple sketch to send heart beat to widget. For Raspberry Pi I have used your example from linux folder. I'm using my own blynk server. When I reboot the blynk server, the application does not try to connect to the server again. 

### Expected Result
The application continues to try to connect to the server until the connection is restored.

### Actual Result
Arduino loses its connection. The application in the Linux ends without any messages.

**Comment by vshymanskyy** [comment]
Please look for solutions on community.blynk.cc
