### ISSUE TITLE
A Callback Function for Blynk.connect() ?

### ISSUE THREAD

**Issue by W-O-X-Y** [blynkkk/blynk-library#479]
Blynk library version: [v0.6.1]
IDE: [Arduino.]
IDE version: [1.8.5]
Board type: [Uno R3]

The Issue: I'm trying to run some code asynchronously while my blynk client (Arduino Uno with ESP8266 as WiFi Shield) is trying to connect to my Blynk local Server, I went through the library and it seems the Blynk.connect() function blocks the code flow while waiting for connectivity to the server.

My question or feature request: is there any way a callback or event can be added to allow execution of code while waiting for connectivity to the server?

**Comment by vshymanskyy** [comment]
You should be able to use this pattern:
```cpp
// Start connection (timeout=0, immediately exit)
Blynk.connect(0);
// Then, periodically:
Blynk.run();
if (Blynk.connected()) { ... }
```
