### ISSUE TITLE
Wrong pattern for Blynk Auth token

### ISSUE THREAD

**Issue by CHE77** [blynkkk/blynk-library#481]
Sometime Blynk Auth token has "-" and "underscore" and pattern="[a-zA-Z0-9]{32}" does not fit for it. But this one "[_-a-zA-Z0-9]{32}" - works fine

https://github.com/blynkkk/blynk-library/blob/master/examples/Blynk.Inject/Template_ESP8266/ConfigMode.h

Line 59. <tr><td><label for="blynk">Auth token:</label></td><td><input type="text" name="blynk" placeholder="a0b1c2d..." pattern="[a-zA-Z0-9]{32}" maxlength="32" required="required"></td></tr>

**Comment by doom369** [comment]
@CHE77 nice catch, could you please send PR?
