### ISSUE TITLE
Android GPS Triger

### ISSUE THREAD

**Issue by szohar** [blynkkk/blynk-library#482]
Hi,

I need to use the GPS trigger when using an Android (since in iOS there is an ID I implemented a code for GPS trigger with Hysteresis).

I need one Trigger for Enter and one for exit with different radiuses.

In the App I added two trigger widgets. As an App developer I can set the circle/location for different radiuses when setting the widget but I can't see how the user will be able to set his own location and radius.

I found numerous answers in this forum that shows the developer how to set it up.

I hope someone can help explain this.

Thanks
Sharon

**Comment by vshymanskyy** [comment]
https://community.blynk.cc is the best place to discuss this!
