### ISSUE TITLE
BLE connection issue with android app

### ISSUE THREAD

**Issue by danyhm** [blynkkk/blynk-library#483]
Blynk library version: [0.6.1]
IDE: [Arduino]
IDE version: [1.8.12]
Board type: [STM32 BluePill]
Additional modules: [HM-10 connected as BLE]
App version : 2.27.15 (local server)

### Scenario, steps to reproduce
After the initial BLE connection, if the connection to BLE is somehow lost (HM-10 LED starts blinking) , the App still shows a blue Bluetooth icon and the setup screen still shows as connected to BLE xxx. one way to reproduce it is to press the power button on phone to lock it. after waking up the connection is lost.

### Expected Result
The App should detect the lost connection and indicate it. also, a reconnection attempt should be made(?)

### Actual Result
the App still shows a blue Bluetooth icon and the setup screen still shows as connected to BLE xxx.

**Comment by vshymanskyy** [comment]
https://community.blynk.cc is the best place to discuss such issues!
