### ISSUE TITLE
Bluetooth examples not compiling (Arduino IDE targeting Mega) with "'SerialBLE' was not declared in this scope"

### ISSUE THREAD

**Issue by MatthewMWR** [blynkkk/blynk-library#485]
Blynk library version: 0.6.1
IDE: Arduino
IDE version: 1.8.12
Board type: Arduino Mega 2560
Additional modules: [...]

### Scenario, steps to reproduce
Trying to use the Bluetooth examples from example browser to get started with Blynk and Bluetooth. For example https://examples.blynk.cc/?board=Arduino%20Mega%202560&shield=HC05%20or%20HC06&example=GettingStarted%2FGetData&auth=1234 

### Expected Result
Should compile

### Actual Result
'SerialBLE' was not declared in this scope

**Comment by FedericoBusero** [comment]
This is not an issue in the blynk library, but in the Blynk Sketch Generator. See https://github.com/blynkkk/blynk-sketch-generator/issues/93

**Comment by MatthewMWR** [comment]
Thanks.
