### ISSUE TITLE
Table value field is limited to 10 chars and not configurable while there's plenty of space on screen

### ISSUE THREAD

**Issue by danyhm** [blynkkk/blynk-library#486]
Blynk library version: [0.6.1]
IDE: [Arduino]
IDE version: [1.8.12]
Board type: [STM32 BluePill]
Additional modules: [HM-10 connected as BLE]
App version : 2.27.15 (local server)]

### Scenario, steps to reproduce
add any row to the table widget with a value field length exceeding 10 chars.

### Expected Result
more chars should be displayed as there's a lot of empty space

### Actual Result
the value field is truncated by 10 chars and "..."

**Comment by vshymanskyy** [comment]
https://community.blynk.cc is the best place to discuss such issues!
