### ISSUE TITLE
Issue with terminal.print("text" + variable);

### ISSUE THREAD

**Issue by maciokeks** [blynkkk/blynk-library#491]
![111](https://user-images.githubusercontent.com/46223194/83322234-4105ae80-a256-11ea-8aba-bcb766a0411e.jpg)
Hi I have issue with print my variable with text on the same line. I will be very thankfully for resolve this problem or comment when I have bug in my code 👍  

`#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

char auth[] = "xxx";

char ssid[] = "xxx";
char pass[] = "xxx";
int i = 100;
WidgetTerminal terminal(V1);
BLYNK_WRITE(V1){
  if(String("sample") == param.asStr()){
    terminal.print("sample with int:" + i);
    terminal.flush();
    
}
}
void setup() {
 Blynk.begin(auth, ssid, pass);
 terminal.clear();
 
}

void loop(){
  Blynk.run();

}`

**Comment by vshymanskyy** [comment]
It's invalid usage of strings.
You should use: 
```
terminal.print(String("sample with int:") + i);
```
