### ISSUE TITLE
Servo control with Arduino WiFi Uno Rev 2 breaks connection to server

### ISSUE THREAD

**Issue by vladSedlov** [blynkkk/blynk-library#494]
Blynk library version: 0.6.1
IDE: Arduino
IDE version: 1.8.13
Board type: Arduino Uno Wifi Rev 2
Additional modules: Servo

### Scenario, steps to reproduce
Control servo motor with slider via virtual pin

### Expected Result
Servo should rotate to the provided angle

### Actual Result
Once Servo motor rotates to the provided angle and afterwards the connection to server fails until reset of the board. The problem reproduces all the time.

**Comment by vshymanskyy** [comment]
This is not related to Blynk library. Please look for a solution on https://community.blynk.cc, or ask your own questions there!
