### ISSUE TITLE
ESP8266_Lib.h: No such file or directory

### ISSUE THREAD

**Issue by varunbk96** [blynkkk/blynk-library#496]
ESP8266_Lib.h: No such file or directory
Iam getting this error as i included the library also

**Comment by varunbk96** [comment]
#define BLYNK_PRINT Serial
#include <ESP8266_Lib.h>
#include <BlynkSimpleShieldEsp8266.h>
// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "yourAUTH";
// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "yourSSID";
char pass[] = "yourpassword";
// Hardware Serial on Mega, Leonardo, Micro...
//#define EspSerial Serial1
// or Software Serial on Uno, Nano...
//#include <SoftwareSerial.h>
//SoftwareSerial EspSerial(2, 3); // RX, TX
// Your ESP8266 baud rate:
#define ESP8266_BAUD 115200
ESP8266 wifi(&Serial);
void setup()
{
 // Debug console
 Serial.begin(9600);
 delay(10);
 // Set ESP8266 baud rate
 Serial.begin(ESP8266_BAUD);
 delay(10);
 Blynk.begin(auth, wifi, ssid, pass);
}
void loop()
{
 Blynk.run();
}

**Comment by varunbk96** [comment]
i included this also by extracting and droping it in a library folder--> https://github.com/blynkkk/blynk-library/releases/latest

**Comment by vshymanskyy** [comment]
https://github.com/blynkkk/blynk-library/issues/128
