### ISSUE TITLE
IDK Different issues

### ISSUE THREAD

**Issue by judah-b2** [blynkkk/blynk-library#503]
Blynk library version: latest
IDE: Arduino
IDE version: latest
Board type: esp32
Additional modules: nothing

### Scenario, steps to reproduce
i want to use my blynk to control the LED_BUILTIN pin of esp32 it dosent work
i downloaded the blynk library from library manager and this is the code
`#define BLYNK_PRINT Serial
#include <WiFi.h>
#include <WiFiClient.h>
#include <BlynkSimpleEsp32.h>

char auth[] = "auth key";

char ssid[] = "ssid";
char pass[] = "password";

void setup()
{
  Serial.begin(9600);

  Blynk.begin(auth, ssid, pass);
}
void loop()
{
  Blynk.run();
}`

### Expected Result
the expected result is when i click the button in my app the led in pin 2 should light up

### Actual Result
`Arduino: 1.8.13 (Windows 10), Board: "NodeMCU-32S, 80MHz, 921600"

In file included from C:\Users\George\Documents\Arduino\BLYNK\ESP32\BasicOperations\BasicOperations.ino:4:0:

C:\Users\George\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp32.h: In member function 'void BlynkWifi::connectWiFi(const char*, const char*)':

C:\Users\George\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp32.h:37:14: error: 'class WiFiClass' has no member named 'mode'

         WiFi.mode(WIFI_STA);

              ^

C:\Users\George\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp32.h:37:19: error: 'WIFI_STA' was not declared in this scope

         WiFi.mode(WIFI_STA);

                   ^

C:\Users\George\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp32.h:39:34: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

             WiFi.begin(ssid, pass);

                                  ^

In file included from C:\Users\user\Documents\Arduino\BLYNK\ESP32\BasicOperations\BasicOperations.ino:2:0:

C:\Users\user\Downloads\arduino-1.8.13\libraries\WiFi\src/WiFi.h:79:9: note:   initializing argument 1 of 'int WiFiClass::begin(char*, const char*)'

     int begin(char* ssid, const char *passphrase);

         ^

In file included from C:\Users\user\Documents\Arduino\BLYNK\ESP32\BasicOperations\BasicOperations.ino:4:0:

C:\Users\user\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp32.h:41:28: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

             WiFi.begin(ssid);

                            ^

In file included from C:\Users\user\Documents\Arduino\BLYNK\ESP32\BasicOperations\BasicOperations.ino:2:0:

C:\Users\user\Downloads\arduino-1.8.13\libraries\WiFi\src/WiFi.h:60:9: note:   initializing argument 1 of 'int WiFiClass::begin(char*)'

     int begin(char* ssid);

         ^

exit status 1

Error compiling for board NodeMCU-32S.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by vshymanskyy** [comment]
https://community.blynk.cc is the best place to discuss such issues!
