### ISSUE TITLE
Error when using bridge & V254-255 pins

### ISSUE THREAD

**Issue by BearScience** [blynkkk/blynk-library#512]
Hello, guys!

I spend a lot of time, because i can't understood why i got error:
error: 'V255' was not declared in this scope

So, the problem is : when we use bridge1.virtualWrite(V254, tempC); for example - we have error
src\main.cpp:127:28: error: 'V254' was not declared in this scope

but if we use for example 
bridge1.virtualWrite(V20, tempC); - it works fine.

Ohh, i spent so much time before i tried other number.

Also - WidgetBridge bridge1(V254); won't work because of the same reason.
And WidgetBridge bridge1(V21); will work's fine.

Thanks!

**Comment by doom369** [comment]
@BearScience hello - https://docs.blynk.cc/#blynk-firmware-virtual-pins-control-blynkvirtualwritevpin-value
![screenshot-docs blynk cc-2021 01 13-22_29_22](https://user-images.githubusercontent.com/1536494/104507060-e3f51800-55ee-11eb-9d21-a884ea322e36.png)
:
