### ISSUE TITLE
SSL error 56

### ISSUE THREAD

**Issue by 10k-resistor** [blynkkk/blynk-library#517]
Blynk library version: 0.6.1
IDE: PlatformIO
IDE version: [...]
Board type: ESP8266 (Wemos d1 mini)

### Scenario, steps to reproduce
I am trying to connect a ESP8266 to my own Blynkserver via SSL. The port is 19443.
`Blynk.config("token", "10.1.2.3", 19443);`

### Expected Result
The controller should connect.

### Actual Result
The connection fails with SSL error 56. Without SSL everything works as expected.

[18204] Current time: Thu Mar 18 20:19:47 2021  
[18204] Connecting to 10.1.2.3:19443  
[18310] SSL error: 56  
[21517] Current time: Thu Mar 18 20:19:50 2021  
[21517] Connecting to 10.1.2.3:19443  
[21608] SSL error: 56

**Comment by vshymanskyy** [comment]
Please disable SSL, and re-flash your device. Unfortunately this is going to be the only cure for this issue.
More details in this comment: https://community.blynk.cc/t/esp8266-ssl-connections-down-using-blynk-wifimanager-esp32-works-fine-non-ssl-8266-works-fine/52144/5?u=vshymanskyy

**Comment by 10k-resistor** [comment]
@vshymanskyy Thanks for your answer.
ThenIi must use blynk without ssl.
