### ISSUE TITLE
W5100 not connecting at all

### ISSUE THREAD

**Issue by coolermister** [blynkkk/blynk-library#520]
Blynk library version: 0.5.0-1.0.0-beta
IDE: Arduino
IDE version: 1.6.13-1.8.13
Board type: Arduino mega 2560(1x chinese, 1x original italian)
Additional modules: Ethernet shield w5100 (1x original italian, 2x chinese)

Hi guys! First of all, thank you for great product! Using it at home for aproximmate year for now...

The issue is simple, blynk sketch just not connecting to blynk server in local network, and in blynk-cloud. 
The bug is strange, year ago or something like that, it all was working. I actually have one mega with w5100 that i program approximate in that time, and it still working. Bug reproduces with all versions of ethernet library that i found, and all blynk-lib versions. Bug behavior is version dependent. It can be just stuck on connecting, or connection timeout. I actualy tried all possible variations and combinations of versions, arduinos, shields, switches, cables, ide versions, and so on. Seem's like i only one who use that hardware) And that is ethernet library, or blynk compability with it, totaly broken(

### Scenario, steps to reproduce
Simply run exapmle sketch [this for example](https://examples.blynk.cc/?board=Arduino%20Mega%202560&shield=Ethernet%20Shield%20W5100&example=GettingStarted%2FBlynkBlink&auth=Token)
With default and all custom parameters:
``` Blynk.config(auth,server_ip, 8080);```
``` Blynk.connect(3333);```
or
``` Blynk.begin(auth,server_ip, 8080);```
or
``` Blynk.begin(auth);```
or
``` Blynk.begin(auth, server_ip, 8080, arduino_ip, dns_ip, gateway_ip, subnet_mask);```
and so on.

### Expected Result
It working!) 
### Actual Result
"Device never connected". If you enable debug printing in sketch, you will see that arduino is stuck, or it spamming that it trying to connect, or cannot get address by dhcp, it depends about lib versions.

**Comment by dmchaplin** [comment]
Did you ever get this working?   I used an Ethernet shield on a Mega 2560 successfully with Legacy Blynk.   But now when I try to migrate it to the new Blynk, I can't get it to work.   I get an IP address and then "Connecting to blynk.cloud:80"

**Comment by coolermister** [comment]
> Did you ever get this working? I used an Ethernet shield on a Mega 2560 successfully with Legacy Blynk. But now when I try to migrate it to the new Blynk, I can't get it to work. I get an IP address and then "Connecting to blynk.cloud:80"

It started to work after i dropped all libraries at all, and reinstall them again

**Comment by dmchaplin** [comment]
Thanks.  I got mine working as well.  The DNS was returning the wrong IP address when querying Blynk.cloud.    I hardcoded the IP in the Begin statement for now, and it started working

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/ for such questions
