### ISSUE TITLE
Improvement: Install of library on Linux (Raspberry)

### ISSUE THREAD

**Issue by hajosc** [blynkkk/blynk-library#521]
Would be good if the Linux (Raspberry) library could be installed system-wide (->sudo make install). That would allow it to be used in existing, larger projects and be provided by packagers for automatic install. Today it's a real pain to figure out all the includes and obj's required and makes distribution of of projects very tedious.

**Comment by hajosc** [comment]
I modified the source to provide a system-wide lib. Currently testing it on a Raspberry, will create a pull request shortly.

**Comment by hajosc** [comment]
Pull request added: https://github.com/blynkkk/blynk-library/pull/526

Appreciate if you could let me know whether you'll accept it or not - I don't want to release code relying on a library that will never be made available...

**Comment by vshymanskyy** [comment]
Blynk is intended to be statically linked
