### ISSUE TITLE
Unable to access the Android app using beta tester link

### ISSUE THREAD

**Issue by DaleSchultz** [blynkkk/blynk-library#522]
I cannot even get started as I cannot access the link for the android app that was provided by Mariia

The link in the email resolves to :
https://play.google.com/store/apps/details?id=cloud.blynk
and that page says: We're sorry, the requested URL was not found on this server.

Mariia said she would get back to me but that was a week ago now.

**Comment by doom369** [comment]
Hello. I'll forward it to Maria.

**Comment by alexkipar** [comment]
@DaleSchultz, can you provide your email used in Play Store? May it be that you use a different email in Play Store from the email in sign up for access link

**Comment by DaleSchultz** [comment]
yes I provided that to Mariia a week ago and again today

Google ID: wilsnack

Dale

**Comment by alexkipar** [comment]
@DaleSchultz, please try the link again - it should work now

**Comment by DaleSchultz** [comment]
yes! thank you ! You can delete the github post !

Dale

**Comment by DaleSchultz** [comment]
.
