### ISSUE TITLE
Blynk Edgent Library for Python

### ISSUE THREAD

**Issue by Tarun75** [blynkkk/blynk-library#528]
Blynk library version: [BLynk.mpy]
IDE: [Thonny Python.]
IDE version: [...]
Board type: [ESP32]
Additional modules: [...]

Please provide library for Wifi Provisioning BlynkEdgent for Python.

### Expected Result
I have developed application on ESP32 on Python, need support on Wifi Provisioning of device with Python Language.Please help.

**Comment by John93-Blynk** [comment]
https://github.com/vshymanskyy/blynk-library-python/tree/master/examples/Edgent_Linux_RPi
