### ISSUE TITLE
Build failing, with "BLYNK_HW_IN is not declared" error

### ISSUE THREAD

**Issue by WL-Amigo** [blynkkk/blynk-library#53]
When trying building blynk-library on raspberry pi B rev1, I got error message like `BlynkApiWiringPi.h : BLYNK_HW_IN is not declared in this scope` and fail to build.

`BLYNK_HW_IN` is missing in [this commit](https://github.com/blynkkk/blynk-library/commit/04d7a64fa4f0daeeb75fe10c280ed72eeeef3985).

And, I worked around this issue by adding preprocessor symbol `BLYNK_NO_INFO` to linux/Makefile : 
```
CFLAGS =   = -I ../ -I ./ -DLINUX -DBLYNK_NO_INFO
```
Then, Building is succeeded, and `blynk` command worked well.
But I think this workaround has some side-effects...

Please check this. Thank you.

**Comment by vshymanskyy** [comment]
Confirmed. Will release a fix very soon. Thanks.
