### ISSUE TITLE
Blynk Library in Python for new Blynk version

### ISSUE THREAD

**Issue by Tarun75** [blynkkk/blynk-library#530]
Blynk library version: [Blynk.mpy]
IDE: [Thonny Python]
IDE version: [...]
Board type: [ESP32]
Additional modules: [...]

### Scenario, steps to reproduce
I have implemented IoT project on above hardware in Python ,Please provide Python library for Blynk new version. I am using the current available library in Python, will that work for new Blynk version and support all new features such as WiFi provisioning etc.
Please help.

**Comment by vshymanskyy** [comment]
Please do not create duplicate issues
