### ISSUE TITLE
Send sensors data between devices.

### ISSUE THREAD

**Issue by NW93** [blynkkk/blynk-library#531]
Hello guys.

I'm using the new version of blynk and I have a question, how can I send sensors data between devices ? 
Currently I'm using automation but by using this method you can control devices only, so what should I do ?

Greetings.

**Comment by doom369** [comment]
Hello. At the moment this is not possible. However, this feature is in our roadmap.

**Comment by NW93** [comment]
> Hello. At the moment this is not possible. However, this feature is in our roadmap.

Thanks for replying sir.

Have a nice day.
