### ISSUE TITLE
C++ libraries for Raspberry (WiringPi)

### ISSUE THREAD

**Issue by gstvgrc** [blynkkk/blynk-library#532]
Blynk library version: [1.0.0.]
IDE: [...]
IDE version: [...]
Board type: [Raspberry 3b]
Additional modules: [...]

### Scenario, steps to reproduce
[Hi, I'm trying to move a servo connected to a RPi3 with the code in examples.blynk.cc (C++). Nodejs way works just fine

1. From website https://github.com/blynkkk/blynk-library/tree/master/linux

git clone https://github.com/blynkkk/blynk-library.git
cd blynk-library/linux
make clean all target=raspberry
./build.sh raspberry
sudo ./blynk --token=MyToken
//by now, ok
sudo nano main.cpp

`
#define BLYNK_PRINT stdout

#ifdef RASPBERRY
 #include <BlynkApiWiringPi.h>
#else
 #include <BlynkApiLinux.h>
#endif
#include <BlynkSocket.h>
#include <BlynkOptionsParser.h>

#include <Servo.h>

static BlynkTransportSocket _blynkTransport;
BlynkSocket Blynk(_blynkTransport);
#include <BlynkWidgets.h>

Servo servo;

BLYNK_WRITE(V3)
{
  servo.write(param.asInt());
}

void setup()
{
  servo.attach(9);
}

void loop()
{
  Blynk.run();
}

int main(int argc, char* argv[])
{
  const char *auth, *serv;
  uint16_t port;
  parse_options(argc, argv, auth, serv, port);

  Blynk.begin(auth, serv, port);

  setup();
  while(true) {
    loop();
  }

  return 0;
}
`
///obviously, I don't have the servo.h file and here comes the error
]

### Expected Result
[move the servo with slider with the cellphone app. At this moment, I don't know how to work with wiring PWM or get a library servo for raspberry in C++]

### Actual Result
When I write: ./build.sh raspberry
then:
[rm main.o ../src/utility/BlynkDebug.o ../src/utility/BlynkHandlers.o ../src/utility/BlynkTimer.o blynk
rm: cannot remove 'main.o': No such file or directory
rm: cannot remove '../src/utility/BlynkDebug.o': No such file or directory
rm: cannot remove '../src/utility/BlynkHandlers.o': No such file or directory
rm: cannot remove '../src/utility/BlynkTimer.o': No such file or directory
rm: cannot remove 'blynk': No such file or directory
make: [Makefile:64: clean] Error 1 (ignored)
g++ -I ../src/ -I ./ -DLINUX -c -O3 -w -DRASPBERRY main.cpp -o main.o
main.cpp:11:10: fatal error: Servo.h: No such file or directory
 #include <Servo.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:70: main.o] Error 1]

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/ for such questions
