### ISSUE TITLE
Error arduino nano + esp8266 shield

### ISSUE THREAD

**Issue by Zanzaux** [blynkkk/blynk-library#534]
OS: Windows 7 64bit
Arduino IDE: 1.8.15
Blynk versione: 1.0.0
Arduino nano con ESP8266 Wi-Fi

In file included from \Documents\Arduino\libraries\arduino_290203\src/Blynk/BlynkApi.h:38:0,
                 from \Documents\Arduino\libraries\arduino_290203\src/BlynkApiArduino.h:14,
                 from \Documents\Arduino\libraries\arduino_290203\src/BlynkSimpleShieldEsp8266.h:29,
                 from \Documents\Arduino\libraries\arduino_290203\examples\Boards_WiFi\ESP8266_Shield\ESP8266_Shield.ino:40:
\Documents\Arduino\libraries\arduino_290203\src/Blynk/BlynkConsole.h:20:10: fatal error: functional: No such file or directory
 #include <functional>
          ^~~~~~~~~~~~
compilation terminated.
exit status 1

**Comment by zerg960** [comment]
Me too. I downgraded to 0.6.1 to get past that error.

**Comment by vshymanskyy** [comment]
This is fixed already. Please use the latest version from master branch.

**Comment by doom369** [comment]
@vshymanskyy maybe we can release the new version?

**Comment by vshymanskyy** [comment]
@doom369 we cannot:
- still pending some changes
- and not tested by our QA team yet

**Comment by Zanzaux** [comment]
Il problema è risolto installando l'ultima libreria Blynk  1.0.0-beta.3 
Grazie.
