### ISSUE TITLE
Please add BRIDGE mode 

### ISSUE THREAD

**Issue by Zanzaux** [blynkkk/blynk-library#535]
Hello Via Blynk 1.0 I use bridge widget to send a value from one device to another where this is displayed via a 1602 lcd, please add this

Thanks.

Blynk library version: [.1.0.0.beta3]
IDE: [Arduino IDE]
IDE version: [...]
Additional modules: [1.8.15]

**Comment by vshymanskyy** [comment]
Bridge is still in the library, you should use 1.0.0 or the version from master branch (not beta)

**Comment by Zanzaux** [comment]
Thanks for replying, unfortunately my translation was not complete, I meant Bridge does not work on Blynk 2.0

**Comment by Zanzaux** [comment]
Thanks for replying, unfortunately my translation was not complete, I meant Bridge does not work on Blynk 2.0

**Comment by vshymanskyy** [comment]
Yes, Bridge is replaced by other mechanisms in Blynk 2.0

**Comment by Zanzaux** [comment]
I can’t migrate some of my projects to the new blynk due to the lack of bridge communication, which is really important to me on the new platform.The very useful thing about bridge is that I was able to send data from different hardware devices such as arduino nano ed nodemcu.

Example 1:
Through arduino nano + esp01 I read a tank, this virtual value is sent via “bridge” to a Nodemcu connected to an lcd1602 display, where the parameters are read simultaneously on both the blynk app and the lcd.

Example 2:
Reading and control system of 2 tanks with 2 arduino nano + esp01 in communication bridge and 1 relay.

In this project there are 2 cisterns about 400 meters apart, one is the main one and the other of rainwater, both of which read the cisterns by sending their values ​​to the app.
When the main tank is equal to or below 30% and the rainfall is greater than 30%, a pump is turned on that sends water to the main tank, when the rainfall value is equal to or below 10% the motor is not activated or if activated it switches off automatically.

a presence check also takes place, i.e. if one of the 2 boards cannot be reached via the bridge, they both restart after 30 seconds, resetting the relays to the off state to prevent the relay from remaining on.

I hope bridge will be reintroduced soon because it is currently a big limitation …
Thank you.
