### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by Huzefamaz** [blynkkk/blynk-library#542]
Arduino: 1.8.12 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:38,
                 from C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/BlynkApiArduino.h:14,
                 from C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266.h:24,
                 from C:\Users\hosaifa\Documents\Arduino\Door_Sensor_Code\Door_Sensor_Code.ino:9:
C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkHandlers.h:152:10: error: redefinition of 'void BlynkWidgetWrite1(BlynkReq&, const BlynkParam&)'
  152 |     void BlynkWidgetWrite ## pin (BlynkReq BLYNK_UNUSED &request, const BlynkParam BLYNK_UNUSED &param)
      |          ^~~~~~~~~~~~~~~~
C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkHandlers.h:160:31: note: in expansion of macro 'BLYNK_WRITE_2'
  160 | #define BLYNK_WRITE(pin)      BLYNK_WRITE_2(pin)
      |                               ^~~~~~~~~~~~~
C:\Users\hosaifa\Documents\Arduino\Door_Sensor_Code\Door_Sensor_Code.ino:92:1: note: in expansion of macro 'BLYNK_WRITE'
   92 | BLYNK_WRITE(V1) {
      | ^~~~~~~~~~~
C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkHandlers.h:152:10: note: 'void BlynkWidgetWrite1(BlynkReq&, const BlynkParam&)' previously defined here
  152 |     void BlynkWidgetWrite ## pin (BlynkReq BLYNK_UNUSED &request, const BlynkParam BLYNK_UNUSED &param)
      |          ^~~~~~~~~~~~~~~~
C:\Users\hosaifa\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkHandlers.h:160:31: note: in expansion of macro 'BLYNK_WRITE_2'
  160 | #define BLYNK_WRITE(pin)      BLYNK_WRITE_2(pin)
      |                               ^~~~~~~~~~~~~
C:\Users\hosaifa\Documents\Arduino\Door_Sensor_Code\Door_Sensor_Code.ino:74:1: note: in expansion of macro 'BLYNK_WRITE'
   74 | BLYNK_WRITE(V1) {
      | ^~~~~~~~~~~
Multiple libraries were found for "BlynkSimpleEsp8266.h"
 Used: C:\Users\hosaifa\Documents\Arduino\libraries\Blynk
 Not used: C:\Program Files (x86)\Arduino\libraries\Blynk
 Not used: C:\Users\hosaifa\Documents\Arduino\libraries\blynk-library-master
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Huzefamaz** [comment]
Dear Blynk Team 
i have this issue on since from 19/7/2021 i use esp32 also same issue

**Comment by NW93** [comment]
Hey there.

Try to delete the not used libraries, for some reason multiple libraries are not allowed.

**Comment by vshymanskyy** [comment]
You have multiple `BLYNK_WRITE(V1)` defined in a single sketch
