### ISSUE TITLE
BlynkSimpleEsp32.h: No such file or directory

### ISSUE THREAD

**Issue by bigkhemmachat** [blynkkk/blynk-library#546]
ESP32_WiFi:41:30: fatal error: BlynkSimpleEsp32.h: No such file or directory
Multiple libraries were found for "WiFi.h"
compilation terminated.
 Used: C:\Users\big_2\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
Multiple libraries were found for "BlynkSimpleEsp32.h"
 Used: C:\Users\big_2\OneDrive\เอกสาร\Arduino\libraries\blynk-master
 Not used: C:\Users\big_2\OneDrive\เอกสาร\Arduino\libraries\Blynk
exit status 1
BlynkSimpleEsp32.h: No such file or directory

how to solve this problem

Blynk library version: [...]
IDE: [Arduino/Energia/MBED Compiler/Platform.IO/Eclipse ...]
IDE version: [...]
Board type: [...]
Additional modules: [...]

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by rameetsingh142** [comment]
Just try to remove the  similar or current libraries  Blynk and try to re install and then try.
