### ISSUE TITLE
blynk library and Energia boards from MSP430 family - compilation error on template

### ISSUE THREAD

**Issue by reaper7** [blynkkk/blynk-library#55]
please rename variable "N" to "NN" inside utility/BlynkUtility.h (from line 26),
because name "N" causer compilation error on ENERGIA/MSP430 launchpads

exactly from:
```
template <unsigned N, typename T>
void BlynkAverageSample (T& avg, const T& input) {
    avg -= avg/N;
    const T add = input/N;
    // Fix for shorter delays
    avg += (add > 0) ? add : -1;
}
```
to
```
template <unsigned NN, typename T>
void BlynkAverageSample (T& avg, const T& input) {
    avg -= avg/NN;
    const T add = input/NN;
    // Fix for shorter delays
    avg += (add > 0) ? add : -1;
}
```
with this little change, launchpads like msp430f5529 works OK with UIPEthernet example

reference:
https://github.com/energia/Energia/issues/785

**Comment by vshymanskyy** [comment]
Fixed. Which exactly board did you use?

**Comment by reaper7** [comment]
I tested this with two boards with success:
1)
LaunchPad w/ msp430f5529 (25MHz)
http://energia.nu/pin-maps/guide_msp430f5529launchpad/

2)
YoshPad G2955 QFN B0 (DEFAULT USCIB0)
this is not official launchpad but project of my friend Yosh from 43oh forum (with my little complicity)
pins definition and pins map on my github:
https://github.com/reaper7/energia_msp430g2955_yoshpad

my modified version of ntruchsess UIPEthernet library for ENERGIA and ESP8266 which works with blynk also available on my github:
https://github.com/reaper7/arduino_uip
