### ISSUE TITLE
Writing to TimeInput widget on Android problem 

### ISSUE THREAD

**Issue by thorathome** [blynkkk/blynk-library#550]
```
Blynk library version: [1.0.1]
IDE: [Arduino in Win 10]
IDE version: [1.8.15]
Board type: [ESP32]
Target mobiles: iOS iPad 14.8, Android 11 (Pixel 3a XL)
```

Hi Blynk team. I've re-implemented the Blynk IoT Time Input widget successfully. Thanks for returning this widget to IoT. 

I am using this widget to get Start/Stop Time Input successfully. 

**I also WRITE to the widget for Start/Stop DISPLAY by day of week. This works perfectly in iOS, not at all in Android.** 

**Two screen shots below. First is iOS. Second is Android.** 
* Top row shows three display-only widgets. They look good on iOS, are empty on Android. I write to them with `Blynk.virtualWrite`. 

Note that the Android version's Time Input widgets do not display the Start/Stop times I wrote to them. They look good on iOS. 

* Second row widgets are for both input and display. On the Android screenshot, you can see values in the first and third widget on the second row. These values are there from having INPUT times, not from writing to the widget.)  

Note also that, when I input Start/Stop times through the widget on EITHER mobile device, those input times are displayed accurately on the other system. In this case, second row, first and third widgets, the Android is displaying the Start/Stop time set on the iOS device. I did not manually write that time to the widget and it displays accurately. It is only when I use `Blynk.virtualWrite` to the widget it does not display on Android. 

I do hope this is clear, and that it is fixable. It would make my Android app much more useful.  I am happy to show my code if helpful. 

Thanks, Blynk team. 

**iPad iOS**
![iOS TimeInput](https://user-images.githubusercontent.com/2821513/134388458-24a19d32-87e7-48b1-bf78-4ed7cf8004c2.PNG)

**Android** 
![Android TimeInput](https://user-images.githubusercontent.com/2821513/134387699-e7ee8815-1a9b-4707-b48f-66ce486372bf.PNG)

**Comment by doom369** [comment]
Hello, thanks for the report. Working on the fix. @alexkipar FYI

**Comment by thorathome** [comment]
Thanks for spending time on this. I thank yoi. My Android thanks you.

**Comment by thorathome** [comment]
It appears the Time Input Widget formatting (HH:MM - HH:MM:SS, etc.) does not sync correctly between iOS and Android. 
I notice that Time Input Widget time formatting changes make in Developer mode at either iOS or Android are not reflected in the other mobile app. 

I see now that the day of week display works properly when writing to the Time Input widget using `Blynk.virtualWrite` on both iOS and Android. It is only the displayed **time** which does not appear on Android. 

I am still testing to diagnose this Android glitch. Hope this is helpful.

**Comment by alexkipar** [comment]
@thorathome thanks, I've forwarded this issue to our QA team for investigation

**Comment by thorathome** [comment]
I just made a post with full demonstration code on community.Blynk. This Android issue/bug is persistent.

I am writing start time, stop time and day of week to the Time Input widget. It works wonderfully on iOS, only partially on Android. Would value a fix for my Android. Thanks.
