### ISSUE TITLE
Blynk & Mblock extension

### ISSUE THREAD

**Issue by tecowong** [blynkkk/blynk-library#554]
I am planning to develop an Blynk & Mblock extension. However, as the limitation from Blynk. This 3 line must be placed before library.
#define BLYNK_TEMPLATE_ID ""
#define BLYNK_DEVICE_NAME ""
#define BLYNK_AUTH_TOKEN "";

#define BLYNK_PRINT Serial

I followed this https://www.mblock.cc/doc/zh/developer-documentation/add-python-common-code.html#%E4%BF%AE%E6%94%B9%E8%BD%AC%E7%A0%81%E6%A8%A1%E6%9D%BF to change its Arduino code. However when I preview the code. It cannot show my changes , how to fix it??

**Comment by vshymanskyy** [comment]
Mblock is not supported. Moreover, it uses Python - so it's not relevant for this C/C++/Arduino library
