### ISSUE TITLE
rgb light control

### ISSUE THREAD

**Issue by fabridelo1969** [blynkkk/blynk-library#556]
Hi

I ask the blynk developers and who may know. is there an example like for the other widgets?

Thank you

**Comment by fabridelo1969** [comment]
Hi everyone

I need help 
I still can't get this widget to work does anyone know what "animation speed" is for and how to set it up?
Thank you

Best Regards

**Comment by FedericoBusero** [comment]
Would be cool to use it with https://github.com/Aircoookie/WLED

**Comment by John93-Blynk** [comment]
I've tried it before with this library.
https://github.com/wilmouths/RGBLed
It worked fairly well.

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/ for such questions
