### ISSUE TITLE
 Swedish letters åäö in email doesn't work

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#56]
Seems like library bug. (Checked sending mail from server with above body - works).

http://community.blynk.cc/t/swedish-letters-aao-in-email/3152

**Comment by vshymanskyy** [comment]
It is not the library bug. The library handles all strings as UTF8 Unicode.
In general, you can try to print your message to serial and see if it works (the terminal should be set to UTF-8 encoding).
Cyrylic worked as expected.
