### ISSUE TITLE
Blynk API useing ESP_IDF

### ISSUE THREAD

**Issue by adamCPP** [blynkkk/blynk-library#577]
Blynk library version: [NA]
IDE: [esp-idf]
Board type: [esp32]

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]
I want to blynk cloud to send information to my device when switch have been changed. How can I accomplish that in less dump way than sending constantly https://blynk.cloud/external/api/get?token=Rps15JICmtRVbFyS_95houlLbm6xIQ2L&v1. I'm useing my own httpClient 

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

Get notified when value change

**Comment by John93-Blynk** [comment]
May I ask you why are you using API?
You can simply use the BLYNK_WRITE(vPIN) function instead. The BLYNK_WRITE is a function called every time device gets an update of Virtual Pin value from the server or app.

**Comment by adamCPP** [comment]
> May I ask you why are you using API? You can simply use the BLYNK_WRITE(vPIN) function instead. The BLYNK_WRITE is a function called every time device gets an update of Virtual Pin value from the server or app.

As I write above I'm not using arduino framework. My project is based on  esp-idf framework. So I can't use this functions. Blynk API is my only hope

**Comment by John93-Blynk** [comment]
Using the API method is not the best approach because there are limitations.
https://docs.blynk.io/en/blynk.console/limits

I'd use Node-RED and the blynk plugin if I were you.

**Comment by adamCPP** [comment]
But arduino library does the job somehow. So I assume there is some kind of API or mqtt protocol to communicate between cloud and device

**Comment by John93-Blynk** [comment]
You can use the API to get data from the server or send data to the server, but as I said before, there's a limitation. 
You can try Node-RED and the blynk plugin method instead.

**Comment by vshymanskyy** [comment]
You should use Arduino Core as a component, then you can run Blynk under it
