### ISSUE TITLE
Cant find nodemcu option in blynk board_wifi examples

### ISSUE THREAD

**Issue by Fauzul110** [blynkkk/blynk-library#578]
Blynk library version: [1.2.0]
IDE: [Arduino]
IDE version: [2.0.3]
Board type: [ESP8266, NODEMCU 1.0]

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]
Im new to using blynk so forgive me if my question might be funny, apparently im using esp8266 nodemcu 1.0 for my work, and i've seen that there are option for nodemcu for wifi board from post that i've seen before but when im trying to find one in this newest blynk, it doesnt have that option, the only one that related most is 8266 but it have 4 different version which is shield, standalone, standalone ssl etc, can you tell me wether nodemcu option for board_wifi is actually there or not, and if no then what is the closest to nodemcu that i can use between those 4 version of esp8266?

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]
Finding the nodemcu option on board_wifi

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
There is no option for nodemcu

**Comment by John93-Blynk** [comment]
Check the examples
https://examples.blynk.cc/?board=NodeMCU&shield=ESP8266%20WiFi&example=GettingStarted%2FBlynkBlink

**Comment by vshymanskyy** [comment]
NodeMCU is just an ordinary ESP8266 device
