### ISSUE TITLE
BlynkSimpleSIM800.h: No such file or directory

### ISSUE THREAD

**Issue by MOKH99** [blynkkk/blynk-library#579]
typed this code
#include <BlynkSimpleSIM800.h> //https://github.com/blynkkk/blynk-library.git
and i got a compellation error 

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]
i entered this code
#include <BlynkSimpleSIM800.h> //https://github.com/blynkkk/blynk-library.git
and I got a compellation error. what seems to be the problem here?

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by John93-Blynk** [comment]
You should provide as much detail as possible, such as the hardware you're using, the library version, etc.

**Comment by MOKH99** [comment]
> You should provide as much detail as possible, such as the hardware you're using, the library version, etc.

I am using a TTGO T-Call V1.4 SIM800L ESP32

**Comment by MOKH99** [comment]
and I seem to notice that in the test file, there is no BlynkSimple800.h was it removed? I've seen someone write this code in adruino and it worked perfectly fine with him

**Comment by John93-Blynk** [comment]
Try this example
https://github.com/blynkkk/blynk-library/blob/master/examples/Boards_GSM/TinyGSM_SIM800_SIM900/TinyGSM_SIM800_SIM900.ino

**Comment by pradumntomar14** [comment]
i am also facing this issue. how can i resolve it
