### ISSUE TITLE
Error when installing library in Arduino: Error: 13 INTERNAL: Library install failed: archive is not valid: multiple files found in zip file top level

### ISSUE THREAD

**Issue by gotfredsen** [blynkkk/blynk-library#581]
Blynk library version: **v1.2.0**
IDE: **Arduino**
IDE version: **2.0.4**
Board type: **ESP32**

### Scenario, steps to reproduce
Download the .zip file: Blynk_Release_v1.2.0.zip
**Arduino** -> `Sketch` -> `Include library` -> `Add .ZIP Library...`

### Expected Result
Library installed

### Actual Result
Library not installed
`Error: 13 INTERNAL: Library install failed: archive is not valid: multiple files found in zip file top level`

### Comments
Firstly, it will work if I just drag the libraries to libraries in Arduino.
Secondly, this library was possibly not meant for Arduino, but the how to install link in the release notes, gives 404

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc for such questions
