### ISSUE TITLE
Cannot retrieve Historical data for GPS Datastream

### ISSUE THREAD

**Issue by zvikapika** [blynkkk/blynk-library#582]
Blynk library version: 1.2
IDE: Arduino IDE
IDE version: 1.8.19
Board type: ESP32 Dev Module
Additional modules: LoRa

### Scenario, steps to reproduce
following documentation pages:
https://docs.blynk.io/en/blynk.cloud/get-device-report
https://github.com/blynkkk/docs/blob/main/blynk.cloud/get-device-report.md
I have tried to craft a URL that will retrieve GPS data written to a virtual pin
https://fra1.blynk.cloud/external/api/data/get?token=*************&period=DAY&granularityType=MINUTE&sourceType=AVG&tzName=Africa/Accra&output=FILE&pin=V0
but I am getting 'no data' message although I can see that there is on the dashboard

### Expected Result
getting a zip download url where I can find a CSV file describing GPS trail over the last day

### Actual Result
{"error":{"message":"No data"}} appears in the browser

**Comment by vshymanskyy** [comment]
This is not related to Blynk Library. Please use https://community.blynk.cc for such questions
