### ISSUE TITLE
error when using blynk with arduino uno and ESP01 

### ISSUE THREAD

**Issue by LapakArduino** [blynkkk/blynk-library#587]
Blynk library version: [1.2.0]
IDE: [Arduino.]
IDE version: [1.8.13]
Board type: [arduino uno ]
Additional modules: []

### Scenario, steps to reproduce
[What you are trying to achieve and you can't?]

### Expected Result
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

##SOME ISSUES WHEN USE BLYNK WITH ARDUINO UNO AND ESP01
i use blynk lib 1.2.0 but its lot of problem, when i use esp01 and connected to arduino 
blynk response : [1234] ping 25ms
PROBLEM : ## it happened because the arduino disconnected with the blynk server
FIX : change esp01 baudrate to lower ex: 38400, change blynk lib to version 1.0.0

**Comment by vshymanskyy** [comment]
https://community.blynk.cc/t/any-arduino-esp8266-at-firmware-to-be-deprecated/66867
