### ISSUE TITLE
Hardcoded BLYNK_TEMPLATE_ID and BLYNK_TEMPLATE_NAME

### ISSUE THREAD

**Issue by adamCPP** [blynkkk/blynk-library#589]
In version 1.3 you added in BlynkApi.h
#if !defined(BLYNK_TEMPLATE_ID) || !defined(BLYNK_TEMPLATE_NAME)
    #error "Please specify your BLYNK_TEMPLATE_ID and BLYNK_TEMPLATE_NAME"
#endif

Before this i have used Blynk with just BLYNK_AUTH_TOKEN obtained during the runtime of the app and it worked.  Please consider to not force users to hardcode this value before compilation.  

### Scenario, steps to reproduce
Compile app with Blynk without hardcoded BLYNK_TEMPLATE_ID and BLYNK_TEMPLATE_NAME

### Expected Result

Compilation succesful

### Actual Result
Preprocesor stops compilation process

**Comment by CyberSteve99** [comment]
I have the same issue. I have had to hard code using version 1.2.0 due to this breaking change.

**Comment by ram-codeswork** [comment]
i cant fiqure this out still i tried even with 1.2.0 but it didnt work any idea?????/

**Comment by vshymanskyy** [comment]
This is required with Blynk 2.0, there's no big deal in hard coding it - it binds your firmware to the specific template or product, which makes sense.

**Comment by vshymanskyy** [comment]
We added these checks for a purpose, and if you omit to add this info, your sketch will fail to work in the future.
Your "fix" to downgrade the library is not viable so I removed the suggestion, not to confuse other users.

You just need to include BLYNK_TEMPLATE_ID and BLYNK_TEMPLATE_NAME when you upgrade your sketch, this is well known and well documented.
