### ISSUE TITLE
SimpleTimer library doesn't work with Espressif (solution included)

### ISSUE THREAD

**Issue by aperepel** [blynkkk/blynk-library#59]
I know, I know, everyone hates to maintain forks for platforms. It looks like `SimpleTimer` library messes with esp12e hardware timers in a bad way - I get callbacks as fast as it can vs every second. I, however, found that `Timer` http://platformio.org/#!/lib/show/75/Timer lib works quite well (I'm sure it will work with regular UNOs of the world, too).

Please update http://docs.blynk.cc/#troubleshooting-flood-error section and enhance the instructions. Or, maybe, switch the library code and examples to use this library instead?

## This one works:
```
#include <Timer.h>

// the timer object
Timer timer;

// a function to be executed periodically
void repeatMe() {
    Serial.print("Uptime (s): ");
    Serial.println(millis() / 1000);
}

void setup() {
    Serial.begin(9600);
    timer.every(1000, repeatMe);
}

void loop() {
    timer.update();
}
```

**Comment by vshymanskyy** [comment]
SimpleTimer doesn't mess with hardware timers at all, it just uses millis() to sense the time.
For now, we will stick with SimpleTimer, unless we see some bigger troubles with it.
Anyway, thanks for reporting :)
