### ISSUE TITLE
Problems with virtual pin double type variables

### ISSUE THREAD

**Issue by parkjunsang0314** [blynkkk/blynk-library#590]
<!-- 블링크 앱을 이용해 주셔서 감사합니다 :-)

이슈를 열기 전에 다음 내용을 읽어보시기 바랍니다: http://docs.blynk.cc https://github.com/blynkkk/blynk-library/wiki https://guides.github.com/features/mastering-markdown

모든 이슈에 대해 다음 정보를 제공해 주세요. [괄호] 및 자리 표시자 텍스트를 답변으로 대체하세요.

블링크 라이브러리 버전: [...] IDE: [Arduino/Energia/MBED 컴파일러/Platform.IO/Eclipse ...] IDE 버전: [...] 보드 유형: [...] 추가 모듈: [...]

- arduino mkr nb 1500 / platform.io / blynk 1.3.0

### 시나리오, 재현 단계 [달성하려고 하는 것과 달성할 수 없는 것]]

Error code when writing a double-type variable to a virtual pin
This issue only occurs in the 1.3.0 version of the library
It works fine in version 1.2.0, so what changed?

### 실제 결과 [재현 단계 이후 실제로 어떤 일이 발생하나요? 가능한 경우 오류 출력 또는 요점 링크를 포함하세요.]

**Comment by parkjunsang0314** [comment]
The best version of the 1.3.0 library is the
Error code when trying to write double type variable to virtual pin on arduino mkr 1500 using platform.io

**Comment by vshymanskyy** [comment]
Fixed
