### ISSUE TITLE
Arduino Nano 33 BLE won't pair via BLE

### ISSUE THREAD

**Issue by maxgerhardt** [blynkkk/blynk-library#593]
Blynk library version: 1.3.2
IDE:Arduino IDE
IDE version: 1.8.19
Board type: Arduino Nano 33 BLE 
Additional modules: None

### Scenario, steps to reproduce
What I'm trying to achieve: Connect the board via BLE to the Blynk app on an iPhone.

1. Flash the Arduino Nano 33 BLE with the following sketch, of course authentication tokens replaced with one gotten from "New Device". (sketch adapted from [here](https://github.com/blynkkk/blynk-library/compare/master...JanSurft:blynk-library:feature/arduino-nano-33-BLE))

```cpp
#define BLYNK_PRINT Serial // Enables Serial Monitor
#define BLYNK_PRINT Serial
#define BLYNK_DEBUG
/* Fill in information from Blynk Device Info here */
#define BLYNK_TEMPLATE_ID "TMPL2-vWld9hg"
#define BLYNK_TEMPLATE_NAME "nano ble33"
#define BLYNK_AUTH_TOKEN "---secret removed ---"

#include <BlynkSimpleArduinoNanoBLE.h>

void setup()
{
  // See the connection status in Serial Monitor
 Serial.begin(9600);
delay(3000);
BLE.setAppearance(0x0080);
  // Here your Arduino connects to the Blynk Cloud.
  Blynk.begin(BLYNK_AUTH_TOKEN,"Blynk");
}

void loop()
{
 BLEDevice central = BLE.central();

  if (central) {    // If BLE is connected...
    Blynk.run();
    BLE.poll();
  }
}
```
2. Open the serial monitor and see startup
```
17:25:13.195 -> [3006] 
17:25:13.195 ->     ___  __          __
17:25:13.195 ->    / _ )/ /_ _____  / /__
17:25:13.195 ->   / _  / / // / _ \/  '_/
17:25:13.195 ->  /____/_/\_, /_//_/_/\_\
17:25:13.195 ->         /___/ v1.3.2 on MBED
17:25:13.195 -> 
17:25:13.195 ->  #StandWithUkraine    https://bit.ly/swua
17:25:13.195 -> 
17:25:13.195 -> 
```
3. Have an iPhone 13 running iOS 17.1
4. Install the Blynk app on it
5.  "Add new device" -> "Find devices nearby"

### Expected Result

Successfull bluetooth connection between the Blynk app on the iPhone and the board.

### Actual Result

No devices are found in the Blynk app.

![grafik](https://github.com/blynkkk/blynk-library/assets/26485477/410f7158-74fa-4abe-a937-620df65fdfb0)

**However**, other Bluetooth apps **do** see the device!

![grafik](https://github.com/blynkkk/blynk-library/assets/26485477/8265a7c2-e9c7-40cb-9a27-1d0fd7a01a2c)

**Comment by vshymanskyy** [comment]
Sorry for the confusion, direct BLE interaction with the device was deprecated and removed in Blynk 2.0.
We may add this feature again in future
