### ISSUE TITLE
Who can fix Error this (Arduino IDE)

### ISSUE THREAD

**Issue by Sornram45** [blynkkk/blynk-library#594]
In file included from c:\Users\User\Documents\Arduino\libraries\Blynk\src/BlynkApiArduino.h:14,
                 from c:\Users\User\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266.h:24,
                 from C:\Users\User\Downloads\NodeMCU_Blynk_2Relay\NodeMCU_Blynk_2Relay.ino:6:
c:\Users\User\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:39:6: error: #error "Please specify your BLYNK_TEMPLATE_ID and BLYNK_TEMPLATE_NAME"
   39 |     #error "Please specify your BLYNK_TEMPLATE_ID and BLYNK_TEMPLATE_NAME"
      |      ^~~~~

exit status 1

Compilation error: exit status 1

**Comment by vshymanskyy** [comment]
Please check https://community.blynk.cc/ of  for answers for such questions
