### ISSUE TITLE
button inversion

### ISSUE THREAD

**Issue by tablatronix** [blynkkk/blynk-library#61]
how do i change the behavior of a button state ?

I want HIGH -_ LOW not low-_high

The gui offers no option , can I force start state in code, or remap to a virtual somehow ?
Seems like a basic option.

**Comment by doom369** [comment]
@tablatronix there is no UI option for that. But you could do it via virtual pin.

```
BLYNK_WRITE(1) {
    if (param.asInt()) {
         //process high
    } else {
         //process low
    }
}
```
