### ISSUE TITLE
 Blynk.email seems limited to 97 characters with ESP

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#62]
http://community.blynk.cc/t/blynk-email-seems-limited-to-97-characters/3340

**Comment by vshymanskyy** [comment]
Added BLYNK_MAX_SENDBYTES config option to control this.

**Comment by doom369** [comment]
Does sketch need to be changed?

**Comment by vshymanskyy** [comment]
Yes, there's no easy way to make it dynamic.
But we can increase it by default for ESP8266, for example.

**Comment by doom369** [comment]
Ok. I think adding comment for Blynk.email() would be ok.

**Comment by doom369** [comment]
Also pls don't forget about docs.
