### ISSUE TITLE
constant reconnecting long pings and timer delay

### ISSUE THREAD

**Issue by tablatronix** [blynkkk/blynk-library#64]
I ran a sketch all night for stability testing
Uses a 2 second simpletimer to send some values to server.

This morning I was getting timer delays of 3 seconds and logging this, restarted and it worked fine.

Ideas? advanced debugging I can enable ?

```
[30371206] Ready (ping: 169ms).
sending
o
[30376248] Connecting to cloud.blynk.cc:8442
sending
o
[30376510] Ready (ping: 174ms).
sending
o
[30381554] Connecting to cloud.blynk.cc:8442
sending
o
[30381819] Ready (ping: 172ms).
sending
o
[30386862] Connecting to cloud.blynk.cc:8442
sending
o
[30387123] Ready (ping: 174ms).
sending
8��������[237] Connecting to ap
[2237] Connected to WiFi
[2237] My IP: 10.0.1.16
[2237] Blynk v0.3.1
blink wait
sending
o
[5001] Connecting to cloud.blynk.cc:8442
[5091] Ready (ping: 1ms).
sending
o
sending
o
sending
o
sending
o
sending
o
sending
o
sending
o
sending
o
sending
o
sending
o
sending
```

**Comment by tablatronix** [comment]
esp8266 standalone

**Comment by doom369** [comment]
please post also code sketch

**Comment by vshymanskyy** [comment]
I'll try reproducing this, thanks.

**Comment by tablatronix** [comment]
I tried reproducing and it seems intermittent, I have not gotten stuck in a bad heartbeat state again, it always seems to come back out on its own. So I don't know what happened unless it was a rate limit check gone wrong.

Ill try to post a simplified sketch if it happens again.

**Comment by tablatronix** [comment]
Reproducible
I will simplify and post example.

**Comment by tablatronix** [comment]
I have not had time to isolate and make a sketch, but I think i know what the problem is.
arduino neopixel interrupt suspensions causes timekeeping drifts for millis and micros.

blynk probably thinks its always timing out or something.

**Comment by tablatronix** [comment]
Looks like this might help my problem
http://community.blynk.cc/t/continuing-loop-while-reconnecting/620

**Comment by vshymanskyy** [comment]
@tablatronix is the bug still there?

**Comment by tablatronix** [comment]
Its been while , but i will test with the new release tomorrow

**Comment by tablatronix** [comment]
Seems to be much more stable, probably fixed.
