### ISSUE TITLE
Hardware state handling - add virtualWrite overloaded method

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#65]
Recently we did a change that allows to change app state with Blynk.virtualWrite(). This is fine for one pin widget. But we have multipin widgets so we need to add overloaded virtualWrite  method in order to  send multiple values with one command.

for instance 
```
Blynk.virtualWrite(V1, 1, 2, 3);
```

**Comment by vshymanskyy** [comment]
It's already there ;)

**Comment by doom369** [comment]
@vshymanskyy could you please add example sketch or doc update? I didn't see it anywhere
