### ISSUE TITLE
Bridge stops working during long-term run

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#67]
http://community.blynk.cc/t/home-domotics/3472

**Comment by vshymanskyy** [comment]
May it be that server "forgets" the auth token bridge setup after device disconnects/reconnects?

**Comment by doom369** [comment]
Yes. On Socket close state is erased.

**Comment by doom369** [comment]
@vshymanskyy Look like we need to extend basic example with reconnection code. WDYT?

**Comment by vshymanskyy** [comment]
I think it's better to remember the configuration.

**Comment by doom369** [comment]
This means infinite session that is not good.

**Comment by vshymanskyy** [comment]
I can easily move Bridge init to BLYNK_CONNECTED() {}
Anyway it was just a shortcoming for token setup in UI, so it should be stable (like dashboard modification)

**Comment by doom369** [comment]
You are right. But I don't want to store additional data until I migrate to DB to have less problems. So let's go with BLYNK_CONNECTED for now.
