### ISSUE TITLE
connection code is blocking

### ISSUE THREAD

**Issue by tablatronix** [blynkkk/blynk-library#68]
i just noticed the connection code is blocking.

Code has issues executing if AP is not available.

All I get in serial is

`[234] Connecting to AP`

**Comment by vshymanskyy** [comment]
In general, we use underlying library which may hang in such cases, and we have no control over it.
What is your connection type?

**Comment by tablatronix** [comment]
esp8266 standalone -> cloud

```
    void connectWiFi(const char* ssid, const char* pass)
    {
...
        while (WiFi.status() != WL_CONNECTED) {
            ::delay(500);
        }
...
```

I don't image this ever times out, retries, or yields()

**Comment by vshymanskyy** [comment]
It was hard to tell without knowing your connection type. )

**Comment by tablatronix** [comment]
What is connection type ?

**Comment by vshymanskyy** [comment]
I will put some timeout for this action. Would it suffice?
Anyway, if you want more advanced WiFi management, we encourage you to use Blynk.config(...) instead of Blynk.begin(..) and manage WiFi in your code.

**Comment by tablatronix** [comment]
I probably will be managing my own wifi.

There probably should be a timeout or a user cancel method.

**Comment by vshymanskyy** [comment]
Closing this issue, as it is not limiting users.
