### ISSUE TITLE
Python Gateway fails to connect on Raspberry Pi

### ISSUE THREAD

**Issue by pieman64** [blynkkk/blynk-library#69]
As detailed at http://community.blynk.cc/t/python-gateway-for-openelec-on-raspberry-pi/3393 the Python Gateway doesn't appear to work on a Raspberry Pi. It attempts to connect and drops the connection within 30 seconds. The Python Gateway works fine with Windows.
Tried Python 2.X and 3.X on the Pi and the results are the same with both.

Are you able to take a look at this?

**Comment by vshymanskyy** [comment]
Does blynk_ctrl.py work as expected?
The gateway is just an early prototype, and we don't put efforts in supporting it, at least for now.

**Comment by pieman64** [comment]
Yes blynk_ctrl.py works fine on the Pi.

**Comment by vshymanskyy** [comment]
I will close this issue, as we have no plans supporting this instance of gateway, nor we have resources for now.
It will be fixed when we get to gateway infrastructure development.
