### ISSUE TITLE
Error in ./blynk-ser.sh script params parsing

### ISSUE THREAD

**Issue by aashvetsov** [blynkkk/blynk-library#76]
When launch ./blynk-ser.sh -s blynk-qa.cloudapp.net
scripts attempts to connect to prod sever.
I see in log 
Resetting device /dev/tty.usbmodem1411...
Connecting: GOPEN:/dev/tty.usbmodem1411,raw,echo=0,clocal=1,cs8,nonblock=1,ixoff=0,ixon=0,ispeed=9600,ospeed=9600,crtscts=0 <-> openssl-connect:cloud.blynk.cc:8441,cafile=/Users/ashvetsov/Desktop/blynk-library/scripts/certs/server.crt,nodelay

**Comment by vshymanskyy** [comment]
This is problem of OS X. Could you try using full option:
./blynk-ser.sh --server=blynk-qa.cloudapp.net
?

**Comment by aashvetsov** [comment]
ok - thanks!
