### ISSUE TITLE
on device/mcu/phone reboot restore state

### ISSUE THREAD

**Issue by tzapu** [blynkkk/blynk-library#8]
this could be a function that a user could add in his code on the MCU to restore the previous state before reboot

the ios app should also restore the visual state if it s closed and restarted. currently it starts with a default state of everything off (buttons for instance)

**Comment by doom369** [comment]
Hi, yeap, you-re right. This is already in progress.

**Comment by tzapu** [comment]
you probably already know this then, but the ios app should also resume state on play/stop :+1: 
is the patch release of the ios app still in review?

**Comment by doom369** [comment]
Yes, exactly this case was already fixed and is under review.

**Comment by tzapu** [comment]
cool, i ll close the issue then and here s hoping for a faster review time,  it s close to 2 weeks now i think and i still can t properly play with my esp :)
