### ISSUE TITLE
What am I missing here? This does nothing. 

### ISSUE THREAD

**Issue by LVLAaron** [blynkkk/blynk-library#85]
Lots of the examples @ https://github.com/blynkkk/blynkkk.github.io/blob/master/Widgets.md

Come to this page. I don't understand how they can possibly do anything. 

Example, Go to controllers/buttons and this is the example sketch: https://github.com/blynkkk/blynk-library/blob/master/examples/GettingStarted/BlynkBlink/BlynkBlink.ino#L48

There is nothing here about a button.

**Comment by tablatronix** [comment]
They just refactored all the examples to autobuild according to commits, I guess these are now borked or at least the links need to be reworked.

You can try the examples for eg. buttons
https://github.com/blynkkk/blynk-library/blob/master/examples/Widgets/PushNotification/PushNotification.ino

**Comment by LVLAaron** [comment]
Thank you!

**Comment by doom369** [comment]
@tablatronix indeed no. All links are correct. @LVLAaron I answered you on community.

**Comment by tablatronix** [comment]
No they aren't


The example links here
https://github.com/blynkkk/blynkkk.github.io/blob/master/Widgets.md

link to these

https://github.com/blynkkk/blynk-library/blob/master/examples/GettingStarted/BlynkBlink/BlynkBlink.ino#L48


Which are basic examples that do nothing.

**Comment by pieman64** [comment]
Read the sketch @tablatronix it includes the following:

 Let’s turn ON your LED with Blynk!
 In this example we'll use Arduino UNO + Ethernet Shield
 5 Steps guide:
 (watch video tutorial here: )
  1. Connect LED to Pin 9
  ( http://arduino.cc/en/uploads/Tutorial/simplefade_bb.png )
 In the Blynk App:
  2. Create New Project
  3. Email yourself Auth Token. You can do it later at any time
  4. Add a Button Widget. Select Pin D9 in Widget's Settings
  5. Press Play icon. Enjoy Blynking!

You might find it hard to believe but you don't require any code to blink with Blynk. Blynk server and the Android / iPhone app takes care of it.

**Comment by doom369** [comment]
@pieman64 exactly. 
@tablatronix There are some widgets that doesn't require any code on hardware side (button with Digital pins, history graph, etc) in such case we provide just basic Blink example.

**Comment by tablatronix** [comment]
wow that went right over my head somehow.. So it auto sets pinmodes for digital pins and buttons.

I guess i forgot this since I started using virtual pins and never looked back.

my bad guys.

**Comment by doom369** [comment]
> wow that went right over my head somehow.. So it auto sets pinmodes for digital pins and buttons.

Yes, exactly. Indeed we just send "pinMode" command when you press "Play" button.
