### ISSUE TITLE
Add WiringPi support to platformio's library.json

### ISSUE THREAD

**Issue by loopj** [blynkkk/blynk-library#87]
I'd love to use blynk in my WiringPi apps when building with platformio. I noticed you guys already have the blynk library published to platformio, but it would be great if the `Blynk*` classes were available for the [wiringpi framework](http://docs.platformio.org/en/latest/frameworks/wiringpi.html) too.

**Comment by loopj** [comment]
I'm guessing we are waiting for platformio 3.0 to revert this: #49?

**Comment by vshymanskyy** [comment]
I don't know if it is working now, but I added wiringpi framework to the library description.

**Comment by vshymanskyy** [comment]
@loopj could you please describe how to check if it's working? Is it working for you now?

**Comment by vshymanskyy** [comment]
@loopj , can I close this bug?

**Comment by vshymanskyy** [comment]
Closed & wontfix due to low priority
