### ISSUE TITLE
Create a list of BLE devices for the first, second, and third release

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#88]
Also please create json file for BT UIDs as we discussed.

**Comment by blynkkk** [comment]
Where is the list?

**Comment by vshymanskyy** [comment]
BLE.json ?

**Comment by blynkkk** [comment]
Why there are no partners of ours? SparkFun, RedBear, but are some odd ones like DFRobot BLE-Link ?

**Comment by vshymanskyy** [comment]
Не прикалуйся, це AirBoard

**Comment by blynkkk** [comment]
I can see only 4 devices... is it the whole list which is planned? 

Title says: Create a list of BLE devices for the first, second, and third release
