### ISSUE TITLE
Last Blynk Update On Android

### ISSUE THREAD

**Issue by dtsrwnis** [blynkkk/blynk-library#89]
After last update when i go to login on my local server as usual i got this message: "Command is bad formed,check syntax and passed params" ..

**Comment by doom369** [comment]
@dtsrwnis please try latest blynk server. which version do you use by the way?

**Comment by dtsrwnis** [comment]
I use 0.12.5.jar 

Anyway i will try with the last one!
Lets see...

**Comment by doom369** [comment]
We changed protocol a bit. For future - you have 2 options:

- Do not update app and automatically;
- Update both server and app at same time;

This is the only way to avoid such issues in future.

**Comment by dtsrwnis** [comment]
0.12.6.jar  --> Works perfect now !

**Comment by doom369** [comment]
Glad, it worked!
