### ISSUE TITLE
can't set virtual pins on startup

### ISSUE THREAD

**Issue by tzapu** [blynkkk/blynk-library#9]
I can t seem to set any pins in the setup function on an esp8266.
i am trying Blynk.virtualWrite(0, 1); after Blynk.begin(auth, ssid.c_str(), pass.c_str());
but it doesn t work. not even with a 2 second delay beforehand. 

the ready serial print comes later than that, after a few connecting attempts
```
done setup
[11287] Connecting to cloud.blynk.cc:8442
[17886] Connecting to cloud.blynk.cc:8442
[24536] Connecting to cloud.blynk.cc:8442
```

is threre any flag to know when connection is actually ready and we can start writing stuff?

**Comment by doom369** [comment]
Yeap, it was added week ago. So you need to take latest Blynk library.

```
if (Blynk.connected()) {
 //do stuff
}
```

**Comment by tzapu** [comment]
thanks
