### ISSUE TITLE
Add one more sketch showing how LED could be used for representing digital pin status

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#97]
Base on this discussions http://community.blynk.cc/t/instructables-how-to-use-virtual-pins/889/12?u=dmitriy
and this 
http://community.blynk.cc/t/virtual-pins-leds-widgetled-blynk-write-arrruggghhhh/4675/16

**Comment by doom369** [comment]
@vshymanskyy please create separate sketch. Such big example just for LED may make user panic

**Comment by vshymanskyy** [comment]
Where should I create it, and which name?

**Comment by doom369** [comment]
Just separate folder. Something like Advanced LED =)
